### PR TITLE
KIALI-990 Fix main content left margin when navigation is collapsed

### PR DESCRIPTION
**Pull request by israel-hdez**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
can you attach a gif to show the differences?

**Comment by jmazzitelli** [comment]
This conflicts with changes that were made in https://github.com/kiali/kiali-ui/pull/494 - not sure how that PR does or does not affect this PR (aside from the code conflicts) - it is possible that PR supercedes this one? I did not see any problems with the left-hand nav when I validated PR #494.

**Comment by jmazzitelli** [comment]
Answering my own question - we do need this PR - it fixes some things in the details pages, not just the graph. @israel-hdez - I think you just need to look at the conflicts and fix them and make sure it doesn't break anything you did here in this PR

**Comment by israel-hdez** [comment]
@jmazzitelli Rebased. I verified that these changes play well with #494.
Do you still need the GIF? Sounds like you already saw the issue.

**Comment by josejulio** [comment]
kiali-990

**Pull request merged**
