### PR TITLE
Adjust list/details layout and title

### PR DESCRIPTION
**Pull request by lucasponce**
Fixes https://github.com/kiali/kiali/issues/3958

Includes:
- Better handle of list on narrowed screens.
image

- "health" is aligned into the left column.
image

- Better treatment of "labels" and "details" columns, adding no wrapping on special cases, for better support of corner cases where a lot of population of labels are used.
image

- Remove redundant titles on details card [1]
image

[1] https://github.com/kiali/kiali-ui/pull/2122#issuecomment-827358907

It doesn't include https://github.com/kiali/kiali/issues/1404 that require special rebase and re-adjust as probably we may want to consolidate validations.

### CODE REVIEW

**Review by lwrigh — APPROVED** [review]
The UX updates look good to me!

**Comment by hhovsepy** [comment]
@lucasponce can you add some 'id' attributes on 'div' or 'ul' tags which are wrapping the W, S and A lines? After the titles removal the xpaths become harder to them and potential bugs can happen.

**Comment by lucasponce** [comment]
> can you add some 'id' attributes on 'div' or 'ul' tags which are wrapping the W, S and A lines? After the titles removal the xpaths become harder to them and potential bugs can happen.

+1, I'll prepare a followup PR.

**Comment by lucasponce** [comment]
@hhovsepy I guess it's ready, let me know if I missed any id/key.

**Review by hhovsepy — APPROVED** [review]
Verified.

**Review by prachiyadav — APPROVED** [review]

**Pull request merged**
