### PR TITLE
[Pf4] MIgrate the Graph Side Panel

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Migrate the Tabs, Nav elements and Icons for the Graph Side panel to PF4.

** Issue reference **
fixes: https://github.com/kiali/kiali/issues/1608

### CODE REVIEW

**Comment by aljesusg** [comment]
Hey @mtho11 Do you need help here ? What is the status?

**Comment by mtho11** [comment]
This is working but still, a styling issue that I need to address tomorrow.

**Comment by mtho11** [comment]
Ok @jshaughn this incorporates your spacing fix around certain states, so I think this is good to go now.

**Comment by aljesusg** [comment]
Hooray

**Comment by mattmahoneyrh** [comment]
Post merge testing, looks good.

**Pull request merged**
