### PR TITLE
KIALI-2392 Enable validations for any backend returned type

### PR DESCRIPTION
**Pull request by burmanm**
** Describe the change **

Instead of manually enabling a type each time (like #1042) this patch makes the backend decide which items are validated. Thus it allows future types (such as those coming from KIALI-2392 backend parts) to display validation results without changes to the UI.

Also, removes code duplication.

** Issue reference **

Part of KIALI-2392 which requires new types.

** Backwards compatible? **

Yes.

** Screenshot **

No UI impact.

### CODE REVIEW

**Comment by hhovsepy** [comment]
Error message is missing when wrong ServiceRole is defined ServiceRoleBinding:
Screenshot from 2019-03-15 17-15-26

Also it does not load any IstioConfig when merged with master.

**Comment by burmanm** [comment]
That's probably because master broke it an hour ago.. ;)

**Comment by hhovsepy** [comment]
master works fine itself,
but with these 2 PRs, "Error loading Istio Config"

**Comment by xeviknal** [comment]
@burmanm  most probably is broken due to one missing error message in here: https://github.com/kiali/kiali/pull/918/files#diff-00df504feeb66372dea6b00a33164c66R153

**Pull request merged**
