### PR TITLE
KIALI-2626 [PF4] Namespace Selector

### PR DESCRIPTION
**Pull request by aljesusg**
Move Namespace selecto to PF4 and aligned with Openshift

JIRA: [KIALI-2626](https://issues.jboss.org/browse/KIALI-2626)

## Before

before_ns_drop_open
before_ns_dropdown

## Openshift

doprodnw_open_okd
dropdown_okd

## Now Kiali

dropdown

### CODE REVIEW

**Comment by hhovsepy** [comment]
Can the dropdown width be fixed so it will not be changed depending on selected namespace length?
Screenshot from 2019-04-15 20-00-43
Screenshot from 2019-04-15 20-00-57

**Comment by aljesusg** [comment]
Move component to contextselector. Thanks @priley86 .
@hhovsepy  can you verify now that the behaviour is correct? Thanks !!!

**Comment by hhovsepy** [comment]
Verified:
Screenshot from 2019-04-16 10-11-31

**Comment by priley86** [comment]
great job w/ this @aljesusg ! I have bookmarked the implementation for possible future OpenShift migration 🎉 🎉

**Pull request merged**
