### PR TITLE
Remove Patternfly-react

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/1857

### CODE REVIEW

**Comment by jotak** [comment]
Not sure if it can be related to the discussion here https://github.com/kiali/kiali-ui/pull/1549 , but I'm seeing the health in error now black instead of red:

Capture d’écran de 2019-11-19 10-41-56

**Comment by lucasponce** [comment]
Agree with @jotak, I guess we have discussed similar.
To me is fine to fix it on this PR or even other, whatever it helps.

**Comment by aljesusg** [comment]
> Agree with @jotak, I guess we have discussed similar.
> To me is fine to fix it on this PR or even other, whatever it helps.

My concern is about why changed PFAlertColor.Danger let me investigate it

**Comment by aljesusg** [comment]
Fixed and merged @jotak @lucasponce https://github.com/kiali/kiali-ui/pull/1552

**Comment by aljesusg** [comment]
@mtho11 you have the power now to finish this ^^

**Comment by lucasponce** [comment]
Nice PR :-)

**Pull request merged**
