### PR TITLE
KIALI-1511 Propagate istio object on tabSelectHandler

### PR DESCRIPTION
**Pull request by lucasponce**
** Describe the change **

Propagate virtualservice/destinationrule parameter when tab is selected.

** Issue reference **

https://issues.jboss.org/browse/KIALI-1511

### CODE REVIEW

**Comment by lucasponce** [comment]
Please @hhovsepy, could you take a look to this PR ?

**Comment by hhovsepy** [comment]
Verified, it is working.

**Comment by lucasponce** [comment]
thanks @hhovsepy ! 
cc @aljesusg ready for review

**Comment by aljesusg** [comment]
LGFM @lucasponce but seems that Jenkins CI is taking so time to finish.

**Comment by lucasponce** [comment]
@aljesusg true, I remember @hhovsepy commented some issues in the internal Jenkins CI pipeline.

**Comment by hhovsepy** [comment]
Jenkins CI/CD is blocked now, please ignore it for now.

**Comment by aljesusg** [comment]
Ok thanks @hhovsepy

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
