### PR TITLE
[PF4] Move MissingIstioSidecar component

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/1799

### CODE REVIEW

**Comment by aljesusg** [comment]
is this in the GA release ? 

I don't remember if we changed this to show the missing SItioSidecar error if the service has some workload without istiosidecar or if this is a bug @lucasponce @xeviknal

**Comment by xeviknal** [comment]
I vaguely remember that we decided to remove the MissingSideCar from service pages because sidecars apply only to workloads and application workloads. But again, I don't remember that quite well.

**Comment by hhovsepy** [comment]
> I vaguely remember that we decided to remove the MissingSideCar from service pages because sidecars apply only to workloads and application workloads. But again, I don't remember that quite well.

Right, now I remember that as well.

**Comment by aljesusg** [comment]
> I vaguely remember that we decided to remove the MissingSideCar from service pages because sidecars apply only to workloads and application workloads. But again, I don't remember that quite well.

But we are showing this icon in the servicelist in the column details...maybe we should remove it or indicate that this is because the service has workloads without istioSidecar

**Pull request merged**
