### PR TITLE
[PF4] Migrate Labels to PF4

### PR DESCRIPTION
**Pull request by xeviknal**
Migration of Labels to PF4.
Closes https://github.com/kiali/kiali/issues/1634

### Screenshots:

Workload details:
Screenshot of Kiali Console (37)

ServiceDetails:
Screenshot of Kiali Console (36)

VirtualService details:
Screenshot of Kiali Console (35)

### CODE REVIEW

**Comment by hhovsepy** [comment]
I see the old design in graph:
Screenshot from 2019-09-26 13-53-33

**Comment by xeviknal** [comment]
Actually this is not wrong. As mention with others from graph, they said that they aren't actually labels from k8s. They are just information we want to show in the sidebar. 
Then, we agreed that labels in the those labels in the screenshot should be like shown.

**Comment by jmazzitelli** [comment]
> As mention with others from graph, they said that they aren't actually labels from k8s.

Here's my comments I emailed earlier - I'll post here in this PR to keep a record of it here:

===

One thing we need to be clear about here - we should not be showing these using the "kubernetes labels" L&F if what we are showing are NOT actual k8s labels (and in many cases, they are NOT actually coming from k8s label fields - they may have the same key/values, but they aren't really coming from k8s labels.)

For example, many times when you see "app" and "version" in Kiali, they are coming from Prometheus. Although in some/most cases they will be 1-to-1 with the actual k8s labels, sometimes they are NOT (think of the times when people are using the newer format of the k8s labels like app.kubernetes.io/name and app.kubernetes.io/version). Also, we don't show ALL the labels on k8s objects - we normally are only showing app and version. So if you didn't know any better, you would think those are the ONLY k8s labels on their objects when most times that is not true (they will have other labels that we just do not show).

So if we know the data is NOT coming from queries that return actual k8s labels, then we should not visualize them using the PF L&F that OpenShift uses to visualize labels - otherwise, it will confuse people thinking their k8s objects have different labels when they don't.

**Comment by jotak** [comment]
Not sure why, but unlike @hhovsepy I'm seeing the new design in the graph. To me it could be fine but it contradicts what @jmazzitelli says. So, not sure if this is ok or not.

**Comment by xeviknal** [comment]
@jotak you are right. There was a bug in master at the time I create this branch. It was fixed https://github.com/kiali/kiali-ui/pull/1445
If you see the files changed in this PR, graph files haven't been changed.

**Comment by xeviknal** [comment]
@jotak @hhovsepy I've rebased with master. Graph doesn't have this labels anymore. Now this branch is coherent with what @jmazzitelli and @jshaughn said.

**Pull request merged**
