### PR TITLE
Iter8 ui fixes

### PR DESCRIPTION
**Pull request by lucasponce**
More work in the UI to consolidate a basic end-to-end flow with the Iter8 extension.

It requires https://github.com/kiali/kiali/pull/2542

@jadeyliu939 
cc @kiali/iter8 

Note, this is a Step 0 feature.
The goal is to consolidate a basic end-to-end flow where it can be a starting point of refinements, UX discussions and projection of more integration of Iter8 Experiments info in other areas of Kiali.

This PR is not intended to start a UX discussion itself, but to have a primitive skeleton that would help to demo and progress on more discussions (additional followup issues will be created after this).

Basic UI introduced by this PR:

- Iter8 main extension entry, with list of Experiments:
image

- Iter8 Experiment Create New Experiment page:
image

- Iter8 Experiment Details page:
image

Instructions about how to test in minikube are described in https://github.com/kiali/kiali/pull/2542

After rebase, some behaviour seems broken, so I won't remove the DNM until it's consolidated.

### CODE REVIEW

**Comment by hhovsepy** [comment]
Traffic split is always set to 0.
Screenshot from 2020-03-24 10-19-10

**Comment by lucasponce** [comment]
Thanks @hhovsepy.

From the CLI, can you get a kubectl get experiments exp4 -n bookinfo -o yaml ?

Just to check where the problem is located.
It seems in iter8 side but I want to check if Kiali query failed.

**Comment by hhovsepy** [comment]
apiVersion: iter8.tools/v1alpha1
kind: Experiment
metadata:
  creationTimestamp: "2020-03-24T09:17:56Z"
  generation: 1
  name: exp4
  namespace: bookinfo
  resourceVersion: "269328"
  selfLink: /apis/iter8.tools/v1alpha1/namespaces/bookinfo/experiments/exp4
  uid: 4c249fbc-38f2-4734-b0aa-478ccf567322
metrics: {}
spec:
  analysis: {}
  targetService:
    apiVersion: v1
    baseline: reviews-v1
    candidate: reviews-v3
    name: reviews
    namespace: ""
  trafficControl:
    maxTrafficPercentage: 50
    strategy: check_and_increment`
`

**Comment by lucasponce** [comment]
@hhovsepy ok, thanks it seems is in iter8
I will cc @kiali/iter8 but they commented me they will promote a new iter8 version in stable we will use for testing.

**Comment by lucasponce** [comment]
@hhovsepy I've updated the backend + frontend PRs.
Note that experiment also holds "status", meaning that we would need to introduce a refresh as it updates the info about % once the experiment is progressing.

Let me know if more or less the basic CRUD is working fine for you.

**Comment by abonas** [comment]
this is looking great.
a few minor comments:
- left side nav says "experiment" instead of experiments so not consistent with the rest of "services, workloads", etc. - the rest of the menu items.
- the wizard - first field, inside the field it says "exteriment" (typo)
- the wizard - first field probably needs a red star next to it indicating it's mandatory

**Comment by jadeyliu939** [comment]
@lucasponce and @hhovsepy  We have a new stable release that is coming, which will have a couple of changes on the CRD. Basically, a new field successCriteria and changes in the format of startTimestamp and endTimestamp. I have the prototype in UI/backend to handle that. 

@abonas Thanks for the comments about the wizard of creating new experiment. Iter8 team is in the process of deciding more field and requirement fields requirement as our CRD will be changed once the new stable release is out.

**Comment by lucasponce** [comment]
@hhovsepy I've sent a couple of minor fixes on this, let me know how it looks like.

@yhliu939 we can wait and consolidate here or merge these PRs (backend+frontend) this week and adjust later.

The idea is to have something consolidated as preliminar step, from here we can progress.
Perhaps, could be good to introduce versions in iter8.

At some point we will need to match kiali x.y.z with iter8 a.b.c, today we are in early developer and we can more or less sync these changes but having also a fixed version would help too.

(It can be done after this preliminar work, and it can be documented in the instructions, but at least to help users to install a specific version of both projects).

**Comment by lucasponce** [comment]
I add back the "do not merge" label.
After rebasing with master I see some regression in styles and logic.
I need to take a closer look at them.

**Comment by hhovsepy** [comment]
@lucasponce verified the Delete functionality and the latest UI fixes:
Screenshot from 2020-03-31 17-23-47

**Pull request merged**
