### PR TITLE
Do not try to fetch traces for a service entry

### PR DESCRIPTION
**Pull request by jotak**
Fixes https://github.com/kiali/kiali/issues/3461

### CODE REVIEW

**Comment by jotak** [comment]
I'm just removing here the "traces" side-panel for service entries. The reason is that, it's not only that we can't find any trace, it's worse than that: we are trying to fetch the k8s service object to get the associated "app" prior to running jaeger query, but with service entries it just doesn't make sense. We can eliminate that whole use case.

**Review by hhovsepy — APPROVED** [review]
Verified:
Screenshot from 2020-12-01 11-52-37

**Review by jshaughn — APPROVED** [review]
Totally makes sense.

**Review by aljesusg — APPROVED** [review]
LGFM

**Pull request merged**
