### PR TITLE
testpr

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: kiali-ui-test-pr [#19](https://paste.fedoraproject.org/paste/Ro4FInU-ktwIatBpjClB4Q)
  * :red_circle: Istio-and-Kiali-on-Openshift [#431](https://paste.fedoraproject.org/paste/lAzZgJVbeJIS-4-WbHY1PA)
  * :red_circle: Kiali-on-Openshift [#140](https://paste.fedoraproject.org/paste/KoSX5MKUzLL1yDV4jTVMGQ)
--------------

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: kiali-ui-test-pr [#20](https://paste.fedoraproject.org/paste/GGHF7mytX~qhGivPR39whg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#432](https://paste.fedoraproject.org/paste/k8nO96CYpUxlp2RhWcmVnQ)
  * :heavy_check_mark: Kiali-on-Openshift [#141](https://paste.fedoraproject.org/paste/B1DRnc5kZwmmW3QCZO~sMw)
  * :heavy_check_mark: Bookinfo-traffic-generator [#161](https://paste.fedoraproject.org/paste/XZwcLezKUINm9GlJJnVNvQ)
  * :heavy_check_mark: Kiali-Test-Mesh [#150](https://paste.fedoraproject.org/paste/i8bV5wN5Pn9g92N5aKXCnA)
  * :red_circle: run-python-rest-tests [#125](https://paste.fedoraproject.org/paste/fVRLHi6KKxw~jm2uTe~rww)
  * :heavy_check_mark: run-python-ui-tests [#204](https://paste.fedoraproject.org/paste/~ZsYV5leshEjO4~I0wKwZQ)
--------------

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
KIALI_HOSTNAME=kialiuipr296-istio-system.openshift3.jonqe.lab.eng.bos.redhat.com

--------------

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: kiali-ui-test-pr [#22](https://paste.fedoraproject.org/paste/Yw79RHpXGPp0hv39TMYUgg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#496](https://paste.fedoraproject.org/paste/JNtbEPnzpCQZsUGVU-IWVw)
  * :heavy_check_mark: Kiali-on-Openshift [#209](https://paste.fedoraproject.org/paste/kcYCodI07qLuw43gHRSBjw)
  * :heavy_check_mark: Bookinfo-traffic-generator [#211](https://paste.fedoraproject.org/paste/d7Rj1a~ddcCAN1ifKmJ2Dg)
  * :heavy_check_mark: Kiali-Test-Mesh [#184](https://paste.fedoraproject.org/paste/D4EJCx7f3Fe8brNu6g2itA)
  * :red_circle: run-python-rest-tests [#159](https://paste.fedoraproject.org/paste/gsS5yLWntG4zh55D4yWvTQ)
  * :red_circle: run-python-ui-tests [#232](https://paste.fedoraproject.org/paste/~tOJjdI5RwNVcFktbFZ-zg)KIALI_HOSTNAME=kialiuipr296-istio-system.openshift3.jonqe.lab.eng.bos.redhat.com

--------------

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: kiali-ui-test-pr [#24](https://paste.fedoraproject.org/paste/OeQmg5kxXR0K5OA1wqUqdg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#507](https://paste.fedoraproject.org/paste/h8u19yENgC-fsC1X5Rax~A)
  * :heavy_check_mark: Kiali-on-Openshift [#218](https://paste.fedoraproject.org/paste/uodsgtkvDh~PltJdIowOMw)
  * :heavy_check_mark: Bookinfo-traffic-generator [#218](https://paste.fedoraproject.org/paste/qYa4OgnpSPpOJRBT62RoSg)
  * :heavy_check_mark: Kiali-Test-Mesh [#190](https://paste.fedoraproject.org/paste/DwlTEB3-H6cjDtB2GlmKYg)
  * :red_circle: run-python-rest-tests [#161](https://paste.fedoraproject.org/paste/Qw0JVAYvurIiDykz04XLSQ)
  * :red_circle: run-python-ui-tests [#239](https://paste.fedoraproject.org/paste/Y0c6shpsKzQyaKMxS7HZuA)


KIALI_NAME=kialiuipr296-istio-system

--------------

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: kiali-ui-test-pr [#25](https://paste.fedoraproject.org/paste/jdis0CWgt34~k5El6mDJhQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#532](https://paste.fedoraproject.org/paste/~x~rrf8xLn5jER7rqEjgCQ)
  * :heavy_check_mark: Kiali-on-Openshift [#248](https://paste.fedoraproject.org/paste/ZrsgLHWAu5LQar9-UMxXdg)
  * :heavy_check_mark: Bookinfo-traffic-generator [#242](https://paste.fedoraproject.org/paste/ppNAt02gy8oqYw3VCJjR1w)
  * :black_circle: Kiali-Test-Meshes-Ansible [#16](https://paste.fedoraproject.org/paste/OcFNq8lbDjPWx8JapMb91Q)


KIALI_NAME=kialiuipr296-istio-system

--------------

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: kiali-ui-test-pr [#26](https://paste.fedoraproject.org/paste/SYmpSSnu5nAr1S3~ij~CXg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#534](https://paste.fedoraproject.org/paste/pSM64-I72ChRML8JvAxApw)
  * :heavy_check_mark: Kiali-on-Openshift [#250](https://paste.fedoraproject.org/paste/zRsvCxm-Y5h65YEuoMwxdQ)
  * :heavy_check_mark: Bookinfo-traffic-generator [#244](https://paste.fedoraproject.org/paste/ViD3aRpRFutcqPdrz9Dg7Q)
  * :red_circle: Kiali-Test-Meshes-Ansible [#18](https://paste.fedoraproject.org/paste/x8QjLLq8b4Uq5q-bdKlTzg)


KIALI_NAME=kialiuipr296-istio-system

--------------

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci keep_kiali

**Comment by rhqci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: kiali-ui-test-pr [#28](https://paste.fedoraproject.org/paste/MX8kqVWGUGbzvuQigs0YsQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#536](https://paste.fedoraproject.org/paste/yW88a2nZ84sMvwNy8gXDaQ)
  * :heavy_check_mark: Kiali-on-Openshift [#252](https://paste.fedoraproject.org/paste/Zg6I4lMmT9OvAbZyQBeiAA)
  * :heavy_check_mark: Bookinfo-traffic-generator [#246](https://paste.fedoraproject.org/paste/7yAaDD79q0r0ihGn1t7khA)
  * :heavy_check_mark: Kiali-Test-Meshes-Ansible [#20](https://paste.fedoraproject.org/paste/1LZyteDaVHelKqj86QodPw)
  * :red_circle: run-python-rest-tests [#167](https://paste.fedoraproject.org/paste/lI1YahhDlUdEEYSlj587og)
  * :red_circle: run-python-ui-tests [#260](https://paste.fedoraproject.org/paste/E4PwIOfydHdclRHarWFS2w)


KIALI_NAME=kialiuipr296-istio-system

--------------

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: kiali-ui-test-pr [#29](https://paste.fedoraproject.org/paste/-6Scqi7k2inN7G0Dgy-GPQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#542](https://paste.fedoraproject.org/paste/fao9xeh3ktZxZAjE7Yowag)
  * :heavy_check_mark: Kiali-on-Openshift [#257](https://paste.fedoraproject.org/paste/rsLrfBeqg7~k-3ymNxICOA)
  * :heavy_check_mark: Bookinfo-traffic-generator [#251](https://paste.fedoraproject.org/paste/ME2Qvs7a~8lQG7Mf6V27Dg)
  * :heavy_check_mark: Kiali-Test-Meshes-Ansible [#25](https://paste.fedoraproject.org/paste/oHZ27pzIjqTiSkhO2~iOMw)
  * :red_circle: run-python-rest-tests [#169](https://paste.fedoraproject.org/paste/ytjglwDSt~ceBmaIG-6nfA)
  * :red_circle: run-python-ui-tests [#264](https://paste.fedoraproject.org/paste/AQHb1w1JyRNvpzSrFFwK3Q)
--------------

**Comment by mtho11** [comment]
This has been open a long time for a one line change - merge or close?

**Comment by lucasponce** [comment]
@hhovsepy do we need this PR open ?
I think this was used for testing the bots with the CI.
I am reviewing the pending PR, if it is not needed, perhaps we can close it and re-opened when more work is necessary.

**Pull request closed without merging**
