### PR TITLE
Enable/Disable/Remove Istio Auto Injection on Namespace/Workload

### PR DESCRIPTION
**Pull request by lucasponce**
Fixes https://github.com/kiali/kiali/issues/3125
Fixes https://github.com/kiali/kiali/issues/3124
Requires https://github.com/kiali/kiali/pull/3130

@hhovsepy I've introduced a explicit "Disabled" vs "Removed" as this opens the possibility to annotate workloads individually.

Lucas

### CODE REVIEW

**Comment by lucasponce** [comment]
Also, I think we should introduce the Enable/Remove/Disable label at workload level too.
As basically a "istio-injection: disabled" placed at namespace works together with a "sidecar.istio.io/inject: true" placed at workload level.

**Comment by lucasponce** [comment]
Thanks @hhovsepy I'm going to hold this PR to add the same operation but at workload level, I think it makes sense.

**Comment by lucasponce** [comment]
@hhovsepy I've added support to combine namespace and workload istio label + annotations.

image

Otherwise end-user should find odd to disable a namespace without possibility to annotate a specific workload or viceversa, to disable a specific workload when a namespace is annotated.

I'm going to review the travis in the CI, but I've added backend + operator PRs for this.

**Comment by hhovsepy** [comment]
@lucasponce one note, from UX perspective:
1. Enable namespace.
2. disable workload.
3. disable namespace
4. enable namespace
Workload remains disabled.
Shouldn't it be better each time changing namespace it force overrides the child workloads?

**Comment by lucasponce** [comment]
> Shouldn't it be better each time changing namespace it force overrides the child workloads?

Not sure, basically Kiali is performing these operations 
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#understanding-what-happened

So, manipulating namespace label and/or workload annotation but it's not adding more logic here.

It's seems that using CLI both (namespace, workload) are also independent, so, I guess in a first approach we can try go add them as well.

**Pull request merged**
