### PR TITLE
KIALI-2429 Show namespace-wide mTLS in the overview card

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **

Show namespace mTLS information into Overview Page.

** Required Pull Request **
https://github.com/kiali/kiali/pull/912

** Issue reference **

https://issues.jboss.org/browse/KIALI-2429

** Screenshot **
- bookinfo ns-wide mTLS explicitely enabled.
- nodejs-prom ns-wide mTLS explicitely disabled.

Mesh-wide mTLS enabled:
Screenshot-2019-3-13 Kiali Console

Mesh-wide mTLS disabled: 
Screenshot-2019-3-13 Kiali Console(2)

Mesh-wide mTLS partly enabled:
Screenshot-2019-3-13 Kiali Console(1)

### CODE REVIEW

**Comment by abonas** [comment]
@xeviknal is it only me, or the lock is very "pale"? (very light grey) - can it be more dark?
light grey might look like disabled

**Comment by xeviknal** [comment]
@abonas I agree with you. What about this? It uses pf-black-600 #72767b, the color used for the icons in the main menu.
Screenshot-2019-3-13 Kiali Console(3)

**Comment by abonas** [comment]
much better :)

**Comment by lucasponce** [comment]
IstioWizards/TrafficPolicy.tsx has a dependency on mTLS Global, I guess that now it needs to check global + namespace.
So I suggest to rebase and also apply those changes there.
It should be a minor one, but better to have it sync-ed here.

**Comment by xeviknal** [comment]
@lucasponce changes applied. Dropdown now takes into account the status of mTLS in service namespace.

**Comment by hhovsepy** [comment]
Verified:
When Mesh-wide mTLS: On all services wizards the TLS is selected by default.
When namespace-wide mTLS: Only on that namespace's wizard the TLS has default selected value.

**Pull request merged**
