### PR TITLE
Kiali-2586 Update many of the libs except for React.js related.

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
It has been a while since we have updated the libs because we wanted things to stabilize.
Now that we have some more time, updating the libs is a priority.

** Issue reference **
https://issues.jboss.org/browse/KIALI-2586

** Backwards compatible? **
yes

### CODE REVIEW

**Comment by mtho11** [comment]
The UI seems to work fine with these changes. 
I do see failures with `OverviewPage.test.tsx` though. And this is what is stopping the merge. Maybe @jotak can take a look?

**Comment by jotak** [comment]
hmm I don't see any test failure, @mtho11 , the build passed. Just some warnings about something deprecated, but we can fix it later, it's not blocking.

**Comment by mtho11** [comment]
That is really strange you don't see the test failures and I don't see the cytoscape error.
Here is the test error that I see. Only one file with errors: `OverviewPage.test.tsx`:

```
Summary of all failing tests
 FAIL  src/pages/Overview/__tests__/OverviewPage.test.tsx (7.908s)
  ● Overview page › filters failures no match

    Error
      [object Object] thrown

  ● Overview page › multi-filters health match

    expect(received).toHaveLength(length)

    Expected value to have length:
      0
    Received:
      {Symbol(enzyme.__unrendered__): null, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): {Symbol(enzyme.__unrendered__): <Provider store={{"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}><BrowserRouter><OverviewPage /></BrowserRouter></Provider>, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): [Circular], Symbol(enzyme.__node__): {"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 1794, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 1073741823, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}, Symbol(enzyme.__nodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": [Object], "_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "props": [Object], "refs": [Object], "state": null, "store": [Object], "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter … />, "store": [Object]}, "ref": null, "rendered": {"instance": [BrowserRouter], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": [Object]}}}}, Symbol(enzyme.__node__): {"instance": null, "key": undefined, "nodeType": "function", "props": {"accented": true, "aggregated": true, "aggregatedMini": false, "cardRef": null, "children": [<CardTitle className="">a</CardTitle>, <CardBody className=""><OverviewStatuses … /><div … /></CardBody>], "className": "", "matchHeight": true}, "ref": null, "rendered": {"instance": <div class="card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"><h2 class="card-pf-title">a</h2><div class="card-pf-body"><a … /><p … /><div … /></div></div>, "key": undefined, "nodeType": "host", "props": {"children": [<CardTitle … />, <CardBody … />], "className": "card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"}, "ref": null, "rendered": [{"instance": null, "key": undefined, "nodeType": "function", "props": [Object], "ref": null, "rendered": [Object], "type": [Function CardTitle]}, {"instance": null, "key": undefined, "nodeType": "function", "props": [Object], "ref": null, "rendered": [Object], "type": [Function CardBody]}], "type": "div"}, "type": [Function Card]}, Symbol(enzyme.__nodes__): [{"instance": null, "key": undefined, "nodeType": "function", "props": {"accented": true, "aggregated": true, "aggregatedMini": false, "cardRef": null, "children": [<CardTitle … />, <CardBody … />], "className": "", "matchHeight": true}, "ref": null, "rendered": {"instance": <div class="card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"><h2 … /><div … /></div>, "key": undefined, "nodeType": "host", "props": {"children": [Array], "className": "card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"}, "ref": null, "rendered": [[Object], [Object]], "type": "div"}, "type": [Function Card]}], Symbol(enzyme.__rootNodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 1794, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 1073741823, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": {"componentDidUpdate": [Object], "getDerivedStateFromProps": true, "getSnapshotBeforeUpdate": true, "setState": [Object]}}}}}
    received.length:
      1

      137 |     ]).then(() => {
      138 |       mounted!.update();
    > 139 |       expect(mounted!.find('Card')).toHaveLength(0);
      140 |       done();
      141 |     });
      142 |     mountPage();

      at src/pages/Overview/__tests__/OverviewPage.test.tsx:139:37

  ● Overview page › multi-filters health no match

    expect(received).toHaveLength(length)

    Expected value to have length:
      1
    Received:
      {Symbol(enzyme.__unrendered__): null, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): {Symbol(enzyme.__unrendered__): <Provider store={{"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}><BrowserRouter><OverviewPage /></BrowserRouter></Provider>, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): [Circular], Symbol(enzyme.__node__): {"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 2348, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 1073741823, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}, Symbol(enzyme.__nodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": [Object], "_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "props": [Object], "refs": [Object], "state": null, "store": [Object], "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter … />, "store": [Object]}, "ref": null, "rendered": {"instance": [BrowserRouter], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": [Object]}}}}, Symbol(enzyme.__node__): undefined, Symbol(enzyme.__nodes__): [], Symbol(enzyme.__rootNodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 2348, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 1073741823, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": {"componentDidUpdate": [Object], "getDerivedStateFromProps": true, "getSnapshotBeforeUpdate": true, "setState": [Object]}}}}}
    received.length:
      0

      166 |     ]).then(() => {
      167 |       mounted!.update();
    > 168 |       expect(mounted!.find('Card')).toHaveLength(1);
      169 |       done();
      170 |     });
      171 |     mountPage();

      at src/pages/Overview/__tests__/OverviewPage.test.tsx:168:37

  ● Overview page › filters namespaces info name match

    Error
      [object Object] thrown

  ● Overview page › filters namespaces info name no match

    expect(received).toHaveLength(length)

    Expected value to have length:
      2
    Received:
      {Symbol(enzyme.__unrendered__): null, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): {Symbol(enzyme.__unrendered__): <Provider store={{"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}><BrowserRouter><OverviewPage /></BrowserRouter></Provider>, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): [Circular], Symbol(enzyme.__node__): {"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 3478, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 0, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}, Symbol(enzyme.__nodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": [Object], "_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "props": [Object], "refs": [Object], "state": null, "store": [Object], "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter … />, "store": [Object]}, "ref": null, "rendered": {"instance": [BrowserRouter], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": [Object]}}}}, Symbol(enzyme.__node__): undefined, Symbol(enzyme.__nodes__): [], Symbol(enzyme.__rootNodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 3478, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 0, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": {"componentDidUpdate": [Object], "getDerivedStateFromProps": true, "getSnapshotBeforeUpdate": true, "setState": [Object]}}}}}
    received.length:
      0

      217 |     ]).then(() => {
      218 |       mounted!.update();
    > 219 |       expect(mounted!.find('Card')).toHaveLength(2);
      220 |       done();
      221 |     });
      222 |     mountPage();

      at src/pages/Overview/__tests__/OverviewPage.test.tsx:219:37

  ● Overview page › filters namespaces info name and health match

    expect(received).toHaveLength(length)

    Expected value to have length:
      0
    Received:
      {Symbol(enzyme.__unrendered__): null, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): {Symbol(enzyme.__unrendered__): <Provider store={{"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}><BrowserRouter><OverviewPage /></BrowserRouter></Provider>, Symbol(enzyme.__renderer__): {"batchedUpdates": [Function batchedUpdates], "getNode": [Function getNode], "render": [Function render], "simulateError": [Function simulateError], "simulateEvent": [Function simulateEvent], "unmount": [Function unmount]}, Symbol(enzyme.__root__): [Circular], Symbol(enzyme.__node__): {"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 3942, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 1073741823, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}, Symbol(enzyme.__nodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": [Object], "_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "props": [Object], "refs": [Object], "state": null, "store": [Object], "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter … />, "store": [Object]}, "ref": null, "rendered": {"instance": [BrowserRouter], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": [Object]}}}}, Symbol(enzyme.__node__): {"instance": null, "key": undefined, "nodeType": "function", "props": {"accented": true, "aggregated": true, "aggregatedMini": false, "cardRef": null, "children": [<CardTitle className="">abc</CardTitle>, <CardBody className=""><OverviewStatuses … /><div … /></CardBody>], "className": "", "matchHeight": true}, "ref": null, "rendered": {"instance": <div class="card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"><h2 class="card-pf-title">abc</h2><div class="card-pf-body"><a … /><p … /><div … /></div></div>, "key": undefined, "nodeType": "host", "props": {"children": [<CardTitle … />, <CardBody … />], "className": "card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"}, "ref": null, "rendered": [{"instance": null, "key": undefined, "nodeType": "function", "props": [Object], "ref": null, "rendered": [Object], "type": [Function CardTitle]}, {"instance": null, "key": undefined, "nodeType": "function", "props": [Object], "ref": null, "rendered": [Object], "type": [Function CardBody]}], "type": "div"}, "type": [Function Card]}, Symbol(enzyme.__nodes__): [{"instance": null, "key": undefined, "nodeType": "function", "props": {"accented": true, "aggregated": true, "aggregatedMini": false, "cardRef": null, "children": [<CardTitle … />, <CardBody … />], "className": "", "matchHeight": true}, "ref": null, "rendered": {"instance": <div class="card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"><h2 … /><div … /></div>, "key": undefined, "nodeType": "host", "props": {"children": [Array], "className": "card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"}, "ref": null, "rendered": [[Object], [Object]], "type": "div"}, "type": [Function Card]}, {"instance": null, "key": undefined, "nodeType": "function", "props": {"accented": true, "aggregated": true, "aggregatedMini": false, "cardRef": null, "children": [<CardTitle … />, <CardBody … />], "className": "", "matchHeight": true}, "ref": null, "rendered": {"instance": <div class="card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"><h2 … /><div … /></div>, "key": undefined, "nodeType": "host", "props": {"children": [Array], "className": "card-pf card-pf-accented card-pf-aggregate-status card-pf-match-height"}, "ref": null, "rendered": [[Object], [Object]], "type": "div"}, "type": [Function Card]}], Symbol(enzyme.__rootNodes__): [{"instance": {"__reactInternalMemoizedMergedChildContext": {"store": [Object], "storeSubscription": null}, "_reactInternalFiber": {"_debugID": 3942, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": [FiberNode], "child": [FiberNode], "childExpirationTime": 1073741823, "effectTag": 0, "elementType": [Function Provider], "expirationTime": 0, "firstContextDependency": null, "firstEffect": [FiberNode], "index": 0, "key": null, "lastEffect": [FiberNode], "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0, "type": [Function Provider], "updateQueue": null}, "_reactInternalInstance": {}, "context": {}, "props": {"children": <BrowserRouter … />, "store": [Object]}, "refs": {}, "state": null, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}, "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}}, "key": undefined, "nodeType": "class", "props": {"children": <BrowserRouter><OverviewPage … /></BrowserRouter>, "store": {"dispatch": [Function anonymous], "getState": [Function getState], "replaceReducer": [Function replaceReducer], "subscribe": [Function subscribe], Symbol(observable): [Function observable]}}, "ref": null, "rendered": {"instance": {"_reactInternalFiber": [FiberNode], "_reactInternalInstance": [Object], "context": [Object], "history": [Object], "props": [Object], "refs": [Object], "state": null, "updater": [Object]}, "key": undefined, "nodeType": "class", "props": {"children": <OverviewPage … />}, "ref": null, "rendered": {"instance": [Router], "key": undefined, "nodeType": "class", "props": [Object], "ref": null, "rendered": [Object], "type": [Function Router]}, "type": [Function BrowserRouter]}, "type": [Function Provider]}], Symbol(enzyme.__options__): {"adapter": {"options": {"enableComponentDidUpdateOnSetState": true, "lifecycles": {"componentDidUpdate": [Object], "getDerivedStateFromProps": true, "getSnapshotBeforeUpdate": true, "setState": [Object]}}}}}
    received.length:
      2

      232 |     mockNamespaces(['abc', 'bce', 'ced']).then(() => {
      233 |       mounted!.update();
    > 234 |       expect(mounted!.find('Card')).toHaveLength(0);
      235 |       done();
      236 |     });
      237 |     mountPage();

      at src/pages/Overview/__tests__/OverviewPage.test.tsx:234:37

  ● Overview page › filters namespaces info name and health no match

    Error
      [object Object] thrown


Test Suites: 1 failed, 55 passed, 56 total
Tests:       7 failed, 244 passed, 251 total
Snapshots:   31 passed, 31 total
Time:        10.48s
Ran all test suites matching /__tests__/i.
```

**Comment by jotak** [comment]
@mtho11 That's weird... What I did to test is remove nodes_modules, run yarn install / yarn test -u / yarn start
Did you do something different?

**Comment by mtho11** [comment]
@jotak weird. I went to a different machine and see the same as you now. Some weird caching thing? I always remove the `node_modules` so strange. I have seen this behaviour before and it scares me a bit.

**Comment by mtho11** [comment]
@mattmahoneyrh can you verify that the library changes are good?

**Comment by josejulio** [comment]
I tested and i see no errors from the tests or the cytoscape graph

**Comment by mtho11** [comment]
Thanks @josejulio. Enjoy Maria, welcome back!

**Comment by josejulio** [comment]
> Thanks @josejulio. Enjoy Maria, welcome back!

Thank you!

**Comment by jotak** [comment]
@josejulio so you tested with an actual mesh and the graph was showing up? Without any cytoscape error?

**Comment by mtho11** [comment]
We are all good with this so merging. And yes, I did remove the Cytoscape libs. We can create a separte jira for that.

**Pull request merged**
