### PR TITLE
Istio Registry changes

### PR DESCRIPTION
**Pull request by lucasponce**
Required for https://github.com/kiali/kiali/pull/4479

### CODE REVIEW

**Comment by hhovsepy** [comment]
Create this ServiceEntry with *.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: 'all.googleapis.com'
spec:
  hosts:
    - "*.googleapis.com"
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
    - number: 443
      name: http-port-for-tls-origination
      protocol: HTTP
  resolution: NONE

```
Listing SE works.
Screenshot from 2021-11-18 19-18-08
But try to click on SE with *
Screenshot from 2021-11-18 19-18-31

**Comment by lucasponce** [comment]
> But try to click on SE with *

@hhovsepy thanks for the test ! I've updated the regex used to map the breadcrumb, let me know if it works.

**Comment by hhovsepy** [comment]
> > But try to click on SE with *
> 
> @hhovsepy thanks for the test ! I've updated the regex used to map the breadcrumb, let me know if it works.

yeah thank you @lucasponce  it works now

**Comment by lucasponce** [comment]
Note, this PR should contain a simple filter by service type, it's minor it would add a lot of help there.

**Comment by lucasponce** [comment]
> Note, this PR should contain a simple filter by service type, it's minor it would add a lot of help there.

Updated.

**Review by hhovsepy — APPROVED** [review]
Looks good, did regression testing of UI.

**Comment by lucasponce** [comment]
Updated, @leandroberetta found a bug in the Service Details page when the service has a ServiceEntry attached

**Pull request merged**
