### PR TITLE
KIALI-1587 Jaeger link tries to open popup

### PR DESCRIPTION
**Pull request by aljesusg**
Fix the popup in traces tab in the service details

JIRA [KIALI-1587](https://issues.jboss.org/browse/KIALI-1587)

cc @hhovsepy please review.

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-ui-pr-e2e-test [#311](https://paste.fedoraproject.org/paste/0TSFAT-mM548ej8nARYPhQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-ui-pr-e2e-test [#312](https://paste.fedoraproject.org/paste/opoC94VNuyLcr1CMVLESWQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-ui-pr-e2e-test [#313](https://paste.fedoraproject.org/paste/VEqEfKxCKAOwAV~vLJNS6A)
 :red_circle: PRT Failed, Please Contact QE

**Comment by aljesusg** [comment]
Thanks @hhovsepy @jotak

**Pull request merged**
