### PR TITLE
PF3->PF4 move wizard framework

### PR DESCRIPTION
**Pull request by lucasponce**
Only the PF3 Wizard are migrated to PF4 Modal.
Content of the wizard is not yet migrated.
https://github.com/kiali/kiali/issues/1595

image

Note, the goal of this PR is only to adjust the modal, and buttons.
Content of each Wizard (Use case) is handled in a different location and we will send different PRs for them.

### CODE REVIEW

**Comment by lucasponce** [comment]
Added "do not merge", I see some things to change after a self-review.

**Comment by aljesusg** [comment]
There is a bug here the first time you open the weight wizard, it seems that is not releated with the changes @lucasponce but this not happen in master Should  we open an issue about in kiali or PF?

Screenshot from 2019-09-09 10-44-22


# Demo

bug

**Comment by lucasponce** [comment]
Ok, I am aware of that issue. I'm still preparing a PR with the content.
When ready, I will close this one and put the commits in the next one, to merge all together.

**Comment by hhovsepy** [comment]
During the load:
Screenshot from 2019-09-09 11-35-10

**Comment by lucasponce** [comment]
@hhovsepy nice one !
Yeah, we put this on hold, I will send a PR with these changes + Advanced options, to fix that issue with the PF3 switches.

**Comment by lucasponce** [comment]
Closing in favor of #1407

**Pull request closed without merging**
