### PR TITLE
[v1.36] Fix a bug where when view only mode is set, workload actions dropdown is not disabled #2219

### PR DESCRIPTION
**Pull request by leandroberetta**
Backport of #2219.

### CODE REVIEW

**Comment by lucasponce** [comment]
This is the backend PR https://github.com/kiali/kiali/pull/4308

**Review by prachiyadav — COMMENTED** [review]
Seems it is not backported yet

Screenshot from 2021-09-02 23-33-40


Screenshot from 2021-09-02 23-33-09


Screenshot from 2021-09-02 23-32-49

**Review by prachiyadav — CHANGES_REQUESTED** [review]
this PR is failing at my end.

**Review by prachiyadav — APPROVED** [review]
Screenshot from 2021-09-03 20-47-27


Screenshot from 2021-09-03 20-46-48

**Comment by prachiyadav** [comment]
Test case >> SWSQE 1978

**Pull request merged**
