### PR TITLE
KIALI-2332 Add MTLS percentage to edge side panel

### PR DESCRIPTION
**Pull request by jshaughn**
mTLS is indicated in side panel on selection, regardless of whether 
Full time period:
image

Percentage of the time period:
image

REQUIRES SERVER PR https://github.com/kiali/kiali/pull/827

### CODE REVIEW

**Comment by abonas** [comment]
Can you explain what does "50% of graph period" means? I don't understand this sentence. thanks

**Comment by jshaughn** [comment]
> Can you explain what does "50% of graph period" means? I don't understand this sentence. thanks

@abonas , This is an attempt to indicate to the user that mTLS was active for only a portion of the data points gathered for the graph.  So, if the graph period represents T1..T2, this is saying that 50% of the datapoints had mTLS enabled, and 50% did not.  Does that make sense?

**Comment by abonas** [comment]
> @abonas , This is an attempt to indicate to the user that mTLS was active for only a portion of the data points gathered for the graph. So, if the graph period represents T1..T2, this is saying that 50% of the datapoints had mTLS enabled, and 50% did not. Does that make sense?

it does make sense, but the phrasing is not clear.

**Comment by jshaughn** [comment]
@abonas How about one of these:

- "mTLS Enabled [50% of the time]"
- "mTLS Enabled [50% of time period]
- "mTLS Enabled [50% of time range]
- "mTLS Enabled [50% of request traffic]
- "mTLS Enabled [partial: 50% of request traffic]

Something else?

**Comment by abonas** [comment]
> * "mTLS Enabled [50% of the time]"
> * "mTLS Enabled [50% of time period]
> * "mTLS Enabled [50% of time range]
> * "mTLS Enabled [50% of request traffic]
> * "mTLS Enabled [partial: 50% of request traffic]

50% of request traffic is not the same like 50% of time period.
which one is more accurate?

**Comment by jshaughn** [comment]
> 50% of request traffic is not the same like 50% of time period. which one is more accurate?

Good point.  So actually, it's the percent of request traffic.  So the better choices would be:
- "mTLS Enabled [50% of request traffic]
- "mTLS Enabled [partial: 50% of request traffic]

**Comment by xeviknal** [comment]
> * "mTLS Enabled [50% of request traffic]

IMO:
I guess that using partial is redundant when % of the traffic doesn't use mTLS. In addition, we use the word `partial` for the mTLS icons on the masthead. Perhaps, it might lead to misunderstandings.

Good feature @jshaughn ! :dancing_men:

**Comment by jshaughn** [comment]
@abonas Here is the updated messaging:
image

**Comment by abonas** [comment]
@jshaughn it's much better!
One thing I'm not sure about is "request traffic". I mean there is request, and response as well, and both are mtls? or only requests? perhaps only saying "traffic" here is suffice?

**Comment by jshaughn** [comment]
@abonas I made the change.

**Comment by abonas** [comment]
> @abonas I made the change.

Is there an updated screenshot? I might have missed that

**Comment by jshaughn** [comment]
@abonas , here you go:

image

**Comment by pilhuhn** [comment]
Is it really traffic? Or time?  If I create a service at noon without TLS, have 100 req/s and then at 1pm enable mTLS and have 20 req/s and then look at it at 2pm, what would be the outcome?
For the scenario when mTLS is not enabled the whole time I'd expect that we show the fraction of time it was (not) enabled. But maybe I misunderstand this.

**Comment by jshaughn** [comment]
> Is it really traffic? Or time?

@pilhuhn , It's requests as the information is based on the request count rate grouped by mTLS vs not-mTLS, for the time period.  If you want to see something time-based a better representation would likely be a sparkline, or something RLE-ish (like the old avail), and it would require actually querying the datapoints so that we could it ordered by time.

**Comment by pilhuhn** [comment]
Hm. I honestly have no idea what users want here (and/or if that really makes sense in such a way and shouldn't be perhaps encoded in a table with timestamp and state change).

*My* expectation is/was to see something like "2h mTLS out of 7", which could be represented as a bar with different colors. Again: I may be completely be wrong and what you have is what folks want to see.

**Comment by jshaughn** [comment]
@pilhuhn I totally agree.  In fact @mwringe and I already pretty much had this discussion.  I'm flipping a penny here and added what could be done reasonable easily in order to give some visibility if in fact they are interested enough to select the edge.  Going any further would be more work, and I think should be motivated by a real-world RFE.

**Pull request merged**
