### PR TITLE
KIALI-2896 Used fixed height for graph find modal

### PR DESCRIPTION
**Pull request by jshaughn**
- enable scroll as needed

kiali-2896

### CODE REVIEW

**Comment by mtho11** [comment]
@jshaughn can you add a before video to show what it looked like before the change?

**Comment by mtho11** [comment]
Do we need to test this with small screen resolution?

**Comment by jshaughn** [comment]
@mtho11 The small screen stuff is unchanged from the previous PR I did for that stuff.  I checked this PR on a small screen as well and the modal and out scrolls both worked as expected.

Here is the before shot showing the varying height issue:

kiali-2896-2

**Comment by abonas** [comment]
why is this PR closed?

**Comment by jshaughn** [comment]
@abonas I have no idea how I managed to close this, re-opening...

**Comment by israel-hdez** [comment]
@jshaughn Most likely, you hit the "Close and comment" button without noticing ;)

**Comment by jshaughn** [comment]
@israel-hdez Yes.  that button is dangerously close to "Comment".  Since you are here, please approve this PR :)

**Pull request merged**
