### PR TITLE
Metrics: fix peer namespace segregation

### PR DESCRIPTION
**Pull request by jotak**
Add *_workload_namespace as an active label by default

Fixes https://github.com/kiali/kiali/issues/3650

Backend PR: https://github.com/kiali/kiali/pull/3651

### CODE REVIEW

**Comment by jotak** [comment]
Capture d’écran de 2021-01-29 09-50-10
Capture d’écran de 2021-01-29 09-50-18

**Comment by jotak** [comment]
For testing, here's a reproducer:

- Install standard mesh-arena

```bash
kubectl label namespace default istio-injection=enabled
kubectl apply -f <(curl -L https://raw.githubusercontent.com/jotak/demo-mesh-arena/zizou/quickstart-naked.yml) -n default
```

- Create test namespace

```bash
kubectl create namespace test
kubectl label namespace test istio-injection=enabled
```

- Grab this yaml and deploy it:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai
    version: visitors
  name: ai-visitors
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
      version: visitors
  template:
    metadata:
      labels:
        app: ai
        version: visitors
    spec:
      containers:
      - env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui.default
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball.default
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadiumsvc.default
        - name: INTERACTIVE_MODE
          value: "0"
        - name: PLAYER_TEAM
          value: visitors
        - name: PLAYER_COLOR
          value: '#F0AB00'
        - name: PLAYER_NAMES
          value: Any
        - name: JAEGER_SERVICE_NAME
          value: ai.test
        - name: JAEGER_SAMPLER_TYPE
          value: ratelimiting
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc/api/traces
        image: quay.io/jotak/mesharena-ai-openj9:1.3.1
        imagePullPolicy: IfNotPresent
        name: ai-openj9
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
```

Now you can check the inbound metrics of service/app/workload 'ball', for example.

**Review by hhovsepy — APPROVED** [review]
Verified:
Screenshot from 2021-01-29 11-52-46
Screenshot from 2021-01-29 11-53-02

**Review by jshaughn — APPROVED** [review]
@jotak Tested and looks good.  Would it be hard to disable Remote Namespace (or any Metric Setting) if there were only one possible selection?  This could potentially simplify the legend and better allow it to use multiple columns in the case that the discriminator does not offer any additional aggregation.  Certainly not a blocker.

**Review by aljesusg — APPROVED** [review]
LGFM

**Comment by jotak** [comment]
> @jotak Tested and looks good. Would it be hard to disable Remote Namespace (or any Metric Setting) if there were only one possible selection? This could potentially simplify the legend and better allow it to use multiple columns in the case that the discriminator does not offer any additional aggregation. Certainly not a blocker.

Yes, we can do that, it's not too difficult. However, it also means that when the user intentionally clicks on a label to turn on aggregation, if there's a single value, it's not going to be shown in the legend either.
But since he can see the value displayed in the settings dropdown - that dropdown being opened since a label was just clicked on - I would say it's ok, the label's value is clearly visible there.
I've played a little bit with this, and it look good. I'll open a separate PR as it's a different thing from here (though driven by this).

**Pull request merged**
