### PR TITLE
KIALI-1694 fix url param renamed to 'duration'

### PR DESCRIPTION
**Pull request by jotak**
Taking opportunity to unify URL params management between Metrics page (for which a generic HistoryManager was created) and ListPages.

Add missing URL Params as enums

JIRA: https://issues.jboss.org/browse/KIALI-1694

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#166](https://paste.fedoraproject.org/paste/-9fE~n-I68SZWGX~oZhMxw)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1493]](https://paste.fedoraproject.org/paste/y8wwU5ru2s-FPK2cXGtV1A)
  * :heavy_check_mark: Istio-Upstream [#[356]](https://paste.fedoraproject.org/paste/4kxCndsF~1cqHcXFSGOdGA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1537, 1538]](https://paste.fedoraproject.org/paste/JaAMCrlpiUySiI33Ve-EGQ)
  * :heavy_check_mark: install-bookinfo [#[864]](https://paste.fedoraproject.org/paste/PJvveQorJ7QPpHdOeyVzzw)
  * :heavy_check_mark: Kiali-on-Openshift [#[864]](https://paste.fedoraproject.org/paste/04wmpsOT4EKZ6e4LFtnzEw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[296]](https://paste.fedoraproject.org/paste/l7Cb6xjRq1GUdP5JWHVRjA)


KIALI_NAME=kialiuipr728-istio-system

**Comment by hhovsepy** [comment]
I see double requests, one with new interval, second with old interval.
Clean network requests.
Change interval.
Clean network again.
Change interval.
Check all requests sent, they are double.

**Comment by jotak** [comment]
@hhovsepy that's correct, but if you have no objection I prefer to create another ticket/PR for that. These duplicate requests are not introduced here, they were already present before, I will create an optimization task.
It will be easier for reviewers to review separately, I think.

**Comment by hhovsepy** [comment]
@jotak I am fine with that

**Pull request merged**
