### PR TITLE
Update Patternfly4

### PR DESCRIPTION
**Pull request by cfcosta**
Did this update as a tentative fix for https://github.com/kiali/kiali/issues/1928.

Didn't help that problem, but everything is working fine (I did a quick check in all pages, could not find anything new except for https://github.com/kiali/kiali/issues/2018 which also happens on master).

This can be merged after the sprint finishes if deemed too dangerous to merge before release.

### CODE REVIEW

**Comment by mtho11** [comment]
This probably needs to wait until the beginning of the sprint since it is many library changes.

**Comment by mtho11** [comment]
Also some failing CI tests.

**Comment by pbajjuri20** [comment]
According to PR, I am unable to replicate.

**Comment by mtho11** [comment]
Adding DNM until the next sprint.

**Comment by pbajjuri20** [comment]
I have tested each and every icon, It is working perfectly. 
Tested and passed on #Kiali-ui 1.11.0 (82004bdb5fcd02596c14abae99ec2676fed1e77a),
Kiali v1.11.0-SNAPSHOT (7a507164c4580a163a559bc508f3f741c47733f9)

**Comment by mtho11** [comment]
Since there were conflicts we should probably let @pbajjuri20 re-test to make sure.

**Comment by pbajjuri20** [comment]
I did a re-test on this PR. Smoke test passed.

**Pull request merged**
