### PR TITLE
Upgrade Cytoscape to the latest version

### PR DESCRIPTION
**Pull request by cfcosta**
Closes https://github.com/kiali/kiali/issues/1826.

This PR should fix the problems we have with big meshes because of cytoscape. Did some testing with small/medium/large graphs, everything seems to be ok.

QE can test it by following what Guilherme did on his issue.

### CODE REVIEW

**Comment by aljesusg** [comment]
Please test tippy components we had problems with the last update of PF4 here because PF4 use tippy 5 and we have tippy 3, not supported and can be affected in cytoscape popper

**Comment by cfcosta** [comment]
@aljesusg sure! Can you give me some pointers on what to test/verify?

**Comment by jshaughn** [comment]
@cfcosta I'm not sure how much Tippy is used in the graph proper but check things like hover, badging on labels, label placement, single-click, double-click, right click menus, and although tangential, the graph tour.

> This PR should fix the problems we have with big meshes 

That's sort of unproven but we're hopeful that the past issues were releated to hash issues that may have been resolved.  Either way this update can close the issue and new issues can be created if/when a user encounters a problem.

**Comment by cfcosta** [comment]
>@cfcosta I'm not sure how much Tippy is used in the graph proper but check
>things like hover, badging on labels, label placement, single-click,
>double-click, right click menus, and although tangential, the graph tour.

Ok, will take a look. I remember the right menus and hovers being ok, but let me verify for this.

>That's sort of unproven but we're hopeful that the past issues were releated to
>hash issues that may have been resolved. Either way this update can close the
>issue and new issues can be created if/when a user encounters a problem

Yeah, there's always the chance what I tested did not trigger an edge case for a
different mesh, but at least I could not find any problems.

**Comment by cfcosta** [comment]
@jshaughn just verified it here. Hovers, badging, label placement, single click, double click, right click menus, graph tour are all exactly the same as before.

Just as a reference, this is before:
image
And this is after:
image

**Comment by jshaughn** [comment]
@pbajjuri20 Make sure to also try the different graph layouts.  Also, make sure to try graph hide.

**Comment by pbajjuri20** [comment]
I have tested on a larger mesh, the issue is fixed perfectly. 

LGTM! 

mesh

**Comment by cfcosta** [comment]
Thanks @pbajjuri20!

**Pull request merged**
