### PR TITLE
TEST PR

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-ui-pr-e2e-test [#1](https://paste.fedoraproject.org/paste/Q3CMptNoRSidnV5LM~LSZw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-ui-pr-e2e-test [#4](https://paste.fedoraproject.org/paste/zmP-f3XXKEOU6zP6p9IDjw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-ui-pr-e2e-test [#5](https://paste.fedoraproject.org/paste/n86d9JRujDsVwCmH~USeHA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[746]](https://paste.fedoraproject.org/paste/6NbskiIm4m9N1p1-uPeb-A)

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-ui-pr-e2e-test [#6](https://paste.fedoraproject.org/paste/LaEQK7P0DvwE9YbyGR9-lQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-ui-pr-UI-test [#330](https://paste.fedoraproject.org/paste/Lxi3OFiXT-oP6oiXpMq5Vw)
  * :question: python-ui-tests-parallel [#[198]](https://paste.fedoraproject.org/paste/m2nR8QC2Q3Kioop5roAxGg)

**Comment by hhovsepy** [comment]
kiliqeci

**Pull request closed without merging**
