### PR TITLE
[WIP] Add EnvoyFilter

### PR DESCRIPTION
**Pull request by Buri**
**Describe the change**
Adds EnvoyFilter to Istio Config screen

**Issue reference**
https://github.com/kiali/kiali/issues/995

**Backwards compatible?**
[ ] Is your pull-request introducing changes in behaviour?

New option in config screen

**Screenshot**

Add a screenshot of the UI after your changes.

**Documentation**
N/A

### CODE REVIEW

**Comment by lucasponce** [comment]
@Buri thanks for the draft !
We will review it when you tell us is ready.

I guess this one will need support from the backend, right ?
I'm not sure if the EnvoyFilter object is listed in the kiali service yet.

**Comment by Buri** [comment]
Yes, this needs BE. I'm currently trying to get Go environment working, since I've never used that before

**Comment by jotak** [comment]
@Buri if you need help about that don't hesitate to ask on chat (irc freenode / #kiali )

**Comment by israel-hdez** [comment]
Hi, @Buri. It has been almost a year. If you don't have available time to finish this, I'm wondering if you prefer to close this PR and re-open if you mange to have the time to work on this.

**Pull request closed without merging**
