### PR TITLE
ServiceDetailsPage: minor fixes

### PR DESCRIPTION
**Pull request by lucasponce**
Closes kiali/kiali#1590

@aljesusg I think ServiceDetailsPage is in Pf4, I've found a couple of problems that are fixed with this PR.

### CODE REVIEW

**Comment by hhovsepy** [comment]
Workload name link is transferred to the next line, even though it is not so big:
Screenshot from 2019-10-23 08-53-39

**Comment by lucasponce** [comment]
Yeah, also I noticed the snapshot test needs an update, too.

**Comment by lucasponce** [comment]
@hhovsepy ok, I moved the "h5" to a "p" element in the workload title (so it should have same effect as previous "a" element).

Also updated tests.

**Comment by hhovsepy** [comment]
Go to Service Details Overview page.
Switch to Traffic tab.
Refresh the browser page.
Switch to Overview tab.
The values are empty.
Screenshot from 2019-10-23 15-01-49

**Comment by lucasponce** [comment]
@hhovsepy ok, it's missing a doRefresh() on change tab when we move from a different tab to overview back.

Thanks !

**Comment by lucasponce** [comment]
@hhovsepy hope now everything is fine, let me know !

**Pull request merged**
