### PR TITLE
Implement mini-graph on detail pages

### PR DESCRIPTION
**Pull request by israel-hdez**
Initial implementation of mini-graph on detail pages.

miniGraph

Related to kiali/kiali#1960

### CODE REVIEW

**Comment by israel-hdez** [comment]
This PR is still missing the following [UXD suggestions](https://github.com/kiali/kiali-design/issues/161#issuecomment-577325123):
* the graph shouldn't have any actions, other than pan enabled
* add a View graph link on the card title

It also needs the following technical improvements:
* mini-graph shouldn't manipulate the URL
* Check if data can be shared between mini-graph and traffic tab, because it's mostly the same data.

But I would like to deal with these points in a separate PRs because this one is already a little big. So, I'm promoting this PR because I think it's in good shape for reviews.

**Comment by israel-hdez** [comment]
@hhovsepy That's part of what I would like to fix in a follow-up PR (the graph shouldn't respond to actions other than pan & zoom)

**Comment by pbajjuri20** [comment]
Tested and Passed on Kiali UI 1.15.0 (5a4656e94732899943e314823d04ed3376246578)

**Comment by lucasponce** [comment]
@israel-hdez sorry, I was in PTO for a couple of days, I'm going to fetch and review this one.
Please, could you rebase conflicts first ?

**Comment by lucasponce** [comment]
> But I would like to deal with these points in a separate PRs because this one is already a little big (and also, because this slipped to a new sprint which gives enough time to address any emerging issue). So, I'm promoting this PR because I think it's in good shape for reviews.

Same comments of @hhovsepy.

I'm find to merge to consolidate the work and progress in comment in a follow-up review (if @hhovsepy is agree and there is no major regression with existing logic).

Also, we need to rebase as there are conflicts.

**Comment by israel-hdez** [comment]
Rebased. Also, since I needed to push the rebased revision, I fixed @jshaughn comments.
I'll merge soon.

**Comment by israel-hdez** [comment]
@lucasponce Do you have any additional comment? If not, I'll go ahead and merge.

**Pull request merged**
