### PR TITLE
KIALI-1427 UXD changes to traffic animation

### PR DESCRIPTION
**Pull request by josejulio**
** Describe the change **

Implement the UXD suggestions for the traffic animation

https://github.com/kiali/kiali-design/blob/0c55e9373fc5b67926b8481b407ce97ccd07a9d7/service-graph/design.md#traffic-animation-options

~~This code is not ready, but was used to create the following screenshots~~

As per feedback, we are going for Option 1 and 4, here is the updated gif with the legend

peek 2018-09-13 11-17

** Screenshot **

Option 1 and 4

option_1_4

Option 2

option_2

Option 3 and 5

option_3_5

### CODE REVIEW

**Comment by josejulio** [comment]
@cshinn which one do you think is better?
Are there any other changes you would like to see?

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#11](https://paste.fedoraproject.org/paste/yN-rNke~TL8QraNB~Q1IBA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1160]](https://paste.fedoraproject.org/paste/isRBFcFVpKqOWAYhAkKe2A)
  * :heavy_check_mark: install-bookinfo [#[581]](https://paste.fedoraproject.org/paste/R3zVLMpIScPjqt7PobPGBg)
  * :red_circle: Kiali-on-Openshift [#[512]](https://paste.fedoraproject.org/paste/2y8NfeZp0S5EmRzCQDmvhA)

**Comment by jmazzitelli** [comment]
> I quite like the first one as well, though I wonder if the failed ones are noticeable enough

maybe do option 1 but have the red circle be a red diamond (like in option 3/5 but have it red)

**Comment by josejulio** [comment]
> maybe do option 1 but have the red circle be a red diamond (like in option 3/5 but have it red)
> Oh wait, I noticed option 1 has the red diamond - but its interspersed with the red circle. I get why its doing that (the amount of diamonds compared to circles represents the error rate percentage) but maybe that is confusing? If it warrants red, maybe always show the diamonds regardless of actual rate?

Circles are successful requests (Option 1, the color depends on the color of the edge), Diamonds (always red) are error requests.

Edge from product page to reviews have a 50% chance of errors (percentErr = 50), that's why we see successful and error requests.

- `rate` determines how often to put a TrafficPoint in the edge
- `responseTime` determines how fast the TrafficPoint should travel from the start to the end of the edge
- `percentErr` determine if the next TrafficPoint is a ball or a diamond (error or not)

I personally think that using the edge color is cool but might be confusing

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#18](https://paste.fedoraproject.org/paste/mQN9JNC0GUigUGspmejFMQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1183]](https://paste.fedoraproject.org/paste/TaEa7QNOZ1if7LUO0SkqOQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[533]](https://paste.fedoraproject.org/paste/Vp2gxHKSFU75qbwc3FufXA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[949]](https://paste.fedoraproject.org/paste/6THoIxb4v4I9TMeQe0yewA)
  * :red_circle: run-kiali-e2e-tests [#[34]](https://paste.fedoraproject.org/paste/vKYz29LA9-aPWr-voBot-Q)

**Comment by israel-hdez** [comment]
> I personally think that using the edge color is cool but might be confusing

Yes, that may be true.
If we don't go with option 1 for this reason, I'd vote for the last animation (option 3&5?).

**Comment by josejulio** [comment]
I actually like option 2  (success for second animation)  and 4 (error for first animation)

**Comment by theute** [comment]
I haven't thought hard about it but I like option 1, the color would still help even if the graph gets very busy

**Comment by josejulio** [comment]
Updated, attached a gif of the results

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#35](https://paste.fedoraproject.org/paste/zM84aHxpw1C8CctXsFNThA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1225]](https://paste.fedoraproject.org/paste/dXwnwE1tRm2Elrl4BKjBtg)
  * :heavy_check_mark: Kiali-on-Openshift [#[573]](https://paste.fedoraproject.org/paste/h2aBIcoav62RT7sS4nV8QA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1006]](https://paste.fedoraproject.org/paste/tRaQwwTYSx0zf7WJmf~jMA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[56]](https://paste.fedoraproject.org/paste/7dNcPVt5zRD4noKzWWhq7g)


KIALI_NAME=kialiuipr659-istio-system

**Pull request merged**
