### PR TITLE
[WIP]KIALI-170 Jaeger UI, search Traces

### PR DESCRIPTION
**Pull request by aljesusg**
jaeger

First iteration of integration of Jager UI

This need [SWSCORE-121](https://github.com/kiali/swscore/pull/121 )

You can search like Jaeger UI less custom date(To do). Sort is implemented too.

To Do

- [ ] Let custom Date( Now disabled)
- [ ] Trace View 
- [ ] Check Style CSS

cc @abonas @theute

### CODE REVIEW

**Comment by objectiser** [comment]
Highlevel comment - can you make the lefthand menu item "Traces" instead of "Jaeger". Thanks.

**Comment by theute** [comment]
The changlog looks huge, is that a fork ?

**Comment by aljesusg** [comment]
@theute  I was talking with @abonas about this...I agree with her that this will be difficult to maintain but I don't know another way right now, the code is not typescript and sintax is different in jaeger, I had to rewrite part of the code and change some functions, I tried to add jaeger-ui like Library (@jotak told me about this possibility) but I got the same errors.  I need to talk with @mtho11 to see alternatives.

Anyway this is a first iteration to have jaeger search in Kiali.

**Comment by theute** [comment]
Let's continue as research, but we shouldn't merge a fork.
If we need a "fork", we'll likely have a quite different UI designed by a specialized team.

As commented in the JIRA, for now we can just link to the Jaeger UI KIALI-242 and keep on researching options to integrate without forking.

Does it really need to be using Typescript for us to embed a React component ?

**Comment by abonas** [comment]
it looks great :cake: , but indeed all my and @theute concerns still stand, so lets explore a bit more alternatives before merging this.

**Comment by jotak** [comment]
If I understand correctly the problem is that jaeger-ui [1] is not published on npm, so we cannot use it as a dependency, is that correct?
We could consider
- Ask Jaeger team if they could publish jaeger-ui on npm
- Or pull jaeger-ui from github as part of our build process

**Comment by aljesusg** [comment]
@jotak I just solve that  
```json
"jaeger-ui": "git+https://git@github.com/jaegertracing/jaeger-ui.git",
```
Now I am learnign about babel to let insert the Jaeger code and avoid warnings.

After that I think that We won't have problems in add components, only we'll need to configure proxy

```json
 "proxy": {
    "/api": {
      "target": <JAEGER-QUERY> or <PROXY SWSCORE>,
      "logLevel": "silent",
      "secure": false,
      "changeOrigin": true,
      "ws": true,
      "xfwd": true
    }
}
```

Research time @abonas @theute

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
