### PR TITLE
Add Regex filter for Show/hide.

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Adds regular expression filtering for the workload show/hide filtering.

- [x] Regex filtering
- [x] Allow copy to clipboard of filtered log results
- [x] Fix alignment with an additional row of toolbar buttons

** Issue reference **
closes https://github.com/kiali/kiali/issues/2892

** Screenshot **
Kiali_Console

regex

### CODE REVIEW

**Comment by jshaughn** [comment]
@mtho11 Let's get this regex stuff in...

**Comment by mtho11** [comment]
Added regex validation for show/hide and also 'copy logs to clipboard':

Kiali_Console

**Comment by mtho11** [comment]
@jshaughn looks like this is ready to goto @pbajjuri20 now

**Comment by mtho11** [comment]
@pbajjuri20 testing can be done using regular expressions like: `178$` to only show lines ending in *178. Or `^2020` to get or hide lines starting with 2020*.

**Comment by pbajjuri20** [comment]
Tested and Passed on Kiali UI 1.21.0 (0416987f21c2e1dc802f9e6628843e43c7ed383f)

**Pull request merged**
