### PR TITLE
Istio preview under istio config view

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/4733

Grouped by namespace

Screenshot from 2022-02-15 11-00-17

### CODE REVIEW

**Comment by hhovsepy** [comment]
Just a note if PR is not ready yet: add "kind" and "apiVersion" into configs.
Facing page crash while trying to Preview Gateway:
Screenshot from 2022-02-16 14-18-22
Screenshot from 2022-02-16 14-27-07

**Comment by aljesusg** [comment]
You're right. I thought I added the changes https://github.com/kiali/kiali-ui/blob/646ab60ce9f1d70a46fca4b7c1e89847c92e68a5/src/components/IstioWizards/WizardActions.ts#L1301 let em fix it

**Comment by hhovsepy** [comment]
I still see the page crashing issue with Gateway Create/Preview.

**Comment by aljesusg** [comment]
Are you sure? Let me check but for me was working in my env

**Comment by aljesusg** [comment]
> I still see the page crashing issue with Gateway Create/Preview.

Fix it, there are so problems when an attribute is undefined, the yaml editor fail...I need to check if there are more attributes that can be undefined

**Comment by hhovsepy** [comment]
Not sure if this regression comes with this PR, but Create button is not working in Create Traffic Policies of Overview page.
Screenshot from 2022-02-21 16-16-04

**Review by hhovsepy — APPROVED** [review]
Now all mentioned issues work fine.

**Comment by lucasponce** [comment]
Sorry @aljesusg, I've found a minor regression.

To be consistent with the Overview and Services, when the user has no rights, it should let to create the config and preview them (but not create them; similar flow as used in the Services).

But in the Istio Config, it disables the menu and I think that should be modified:
image

I've just tested using the "view_only_mode: true".

**Review by lucasponce — CHANGES_REQUESTED** [review]
The menu in the Istio Config should have the same behavior as introduced under the Wizards for consistency.

**Comment by aljesusg** [comment]
> The menu in the Istio Config should have the same behavior as introduced under the Wizards for consistency.

Fixed, I forgot rebase that file with my old branch sorry

**Comment by aljesusg** [comment]
> The menu in the Istio Config should have the same behavior as introduced under the Wizards for consistency.

Fixed. I forgot to rebase that file from my old branch :(

**Review by lucasponce — APPROVED** [review]
The last commit has fixed the issues reported.
Please @skondkar this is ready for QE flow.
Thanks!

**Review by skondkar — APPROVED** [review]
LGTM.
Verified preview mode for Istio objects.

Screenshot from 2022-02-23 15-59-16

Screenshot from 2022-02-23 16-00-03

View only mode:

Screenshot from 2022-02-23 15-52-20

Also verified the preview feature on service details and overview page.

**Comment by skondkar** [comment]
Polarion testcase >> SWSQE-2542

**Pull request merged**
