### PR TITLE
Adds storybook for some components

### PR DESCRIPTION
**Pull request by josejulio**
- CytoscapeLayout
  - MetricOptions
  - Pf
  - ServiceFilter

peek 2018-04-03 00-14

> Storybook is a development environment for UI components. It allows you to browse a component library, view the different states of each component, and interactively develop and test components.
> Storybook runs outside of your app. This allows you to develop UI components in isolation, which can improve component reuse, testability, and development speed. You can build quickly without having to worry about application-specific dependencies.

storybook demo

https://github.com/storybooks/storybook

### CODE REVIEW

**Comment by josejulio** [comment]
Currently is failing travis, let me check.

**Comment by josejulio** [comment]
@mtho11 Travis was red because a new prop was added to cytoscapelayout, I had to update the storybook with these changes.
Is fixed now and ready to review

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by mtho11** [comment]
@josejulio needs rebasing...

**Comment by josejulio** [comment]
Yes, i think this need more than rebasing, will work on this and will let you know.

**Comment by josejulio** [comment]
@mtho11 Rebased, updated the code and travis is green now. Please review.

**Comment by aljesusg** [comment]
What do you think about publish this in github-pages (autodeploy with travis)?

**Comment by josejulio** [comment]
> What do you think about publish this in github-pages (autodeploy with travis)?

I don't see any use on publishing our component's storybook, but i'm not against that.
The intention of this PR is to allow developers to isolate the components and develop/test them, a follow up PR can be made to deploy the storybook to github-pages.

> Storybook is a development environment for UI components. It allows you to browse a component library, view the different states of each component, and interactively develop and test components.
Storybook runs outside of your app. This allows you to develop UI components in isolation, which can improve component reuse, testability, and development speed. You can build quickly without having to worry about application-specific dependencies.

**Pull request merged**
