### PR TITLE
Upgrade the 'kind-of' library for vulnerability. (Medium)

### PR DESCRIPTION
**Pull request by mtho11**
This is from Github security alerts. Note: this is a dev-dependency only so, low risk. Only for builds.

Alerts_·_kiali_kiali-ui

closes #https://github.com/kiali/kiali/issues/2604

### CODE REVIEW

**Comment by mtho11** [comment]
Obviously, this can wait until start of next sprint.

**Comment by israel-hdez** [comment]
I'm wondering if this is fixed by updating react-scripts (or whatever is our direct dependency that uses kind-of)... We tend to forget to update the resolutions stanza. I'd give a try to a react-scripts update first, and we also get benefit of newer build tools :)

If not possible, this anyway looks good.

**Comment by mtho11** [comment]
@israel-hdez can you retest now.

**Comment by mtho11** [comment]
@pbajjuri20 I'm merging this since it is only related to the dev environment:

```
yarn why kind-of                                                             
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "kind-of"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "kind-of@3.2.2"
info Has been hoisted to "kind-of"
info Reasons this module exists
   - Hoisted from "snyk#snyk-gradle-plugin#clone-deep#kind-of"
   - Hoisted from "react-scripts#@svgr#webpack#@svgr#plugin-svgo#merge-deep#kind-of"
   - Hoisted from "react-scripts#@svgr#webpack#@svgr#plugin-svgo#merge-deep#clone-deep#kind-of"
   - Hoisted from "react-scripts#webpack#micromatch#braces#fill-range#is-number#kind-of"
   - Hoisted from "react-scripts#webpack#micromatch#braces#snapdragon-node#snapdragon-util#kind-of"
   - Hoisted from "react-scripts#webpack#micromatch#snapdragon#base#cache-base#to-object-path#kind-of"
   - Hoisted from "react-scripts#webpack#micromatch#snapdragon#base#class-utils#static-extend#object-copy#kind-of"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "44KB"
info Disk size with transitive dependencies: "44KB"
info Number of shared dependencies: 1
=> Found "shallow-clone#kind-of@2.0.1"
info This module exists because "shallow-clone" depends on it.
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "44KB"
info Disk size with transitive dependencies: "44KB"
info Number of shared dependencies: 1
=> Found "is-descriptor#kind-of@6.0.2"
info This module exists because "is-descriptor" depends on it.
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "define-property#kind-of@5.1.0"
info Reasons this module exists
   - "define-property#is-descriptor" depends on it
   - Hoisted from "define-property#is-descriptor#kind-of"
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "24KB"
info Disk size with transitive dependencies: "24KB"
info Number of shared dependencies: 0
=> Found "is-accessor-descriptor#kind-of@6.0.2"
info This module exists because "is-descriptor#is-accessor-descriptor" depends on it.
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "is-data-descriptor#kind-of@6.0.2"
info This module exists because "is-descriptor#is-data-descriptor" depends on it.
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "define-property#is-accessor-descriptor#kind-of@3.2.2"
info This module exists because "define-property#is-descriptor#is-accessor-descriptor" depends on it.
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "44KB"
info Disk size with transitive dependencies: "44KB"
info Number of shared dependencies: 1
=> Found "define-property#is-data-descriptor#kind-of@3.2.2"
info This module exists because "define-property#is-descriptor#is-data-descriptor" depends on it.
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "44KB"
info Disk size with transitive dependencies: "44KB"
info Number of shared dependencies: 1
=> Found "sass-loader#kind-of@6.0.2"
info Reasons this module exists
   - "react-scripts#sass-loader#clone-deep" depends on it
   - Hoisted from "react-scripts#sass-loader#clone-deep#kind-of"
   - Hoisted from "react-scripts#sass-loader#clone-deep#shallow-clone#kind-of"
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "micromatch#kind-of@6.0.2"
info This module exists because "react-scripts#webpack#micromatch" depends on it.
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "plugin-error#kind-of@1.1.0"
info Reasons this module exists
   - "@patternfly#react-styles#fbjs-scripts#plugin-error#extend-shallow" depends on it
   - Hoisted from "@patternfly#react-styles#fbjs-scripts#plugin-error#extend-shallow#kind-of"
info Disk size without dependencies: "12KB"
info Disk size with unique dependencies: "12KB"
info Disk size with transitive dependencies: "12KB"
info Number of shared dependencies: 0
=> Found "global-prefix#kind-of@6.0.2"
info This module exists because "react-scripts#react-dev-utils#global-modules#global-prefix" depends on it.
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "nanomatch#kind-of@6.0.2"
info This module exists because "react-scripts#webpack#micromatch#nanomatch" depends on it.
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "has-values#kind-of@4.0.0"
info This module exists because "react-scripts#webpack#micromatch#snapdragon#base#cache-base#has-value#has-values" depends on it.
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "44KB"
info Disk size with transitive dependencies: "44KB"
info Number of shared dependencies: 1
✨  Done in 0.72s.
```

**Comment by pbajjuri20** [comment]
Tested and passed on Kiali UI 1.17.0 (e0d429b59f5a38222210e17e3dc817fd24a493be)

**Pull request merged**
