### PR TITLE
KIALI-3173 Update favicon with transparent background

### PR DESCRIPTION
**Pull request by jotak**
https://issues.jboss.org/browse/KIALI-3173

See also https://github.com/kiali/kiali-design/issues/141

### CODE REVIEW

**Comment by jotak** [comment]
I don't know why, I'm seeing the blank screen issue (fixed by https://github.com/kiali/kiali-ui/pull/1343 ) ... maybe just some cache issue on my side ?

**Comment by josejulio** [comment]
> I don't know why, I'm seeing the blank screen issue (fixed by #1343 ) ... maybe just some cache issue on my side ?

on build or on yarn start?

**Comment by jotak** [comment]
@josejulio  yarn build only

**Comment by jotak** [comment]
btw it seems favicon are persisted in cache much more than other usual files (I couldn't find how to clear it from cache in my firefox) so maybe we should add a fake query string such as ?v=2 to force a refresh ...

**Comment by cfcosta** [comment]
Nice! I tested it with an icognito window on Chrome and it works fine. Any chance we can also add there the App icons for iOS and Android? Seems like we can just put this logo on a white background and have that working even if people are not exactly using it very well.

**Comment by abonas** [comment]
> Nice! I tested it with an icognito window on Chrome and it works fine. Any chance we can also add there the App icons for iOS and Android? Seems like we can just put this logo on a white background and have that working even if people are not exactly using it very well.

Why is there a need in icons for IOS/Android?

**Comment by cfcosta** [comment]
@abonas you can use Kiali fine on iPad OS, now that it forces desktop-mode first on the websites. And the same for tools that generate contained website apps, like https://fluidapp.com/ or Chrome Apps.

**Comment by jotak** [comment]
@cfcosta I have nothing against supplying more icons but as a linux fundamentalist I don't have such device at home. Do you mind opening either a separate PR, or a PR to merge in mine?

Icons have been added w/ transparent background here: https://design.jboss.org/kiali/ under section "ICON - Color - For LIGHT Background" (or DARK).

**Comment by cfcosta** [comment]
@jotak my ipad broke last week :(
I can test to see if I can do it on my iPhone, let me see.

**Comment by jotak** [comment]
Can we merge it and we can create another JIRA for macos/android icons?

**Comment by jotak** [comment]
thanks!

**Pull request merged**
