### PR TITLE
KIALI-1371 Metrics: add units on Y-axis

### PR DESCRIPTION
**Pull request by jotak**
Use d3-format with SI notation

JIRA: https://issues.jboss.org/browse/KIALI-1371

Screenshot:
units-axis

### CODE REVIEW

**Comment by lucasponce** [comment]
@jotak I would add an space between number and unit (it seems grafana uses that convention, except for % units).

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#157](https://paste.fedoraproject.org/paste/5XDsms~svPS3kgf7Og1h5Q)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1477]](https://paste.fedoraproject.org/paste/mva65neREr3ZTiu8-KYd9A)
  * :heavy_check_mark: Istio-Upstream [#[342]](https://paste.fedoraproject.org/paste/T3~wubw984v9Jbnp~W-Xfg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1504, 1505]](https://paste.fedoraproject.org/paste/Sw3-4vqhnAZmQw3yrQQP0Q)
  * :heavy_check_mark: install-bookinfo [#[847]](https://paste.fedoraproject.org/paste/vw4UHt5FnBJnGmxhGhmRhw)
  * :heavy_check_mark: Kiali-on-Openshift [#[848]](https://paste.fedoraproject.org/paste/QGM6ua-TrXbmTN1bbMOrDg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[280]](https://paste.fedoraproject.org/paste/MZEI2SF5XbsVfG8azEvNLg)


KIALI_NAME=kialiuipr724-istio-system

**Comment by jotak** [comment]
@lucasponce I'm trying to tweak d3-format to get that, not so easy, see https://github.com/d3/d3-format : the "s" format (for SI) returns something like "3K" for 3000, so that if I insert a space after I would have "3K B" instead of desired "3 KB".
Still trying to tune it, I'll let you know.

**Comment by abonas** [comment]
in PF it seems that units are not displayed next to values:
https://www.patternfly.org/pattern-library/data-visualization/line-chart/
@cshinn @serenamarie125 any insights on this?

**Comment by jotak** [comment]
@abonas @cshinn @serenamarie125 I think that could be an interesting change to put directly in patternfly. I agree with Lucas that it's much more convenient to see the units on chart axis.

**Comment by jotak** [comment]
@lucasponce the best way I see for inserting space is to manipulate the string after it's built / via regexp or whatever) which is a bit of an overkill, I'm not sure it's worth it, what do you think?

**Comment by jotak** [comment]
@lucasponce done, there's now a space between numbers & unit.

@aljesusg or @xeviknal since Lucas isn't here can you follow up for the review?

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#164](https://paste.fedoraproject.org/paste/yBcnR2Pi4Dn2XfD-7JT1ow)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1491]](https://paste.fedoraproject.org/paste/NnGKzLF5JgLh4yXg4nN-kw)
  * :heavy_check_mark: Istio-Upstream [#[354]](https://paste.fedoraproject.org/paste/6ROiscsJsqDtJmupCPFDyA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1533, 1534]](https://paste.fedoraproject.org/paste/Qh~R9EFjJiKKSlhxXzINqg)
  * :heavy_check_mark: install-bookinfo [#[862]](https://paste.fedoraproject.org/paste/nueWx1PeO9ERZ-0yOLAm0Q)
  * :heavy_check_mark: Kiali-on-Openshift [#[862]](https://paste.fedoraproject.org/paste/aHjvTjV5AHYpQ41W7URhhA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[294]](https://paste.fedoraproject.org/paste/Og1iVZsZeAESSMf-6I4L3A)


KIALI_NAME=kialiuipr724-istio-system

**Comment by abonas** [comment]
> @abonas @cshinn @serenamarie125 I think that could be an interesting change to put directly in patternfly. I agree with Lucas that it's much more convenient to see the units on chart axis.

@jotak I don't have any objections, but I'm not the decision maker on PF :)

**Comment by cshinn** [comment]
Another option would be to put the units at the axis level rather than on each individual number. Something like this:
screen shot 2018-10-04 at 9 41 41 am

**Comment by abonas** [comment]
I really like @cshinn proposal to avoid repetition of a unit (which looks a bit crowded)
@cshinn is this something that can/should be added as default to PF? how does PF handle today explanation/display of which unit is the graph about?

**Comment by cshinn** [comment]
@abonas That should be achievable by using the [axis label](https://c3js.org/samples/axes_label.html) and [axis label position](https://c3js.org/samples/axes_label_position.html) parameter of C3 (which pf charts are based on)

**Comment by lucasponce** [comment]
I agree with @jotak comments. 
One step can be to bring more clarity in the units as this PR address as it was something commented.
As the proposal means to perform the change in the component of Patternfly I will suggest merging this one and updating the component once that is fully supported in patternfly, as it may have some side effects with the units computation.

**Pull request merged**
