### PR TITLE
Backport - Revert back YAML changes when canceling

### PR DESCRIPTION
**Pull request by lucasponce**
Backport of kiali/kiali#1586 for v1.0 branch.

@hhovsepy could you test if it is ok for v1.0 branch (potentially to be added into Kiali 1.0.6).

### CODE REVIEW

**Comment by lucasponce** [comment]
> The original issue is fixed, but now, when hit Cancal on changed YAML, it does not show the notification message: "You have unsaved changes, are you sure you want to leave?"

Ouch, I cherry-picked the commit from master, Ok, I will review the regression.

Thanks @hhovsepy

**Comment by lucasponce** [comment]
@hhovsepy I've ammended the PR with the changes for the regression.
I tested and it worked in my localhost, but I need to recreate the environment so I couldn't test all cases.
Please, could you re-test it ?
Thanks.

**Comment by hhovsepy** [comment]
It shows the same message for for Cancel and Refresh, but if it is by design, then I am fine with that.
Screenshot from 2019-09-18 16-55-39

**Comment by lucasponce** [comment]
@hhovsepy ouch, nice one, that can be changed easily.
Will update the PR.

**Comment by lucasponce** [comment]
@hhovsepy ok, message changed. I splitted in a different commit as it was minor

**Pull request merged**
