### PR TITLE
[WIP] Move Namespace up to header and Reduxify namespace

### PR DESCRIPTION
**Pull request by mtho11**
Move Namespace selector to the application header

- [x] Add more type safety to namespace related actions/reducers/handlers
- [x] Add _namespace_ to redux store and utilize it
- [x] Make ToolbarDropdown have the option to use names(values) instead of keys
- [x] Change namespaces state to namespaceState to change to standardized
- [x] Vacation
- [x] Fix tests with the above changes
- [ ] Integrate Service List to use new redux namespace (these pages don't currently use redux) and remove from filter list
- [ ] Integrate Istio Config List to use new redux driven namespace and remove from filter list

** Issue reference **
https://issues.jboss.org/browse/KIALI-943

Change behaviour related to namespace changes.

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#37](https://paste.fedoraproject.org/paste/i06Iujee2u2AACmqyE8XWA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1234]](https://paste.fedoraproject.org/paste/u2T0EhllM6pisLDAPVSQRw)
  * :heavy_check_mark: Kiali-on-Openshift [#[579]](https://paste.fedoraproject.org/paste/hiCQFPEr72hIOkJPKW2oRw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1009]](https://paste.fedoraproject.org/paste/rdpXdP25EJcxNnEV9p5tYQ)
  * :red_circle: run-kiali-e2e-tests [#[58]](https://paste.fedoraproject.org/paste/q4izKYlCxo~q1fp9pTU4Nw)


KIALI_NAME=kialiuipr551-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#38](https://paste.fedoraproject.org/paste/XFonnfrvDKCLfEuFP~csnQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1235]](https://paste.fedoraproject.org/paste/GXxwmS71z1KDPEvJ2phNEA)
  * :heavy_check_mark: Kiali-on-Openshift [#[580]](https://paste.fedoraproject.org/paste/I4Wo0qbBQmz8aPfB6ib~mg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1010]](https://paste.fedoraproject.org/paste/T5tFLX79AhE46eFJi3C-KQ)
  * :red_circle: run-kiali-e2e-tests [#[59]](https://paste.fedoraproject.org/paste/1ihElXxaT060QQpKNExFLQ)


KIALI_NAME=kialiuipr551-istio-system

**Comment by jotak** [comment]
@mtho11 if you're working on it, please have a look at https://github.com/kiali/kiali-ui/pull/667 too: it may conflict with this PR, we may have to coordinate.

**Comment by mtho11** [comment]
Closing as no longer relevant

**Pull request closed without merging**
