### PR TITLE
Trivial: Better align the Graph Legend Close box.

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
This is a very small alignment fix to the graph legend close box as it looked a bit off. Now it is in better alignment with the Legend Title.

** Backwards compatible? **
yes

[ ] Is your pull-request introducing changes in behaviour?
no

** Screenshot **

**Before**:

close-box

**After**:

full-legend

### CODE REVIEW

**Comment by serenamarie125** [comment]
@mceledonia can you provide details of the PF4 legend design?  
font size/weight of (1) legend title (2) category title (3) items

**Comment by serenamarie125** [comment]
@mtho11 it's definitely looking better!  Let's see what michael has for inputs!

**Comment by mceledonia** [comment]
Sure thing! @serenamarie125 @mtho11 @jshaughn 
 
Looks like you are using Overpass in the screenshot above, if that's the case just switch out the font to Overpass with the same value listed below:

**Legend title font:** Red Hat Text // Medium // 16px
**Category title font:** Red Hat Text // Regular // 14px
**Item font:** Red Hat Text // Regular // 12px
**Border styling:** 1px height // #EDEDED

**Comment by mtho11** [comment]
Thanks @mceledonia I will make those changes!
And yes, it is using the Overpass font.

**Comment by mtho11** [comment]
@serenamarie125 @mceledonia 
Here is what it looks like with the changes. WDYT?

new-legend

**Comment by mceledonia** [comment]
Looking good! I think it's fine as-is but if you want to try to get it as close as possible to the initial design, I'll list the spacer values below:

Between divider and category title: 16px
Between category title and first item: 8px
Between two items: 8px
Between last item and divider or end of list: 16px

You can also probably decrease the space between the item label and the item icon/shape, right now I have it as (thinking of the label columns and shape columns as 2 individual columns): 16px between them. In other words, 16px of space from the widest shape in the column to the start of the label column. Here's a quick screenshot because that was a tough one to verbalize

image

**Comment by jshaughn** [comment]
@mtho11 When all changes are made you may be able to reduce the overall width a bit.

**Comment by mtho11** [comment]
@jshaughn are you good with this?

**Pull request merged**
