### PR TITLE
Traces list in side-panel

### PR DESCRIPTION
**Pull request by jotak**
- Split file SummaryPanelNode => (SummaryPanelNode + SummaryPanelNodeMetrics)
- When traces are enabled & service is selected, show a tabbed view Traces/Metrics below contextual node info

Fixes https://github.com/kiali/kiali/issues/2840

### CODE REVIEW

**Comment by jotak** [comment]
New Metrics / Traces tabs WIP: 

Capture d’écran de 2020-06-30 12-24-02

Capture d’écran de 2020-06-30 12-24-05

**Comment by jotak** [comment]
@jshaughn do you validate the approach? Tabs placed within node side panel, below the contextual service information like labels/health. I think it's better to keep this info even in traces tab, so that people still have some context.

**Comment by jshaughn** [comment]
@jotak Looks exactly like I was expecting, including splitting up the logic into separate files.  Only thing I'm not sure about is the naming.  Not sure if I'd prefer "Traffic" as opposed to "Metrics" but that is minor.

**Comment by jotak** [comment]
@jshaughn ok, I've renamed that tab.

New commit: shows traces list:
Capture d’écran de 2020-07-01 16-32-18

Also, there's a button at the bottom for advanced search:
Capture d’écran de 2020-07-01 16-32-23

**Comment by aljesusg** [comment]
> @jshaughn ok, I've renamed that tab.
> 
> New commit: shows traces list:
> Capture d’écran de 2020-07-01 16-32-18
> 
> Also, there's a button at the bottom for advanced search:
> Capture d’écran de 2020-07-01 16-32-23

I would trip the names with a tooltip with the full name.
Maybe in the same line we can show information about the spans with a tooltip when mouseover.

**Comment by jotak** [comment]
Also I need to figure out what's the best way to deal with refreshes ... should it be coupled with graph refresh or not? Problem with that is the trace list is very "volatile", there's most chances that it gets completely renewed on refresh, which could be a pain for user experience.

**Comment by jshaughn** [comment]
> Also I need to figure out what's the best way to deal with refreshes ... should it be coupled with graph refresh or not?

If it's not tied to graph refresh do we have a potential issue with the traces syncing well with the graph?  If it's not much of an issue then perhaps a manual refresh button on the tab could work.

**Comment by jotak** [comment]
> If it's not tied to graph refresh do we have a potential issue with the traces syncing well with the graph? If it's not much of an issue then perhaps a manual refresh button on the tab could work.

Or I thought about a small check box saying "Do not refresh traces list", or something similar, within that traces tab. When checked, refresh requests would be ignored. Else when unchecked, it is tied to graph refresh.

**Comment by jotak** [comment]
> I would trip the names with a tooltip with the full name.
> Maybe in the same line we can show information about the spans with a tooltip when mouseover.

Yes I need to improve the styles a little bit. For some reason when I tried to add "text-overflow: ellipsis" it didn't work... I need to try harder :)

**Comment by jshaughn** [comment]
@jotak I saw in a separate issue you have some struggles with fonts in the side panel.  I wanted to mention that we did a decent amount of work on side-panel l+f consistency.  We use 12px throughout, so please also apply that sizing.  You will see a variety of places in the existing code where that is set.

**Comment by jotak** [comment]
@jshaughn yes I've seen that there's a variable for side panel font-size and I think I'm using it as needed.

**Comment by jotak** [comment]
hey @jshaughn @aljesusg I've added an URL-based switch for experimental features: https://github.com/kiali/kiali-ui/pull/1837/commits/4d0746b98afe8095edadee07c2e8c934d507778f
This will allow to safely merge PRs such as this one before the whole epic is complete (or at least before the minimal subset of tasks necessary for the feature to make sense is complete).

With this, I think this PR can be reviewed / merged. Is it fine with you?
For testing, you'd need to add `&xflags=igt` to the URL.

**Comment by jotak** [comment]
@jshaughn I'll do the suggested style changes before it's merged.
About "keep list" versus "refresh", not sure to understand your suggestion, would it be something like a check box "Decouple from graph" (put better phrasing here) + a refresh button that is displayed / enabled only when the checkbox is checked? If so, I'm fine to do it, as long as keeping tying with graph refresh is still an option.

Also, for this "Keep list", I used different phrasing like "Do not refresh" or "Pin list" before ending on "Keep list", but any suggestion is appreciated.

**Comment by jotak** [comment]
@jshaughn I've added some styles as suggested (ellipsis + bottom margin), squashed & pushed.
Also, I realized that when PassthroughCluster node is selected it was showing (empty) traces tab as well ... I figure out this is what is called an "Inaccessible" service, right? So I added `    !nodeData.isInaccessible &&` check to what would trigger traces display. Does it sound correct?

**Comment by jshaughn** [comment]
>  I've added some styles as suggested (ellipsis + bottom margin), squashed & pushed.
Looks great with the ellipse/tooltip, and the margin.

> About "keep list" versus "refresh", not sure to understand your suggestion
The limitation with "keep list" is that you either get the graph refresh or no refresh.  I was thinking that when "keep list" is enabled a manual refresh of the traces could be useful.  To do this currenly you would need to also refresh the graph.  So, I had suggested changing "keep list" to "manual refresh", and when "manual refresh" was enabled, a local refresh button would also be enabled.

This X-Feature is mergeable as-is imo.

**Comment by jotak** [comment]
thanks for review @jshaughn !

**Pull request merged**
