### PR TITLE
Trace details page, spans table: add filtering toolbar

### PR DESCRIPTION
**Pull request by jotak**
Fixes https://github.com/kiali/kiali/issues/3278

Add sorting & filtering capabilities on the spans table.
reusing the StatefulFilters component

### CODE REVIEW

**Comment by jotak** [comment]
Note: as part as doing this task, I've found quite a lot of things that could be simplified in our filters & sort stuff ... started to do it, but it was turning into a big refactoring, so I will send a separate PR for that.

**Review by aljesusg — APPROVED** [review]
LGFM

**Comment by jotak** [comment]
Before we merge it, one quick question to get your opinion : next to this filter component I added a small text to show how much spans are displayed :

- When there's no active filter:
Capture d’écran de 2020-10-08 09-17-23

- With at least one active filter:
Capture d’écran de 2020-10-08 09-20-18

Actually, perhaps we can use the space on that line to repeat the labels that are in trace details (but on a single line instead):
Capture d’écran de 2020-10-08 09-17-21

wdyt? (cc @lucasponce )

**Comment by hhovsepy** [comment]
A small suggestion, add a text "No spans were found" is filter returns empty result, to be consistent with other pages listings.
Screenshot from 2020-10-08 10-24-19

**Comment by aljesusg** [comment]
I would add this to lists too maybe in another PR

**Review by hhovsepy — APPROVED** [review]

**Comment by jotak** [comment]
Thanks for the review, do not merge yet please, I'm doing the discussed changes

**Comment by jotak** [comment]
> I would add this to lists too maybe in another PR

Which lists do you mean? I can see it's there in workloads/applications/service lists

**Comment by lucasponce** [comment]
Please, minor UI / CSS style:

image

Try to align the filter with the table.

**Comment by jotak** [comment]
All done:
- Added empty state
- Added labels
- CSS alignment fixed

Capture d’écran de 2020-10-08 15-03-26

**Comment by hhovsepy** [comment]
Verified.

Screenshot from 2020-10-08 15-35-41
Screenshot from 2020-10-08 15-36-01

**Comment by hhovsepy** [comment]
Only one issue, not sure coming from this PR or not:
https://github.com/kiali/kiali/issues/3306

**Comment by jotak** [comment]
@hhovsepy I'm pretty sure it won't come from that PR as nothing changed here about the workload identification (so you probably have the same problem of wrong workload identified while checking the trace in the graph, because it shares the same code).
I would say it shouldn't block the PR and I'll take a look at the issue separately

**Pull request merged**
