### PR TITLE
KIALI-1827 Resize columns to allow for longer labels.

### PR DESCRIPTION
**Pull request by pilhuhn**
** Describe the change **

Long labels are cut off

** Backwards compatible? **

[X] Is your pull-request introducing changes in behaviour?

_Describe the changes if appropriate. E.g. a new link, a change on what a click does, etc_

** Screenshot **

For before see 

Now:

bildschirmfoto 2018-10-31 um 11 10 02

Note: perhaps we should in the longer run not have the labels as part of the table, but rather
as a row that is as wide as the whole table.

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#295](https://paste.fedoraproject.org/paste/7phLWxxQ8C7sS3e6FvwzfA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1855]](https://paste.fedoraproject.org/paste/ubUqMAbqTPzrod-tkDVxUw)
  * :heavy_check_mark: Istio-Upstream [#[697]](https://paste.fedoraproject.org/paste/taHf84eI61lbXIsF-KCybg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2253]](https://paste.fedoraproject.org/paste/4PhM5Z6JKrR9-e3E8DQ3fA)
  * :red_circle: install-bookinfo [#[1239]](https://paste.fedoraproject.org/paste/DvYss09FAF57k1cEjRLAaQ)


KIALI_NAME=kialiuipr781-istio-system

**Comment by jotak** [comment]
Hmm I'm trying to test your PR, but... how do you get that? I can't even view labels on the deployments apart from the app and version (other are not displayed in Kiali, it seems)

**Comment by jotak** [comment]
Oh actually... it's not the labels of the deployment, but the labels of the template! Maybe the UI should make it clearer

**Comment by jotak** [comment]
@pilhuhn can you run `yarn test -- -u` and add the modified snapshots to the commit please? Some of them must be updated.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#296](https://paste.fedoraproject.org/paste/if9nToPrQ42p6Vex5LUZiw)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1857]](https://paste.fedoraproject.org/paste/WHC8AgoSCZLQM4oe5oN1DA)
  * :heavy_check_mark: Istio-Upstream [#[699]](https://paste.fedoraproject.org/paste/giy62-XTcDFkxOb4WLpcrg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2255]](https://paste.fedoraproject.org/paste/4QUB5EOGQPvoqexS8ln5PA)
  * :red_circle: install-bookinfo [#[1241]](https://paste.fedoraproject.org/paste/x9hfh9GxKcqwEhHto6lJXw)


KIALI_NAME=kialiuipr781-istio-system

**Pull request merged**
