### PR TITLE
KIALI-2442 Map kind and apiVersion attributes

### PR DESCRIPTION
**Pull request by lucasponce**
It updates Istio Config object mapping to add "kind" and "apiVersion" into the yaml editor.

https://issues.jboss.org/browse/KIALI-2442

image

It requires backend PR https://github.com/kiali/kiali/pull/886

### CODE REVIEW

**Comment by lucasponce** [comment]
> What do you think about adding a new interface `IstioObject` with `kind, apiVersion and metadata` extending all the interfaces which are Istio Objects?

+1

**Comment by hhovsepy** [comment]
Verified

**Comment by abonas** [comment]
what happens if user edits the kind and apiversion part?

**Comment by hhovsepy** [comment]
It fails to save:
screenshot from 2019-03-04 17-05-50

**Pull request merged**
