### PR TITLE
Enable `noUnusedParams` on tsconfig

### PR DESCRIPTION
**Pull request by cfcosta**
Part of #1154.

Enabling this added the following errors:

```
ERROR: kiali-ui/src/actions/GraphDataThunkActions.ts:35:80 - 'getState' is declared but its value is never read.
ERROR: kiali-ui/src/app/App.tsx:33:20 - 'e' is declared but its value is never read.
ERROR: kiali-ui/src/app/AuthenticationController.tsx:67:5 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/components/BreadcrumbView/BreadcrumbView.tsx:65:5 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/components/BreadcrumbView/BreadcrumbView.tsx:66:5 - 'snapshot' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx:147:22 - 'e' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/CytoscapeGraph.tsx:135:57 - 'nextState' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/CytoscapeGraph.tsx:163:54 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/CytoscapeGraph.tsx:346:26 - 'evt' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/CytoscapeGraph.tsx:356:23 - 'evt' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx:60:25 - 'nextProps' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx:60:41 - 'nextState' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts:129:63 - 'evt' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts:208:30 - 'event' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts:65:82 - 'edge' is declared but its value is never read.
ERROR: kiali-ui/src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts:86:77 - 'edge' is declared but its value is never read.
ERROR: kiali-ui/src/components/DebugInformation/DebugInformation.tsx:67:19 - 'text' is declared but its value is never read.
ERROR: kiali-ui/src/components/DebugInformation/DebugInformation.tsx:76:56 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/components/Filters/StatefulFilters.tsx:91:22 - 'prevProps' is declared but its value is never read.
ERROR: kiali-ui/src/components/Filters/StatefulFilters.tsx:91:55 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/components/Filters/StatefulFilters.tsx:91:88 - 'snapshot' is declared but its value is never read.
ERROR: kiali-ui/src/components/GraphFilter/GraphFind.tsx:533:67 - 'expression' is declared but its value is never read.
ERROR: kiali-ui/src/components/GraphFilter/GraphSettings.tsx:56:22 - 'prevProps' is declared but its value is never read.
ERROR: kiali-ui/src/components/GraphFilter/__tests__/GraphFind.test.tsx:10:20 - 'val' is declared but its value is never read.
ERROR: kiali-ui/src/components/IstioWizards/IstioWizardDropdown.tsx:151:13 - 'results' is declared but its value is never read.
ERROR: kiali-ui/src/components/JaegerIntegration/JaegerToolbar.tsx:130:40 - 'event' is declared but its value is never read.
ERROR: kiali-ui/src/components/MessageCenter/MessageCenter.tsx:84:38 - 'group' is declared but its value is never read.
ERROR: kiali-ui/src/components/Nav/Masthead/UserDropdown.tsx:102:22 - 'event' is declared but its value is never read.
ERROR: kiali-ui/src/pages/AppDetails/AppInfo/AppDescription.tsx:77:40 - 'appName' is declared but its value is never read.
ERROR: kiali-ui/src/pages/AppList/AppListComponent.tsx:49:56 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/pages/AppList/AppListComponent.tsx:49:90 - 'snapshot' is declared but its value is never read.
ERROR: kiali-ui/src/pages/Graph/SummaryPanelCommon.tsx:57:14 - 'err' is declared but its value is never read.
ERROR: kiali-ui/src/pages/Graph/SummaryPanelGroup.tsx:229:16 - 'i' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx:150:13 - 'r' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx:174:15 - 'r' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx:22:14 - 'destinationRule' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx:28:14 - 'virtualService' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx:221:57 - 'i' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx:317:22 - 'route' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigList/FiltersAndSorts.ts:192:73 - 'reject' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigList/IstioConfigListComponent.tsx:58:5 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/pages/IstioConfigList/IstioConfigListComponent.tsx:59:5 - 'snapshot' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceDetails/ServiceDetailsPage.tsx:148:54 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceDetails/ServiceDetailsPage.tsx:282:62 - 'index' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceDetails/ServiceDetailsPage.tsx:282:69 - 'ary' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceDetails/ServiceInfo/ServiceInfoPods.tsx:15:49 - 'currentState' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceDetails/ServiceInfo/types/DestinationRuleValidator.ts:36:71 - 'i' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceDetails/ServiceInfo/types/DestinationRuleValidator.ts:36:74 - 'ary' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceDetails/ServiceInfo/types/SubsetValidator.ts:19:61 - 'i' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceList/ServiceListComponent.tsx:58:60 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/pages/ServiceList/ServiceListComponent.tsx:58:98 - 'snapshot' is declared but its value is never read.
ERROR: kiali-ui/src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx:106:22 - 'prevProps' is declared but its value is never read.
ERROR: kiali-ui/src/pages/WorkloadList/WorkloadListComponent.tsx:53:61 - 'prevState' is declared but its value is never read.
ERROR: kiali-ui/src/pages/WorkloadList/WorkloadListComponent.tsx:53:100 - 'snapshot' is declared but its value is never read.
ERROR: kiali-ui/src/services/Login.ts:33:24 - 'info' is declared but its value is never read.
ERROR: kiali-ui/src/services/Login.ts:56:24 - 'info' is declared but its value is never read.
ERROR: kiali-ui/src/services/__mocks__/Api.ts:13:34 - 'namespace' is declared but its value is never read.
ERROR: kiali-ui/src/services/__mocks__/Api.ts:13:53 - 'service' is declared but its value is never read.
```

I did not change the signature of most the methods as that might have different outputs or break stuff that is not supposed to break.

### CODE REVIEW

**Comment by jotak** [comment]
I'm not sure to really like this rule. Unused params are ok IMO when the function has to match a type (hence we're not free to declare whatever we want). Prefixing everything with underscore sounds weird.

**Comment by jshaughn** [comment]
+1, there are times this rule can go too far.

**Comment by cfcosta** [comment]
@jotak @jshaughn this rule only care about the local bindings, it's a way to signal to the compiler "hey, I need this argument because of some reason, but I'm not going to use it".

This PR makes it seem like we're putting underscores everywhere, but many of those places are actually arguments that we need to remove. Removing them on those places might break stuff, so I'm taking the quick way here so that at least we do not add more unused code.

**Comment by cfcosta** [comment]
Either way, after #1154 gets merged we can re-revaluate if we want this rule or not, since the compiler will be more strict in other places, we can probably relax this one.

The main reason to get this merged is so when we can merge the upgrade without disabling treating warnings as errors on CI.

**Comment by josejulio** [comment]
I think this is good, it forces the developer to make it explicit that the param is not being used, as mentioned by Caina, it could be removed.

This could prevent mistakes when you intended to use the param but forgot about it.

**Comment by mtho11** [comment]
I follow this rule anyway, this just makes it explicit. And specifically shows intent.

**Pull request merged**
