### PR TITLE
KIALI-2818 Add info message line in case of unknown validation result

### PR DESCRIPTION
**Pull request by burmanm**
** Describe the change **

Adds UI support for cases where we can't validate the end result. 

** Issue reference **

KIALI-2818

** Screenshot **

unknown_validation

### CODE REVIEW

**Comment by pilhuhn** [comment]
I almost missed the little 'i' in the screenshot. Could we make it a bit more prominent? Perhaps in blue? Or does blue too much convey "all good"?
@serenamarie125 WDYT?

**Comment by burmanm** [comment]
No, that's the problem with our current AceEditor integration (ace-react). We can't do anything to the icon easily (we discussed this quickly today in the scrum meeting)

**Comment by abonas** [comment]
@serenamarie125 ^^ since the same editor is used in more places, do you know of any workarounds/potential fixes for this?

**Comment by skondkar** [comment]
Verified this PR with deploying kiali PR: https://github.com/kiali/kiali/pull/1055

Below info message is shown for a DR when the "host" has a FQDN that's not real.
'Unable to verify the validity, cross namespace validation is not supported for this field'

**Comment by burmanm** [comment]
Managed to find a way to replace the style.. here's alternate version, using Patternfly icon ``pficon-unknown``. Would this be better?

pficon-unknown

**Comment by xeviknal** [comment]
I started a design issue to move the discussion into our weekly ux-ui meetings: https://github.com/kiali/kiali-design/issues/128

**Pull request merged**
