### PR TITLE
[KIALI-735] Upgrade patternfly-react to 2.5.1

### PR DESCRIPTION
**Pull request by aljesusg**
Jira: [KIALI-735](https://issues.jboss.org/browse/KIALI-735)

- Upgrade Patternfly to 3.48.0
- Upgrade Patternfly-react to 2.5.1

### CODE REVIEW

**Comment by mtho11** [comment]
This is a dupe of https://github.com/kiali/kiali-ui/pull/391

**Comment by aljesusg** [comment]
@mtho11 this is patternfly-react 2.5.1  the #391 is 2.3

**Comment by mtho11** [comment]
@aljesusg yep, I'll bump it again. That library changes almost every day ;)

**Comment by aljesusg** [comment]
Yes... But we need it for the bulletChart...in fact @mtho11 if you can upgrade to the last version will be great because today the fixed a big in the legend that we found in the bulletChart component. Thanks

**Pull request closed without merging**
