### PR TITLE
KIALI-2496 Disabled Slider should not show +/- buttons

### PR DESCRIPTION
**Pull request by lucasponce**
Hide pins when there are only two workloads
Align text into center
Minor changes on style buttons

https://issues.jboss.org/browse/KIALI-2496

image

image

### CODE REVIEW

**Comment by lucasponce** [comment]
DNM label set.
Found a last minute error on my PR.

**Comment by lucasponce** [comment]
Final fix for 2 workloads usecase:

image

**Comment by pilhuhn** [comment]
Looks great!

**Comment by abonas** [comment]
great work! does this remove the pin also for the single route case?

**Comment by hhovsepy** [comment]
@lucasponce I will suggest to hide "Evenly Distribute Traffic" button when there is only one workload.
Also on a case then Mesh wide mTLS is configured:
1. under the Chrome browser, TLS ISTIO_MUTUAL is selected by default, when I change any percent it is reset, when I click on "Evenly Distribute Traffic" it selects back "ISTIO_MUTUAL". Is it on purpose?
screenshot from 2019-03-07 18-28-35
screenshot from 2019-03-07 18-28-51

2. under FF TLS is always NONE by default

**Comment by lucasponce** [comment]
> great work! does this remove the pin also for the single route case?

Yes, in the first comment, there is a capture with that case in the ratings-v1 workload.
As only workload is elegible, it's by default at 100% and disabled.

**Comment by lucasponce** [comment]
Good finding @hhovsepy.
No, it's not intentional, I guess it's a bug, let me work on it.

**Comment by lucasponce** [comment]
Ok @hhovsepy I think I've fixed it
image
"Evenly..." button is out when only one workload and there was a bug in the state between the TLS component and the Wizard.
I think that Chrome & FF hit same bug, locally it seems fixed, let me know.

**Comment by hhovsepy** [comment]
Verified

**Pull request merged**
