### PR TITLE
KIALI-2432 Make edge protocol label appear on the selected edge and a…

### PR DESCRIPTION
**Pull request by josejulio**
…void it to stay after unselecting

** Screenshot **

fix-strange-hover-behavior

### CODE REVIEW

**Comment by jmazzitelli** [comment]
What does this look like what edge labels are enabled? Does it make things noisy?

**Comment by josejulio** [comment]
> What does this look like what edge labels are enabled? Does it make things noisy?

Not more noisy than before :)

I'm not adding the feature, but fixing some weird behavior it has.
I can create a gif of what it looks with the edge labels enabled.

**Comment by mwringe** [comment]
@gbaufake @mattmahoneyrh Can one of you give a quick look to this?

**Comment by josejulio** [comment]
@jmazzitelli 
peek 21-02-2019 13-33

**Pull request merged**
