### PR TITLE
Add a link the kiali-ui development setup video.

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Adds a link to a video detailing the step by step installation of the kiali-ui dev environment. Should be good for on-boarding and attracting community.

### CODE REVIEW

**Comment by aljesusg** [comment]
I think that we can embed youtube video with adoc format

**Comment by mtho11** [comment]
@aljesusg do you have any links for that?

**Comment by mtho11** [comment]
@aljesusg nvm. found it. Thanks for advice!

**Comment by mtho11** [comment]
The embedded youtube has a much cleaner look:

kiali-ui____projects_kiali-ui__-_____README_adoc

**Pull request merged**
