### PR TITLE
Iter8 Listing page - adding icon, tooltip and filtering

### PR DESCRIPTION
**Pull request by jadeyliu939**
** Describe the change **
1. phase and status changes in Iter8 summary listing page - use icon and tooltip to instead of description.
2. Add filtering for service/baseline/candidate

** Issue reference **
[#2634](https://github.com/kiali/kiali/issues/2634)

** Backwards compatible? **

[ ] Is your pull-request introducing changes in behaviour?

_Describe the changes if appropriate. E.g. a new link, a change on what a click does, etc_

** Screenshot **
Screen Shot 2020-04-20 at 1 07 30 PM

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by lucasponce** [comment]
I will adding some comments as soon as I test this PR locally.

One thing I see:
image

It seems there is a Phase situation not handled (empty) and in the icon the tooltip is empty, too.

I think this case needs to be reviewed.

**Comment by lucasponce** [comment]
Minor: typo in the filter.
image

**Comment by lucasponce** [comment]
I wonder if we want to adjust Phase column to similar as other list pages like health:
image
If you see it, we keep only the icon in the column, but in the filter, it can be filtered by health/status.
Same with other status like validation one.

Perhaps the column message can be combined in the tooltip:
image

So, in the Iter8 list perhaps we can keep the icon, allowing to filter by status, and adding the detail on the tooltip.

**Comment by lucasponce** [comment]
Side note, if you can rebase the working branch with master, you will see that now list pages automatically updates on an interval.

That means that status of an Iter8 status will be automatically progressed.

**Comment by lucasponce** [comment]
Fixes https://github.com/kiali/kiali/issues/2634

**Comment by prachiyadav** [comment]
Screenshot from 2020-04-22 22-03-55

Please refer thr screen-shot. Why we have black tooltip?

**Comment by jadeyliu939** [comment]
Complete change requests 
1. Only show icons in the listing, and use tooltip to show phase and status, fix typo
Screen Shot 2020-04-22 at 2 23 17 PM
2. Add filtering and refresh/duration
Screen Shot 2020-04-22 at 2 23 33 PM

**Comment by jadeyliu939** [comment]
New [PR#1753](https://github.com/kiali/kiali-ui/pull/1753) created

**Pull request closed without merging**
