### PR TITLE
Click on namespace labels crashes

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/2904

And some warnings with keys

### CODE REVIEW

**Comment by hhovsepy** [comment]
The functionality is working, but the filter right alignment is wrong:
Screenshot from 2020-06-17 11-03-29

**Comment by aljesusg** [comment]
> The functionality is working, but the filter right alignment is wrong:
> Screenshot from 2020-06-17 11-03-29

What alignment?

**Comment by lucasponce** [comment]
I see a regression on my side:
image

In other pages, clicking on the label doesn't highlight the label used in the filter.

**Comment by lucasponce** [comment]
But I don't see @hhovsepy problems, here it seems ok:

image

**Comment by hhovsepy** [comment]
> But I don't see @hhovsepy problems, here it seems ok:
> 
> image

Right, now only the label highlight is missing.

**Comment by aljesusg** [comment]
Fixed after rebase of rework @lucasponce @hhovsepy thanks

**Pull request merged**
