### PR TITLE
Merge k-charted in kiali

### PR DESCRIPTION
**Pull request by jotak**
It's mainly moving k-charted files into kiali. Some few modifications
however:

- There was some duplicated models between "/metrics" and "/dashboards"
  endpoints. They are now merged. Idem for model manipulation functions.
  This mainly affects the Summary graph panel.
- Explicit typing of IstioMetricsMap to avoid typos on metric names and
  allow safer refactoring (e.g. there was still an old
  'request_duration' metric being used, I removed it)
- Taking this oportunity to rename some of the model to make it more
  understandable.

Fixes https://github.com/kiali/kiali/issues/3422
Backend PR: https://github.com/kiali/kiali/pull/3427

### CODE REVIEW

**Comment by jotak** [comment]
@mattmahoneyrh @hhovsepy @lucasponce @jshaughn I put all of you as reviewers as this is wide and has impacts on both team areas.

In terms of tests this is only about non-regression. Impacted areas are:
- Istio metrics dashboards pages (including settings manipulations)
- Custom dashboards
- Overview sparkline charts
- Graph side panel, all line charts (response time, RPS for any kind of selected node)

**Comment by hhovsepy** [comment]
I see some overlays in metrics left side:
Screenshot from 2020-11-16 11-55-40

**Comment by hhovsepy** [comment]
This overlay exits in older versions as well:
Screenshot from 2020-11-16 11-55-40

**Review by hhovsepy — APPROVED** [review]
LGTM

**Review by jshaughn — APPROVED** [review]
I didn't see any regressions.  I did also notice the issue with throughput y-axis labels having too much precision and spilling out of the window, but it's a separate issue, not a regression.

**Review by mattmahoneyrh — APPROVED** [review]

**Review by lucasponce — APPROVED** [review]

**Pull request merged**
