### PR TITLE
Make Graph Legend Scrolling more Obvious (and move to PF4)

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Use the new design for Graph Legend (moving it to the left instead of floating to the right). This will resolve some other bug/issues with regards to small screens etc.

- [x ] Move Graph Legend to Left side of Graph (and make non-modal)
- [x ] Resolve issues with hide/show Sidebar and hide/show Legend together
- [x ] Migrate the code to PF4

fixes: https://github.com/kiali/kiali/issues/1620

** Screenshot **

Add a screenshot of the UI after your changes.
**Before**:

fefore

**After**:

legend-left2

**Expand/Collapse of Both Nav and Legend:**

legend-left

### CODE REVIEW

**Comment by mattmahoneyrh** [comment]
Looks like additional scroll bar with Firefox 68


Selection_087

**Comment by jshaughn** [comment]
@mattmahoneyrh Yup, I saw that same on chrome and Mike is working on it...

**Comment by mtho11** [comment]
That is a weird one because it doesn't show up on chrome on OS/X.

**Comment by josejulio** [comment]
IIRC OSX hides the scrollbar by default.

**Comment by mtho11** [comment]
@mattmahoneyrh can you retest please?

**Pull request merged**
