### PR TITLE
Initial cypress integration

### PR DESCRIPTION
**Pull request by nrfox**
Adds cypress for integration testing. This PR is foundational for future cypress work for either QE or dev. It essentially just adds cypress to the project without yet adding any tests or making assumptions for how those tests should be structured.

There's a single test included to serve as an example of the integration working. This can be run when testing kiali locally by first running the UI dev server with `yarn start` and then running `yarn cypress`.

### CODE REVIEW

**Comment by nrfox** [comment]
@ScriptingShrimp assigning you as a reviewer just to keep track of progress so we don't overlap our efforts. I've written a few basic tests mostly to try out different features and to use as a starting point. I haven't fully decided what all should be included in the initial integration PR so if you have any preferences or opinions let me know.

I also haven't yet tested out the cucumber plugin but I'm happy to include that with the initial PR and update the tests.

**Review by ScriptingShrimp — APPROVED** [review]
LGTM, thanks for this effort!
As a starting point this is good enough. Lets merge it so we can have hands on with other QE's. Thank you

**Review by ScriptingShrimp — APPROVED** [review]

**Review by jshaughn — APPROVED** [review]
Starting to look at cypress more today.  This looks fine, I think we can merge straightaway.  The test passes.  I do have a problem playing the video locally.  My F32 player gives me, "The playback of this movie requires a H.264 (High Profile) decoder plugin which is not installed."

Update: I installed VLC and was able to watch the video.

**Comment by nrfox** [comment]
Closing this in favor of #2312 so we can move things along with the BDD integration.

**Pull request closed without merging**
