### PR TITLE
KIALI-1377 Add Inbound and Outbound metrics tab on Workload Details page

### PR DESCRIPTION
**Pull request by aljesusg**
** Describe the change **

Add the metrics tab to Worload Page

workloadmetrics

** Issue reference **
Jira: [KIALI-1377](https://issues.jboss.org/browse/KIALI-1377)

### CODE REVIEW

**Comment by lucasponce** [comment]
Added DNM to fetch locally and review.

**Comment by aljesusg** [comment]
Added outbound metrics @lucasponce . Thanks
workloadmetrics

**Comment by aljesusg** [comment]
Changed @lucasponce Thanks

**Comment by aljesusg** [comment]
Thanks

**Comment by lucasponce** [comment]
My bad, I merged but I see after that a minor issue:
image
Could you add a following PR ? reusing same commit number would be enough.

**Comment by aljesusg** [comment]
Oh Yes. Thanks @lucasponce

**Pull request merged**
