### PR TITLE
KIALI-1688 Get in-app graph help to render decently on different browsers

### PR DESCRIPTION
**Pull request by jshaughn**
@mattmahoneyrh and @mwringe , perhaps one or both of you can try this PR on some different browsers.   For me it leaves some white space on the right side of the boxes on Chrome, but now in FF the text at least fits in the boxes.  It also seemed OK on Edge.

Also, I changed the help text in all of the boxes to be more descriptive, more concise, and to remove a typo or two.  So please review the text.

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#190](https://paste.fedoraproject.org/paste/wHNqHRu~Z4TrCvUuiojfoQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1551]](https://paste.fedoraproject.org/paste/Zva7qGh4~3613-MV-rWsPA)
  * :heavy_check_mark: Istio-Upstream [#[408]](https://paste.fedoraproject.org/paste/ZZIeUxu1xrpbPzZadHZP5A)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1656, 1657]](https://paste.fedoraproject.org/paste/VVgePAM8sNi~ylX0Q677fA)
  * :heavy_check_mark: install-bookinfo [#[921]](https://paste.fedoraproject.org/paste/TPfnX~kGaYWalPck5V3Ceg)
  * :heavy_check_mark: Kiali-on-Openshift [#[928]](https://paste.fedoraproject.org/paste/Lp2rJpmHuzJdqh1671skuQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[349]](https://paste.fedoraproject.org/paste/Hwrz~sTiiRG5myr7PLwAww)


KIALI_NAME=kialiuipr738-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#191](https://paste.fedoraproject.org/paste/fPxUtDaw2qXVn4AX62Dq0w)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1552]](https://paste.fedoraproject.org/paste/DfUtsEzcIGScb~ULBCVSzA)
  * :heavy_check_mark: Istio-Upstream [#[409]](https://paste.fedoraproject.org/paste/S9G6lOGxuswlatpQq5PWOw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1658, 1659]](https://paste.fedoraproject.org/paste/MbR3XNGq9Ao9JE0Ii3IN2w)
  * :heavy_check_mark: install-bookinfo [#[922]](https://paste.fedoraproject.org/paste/8spopIQ2~LNi9IjHiKPZ2A)
  * :heavy_check_mark: Kiali-on-Openshift [#[929]](https://paste.fedoraproject.org/paste/lHfNACjQBIrQnjXbRP905g)
  * :heavy_check_mark: run-kiali-e2e-tests [#[351]](https://paste.fedoraproject.org/paste/zbbzau3EfjeQlDSaz7lQGw)


KIALI_NAME=kialiuipr738-istio-system

**Comment by josejulio** [comment]
I'm working on the next version of this in-app graph help, so this will likely be replaced by https://issues.jboss.org/browse/KIALI-1625

**Comment by jshaughn** [comment]
@josejulio No poblem.   If this one helps even briefly, or for a backport, then that's good enough.

**Comment by mattmahoneyrh** [comment]
Chrome is OK now (not text over edge of box), but

**Pull request closed without merging**
