### PR TITLE
View logs in fullscreen mode

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Adds the capability to show full-screen logs for a zoomed-in view of logging.

** Issue reference **
fixes https://github.com/kiali/kiali/issues/2691

** Screenshot **

Kiali_Console

Kiali_Console

### CODE REVIEW

**Comment by lucasponce** [comment]
I don't understand.
We commented we want to discuss this feature in the logs and editors, otherwise why do we discuss this in the UX ?

**Comment by mtho11** [comment]
@lucasponce in discussing with @jshaughn yesterday, we decided to get this feature in and fix the other editors once we have a strategy. Or else how long would this feature just sit there?

**Comment by jshaughn** [comment]
@lucasponce A unified Kiali approach to full-screen can be good but it doesn't take away from the usefulness of this feature for the logs tab.  I see no reason to hold back for logs as we can iterate on this feature.

**Comment by pbajjuri20** [comment]
conditionally approve:  The Title header is left with more white space. If possible, can you please fix it. This is just a UI change and does not impact any functionality.



logs full screen

**Comment by mtho11** [comment]
That spacing is due to the `title` required  attribute in the `Modal` component, which is set to `title=''`

**Comment by mtho11** [comment]
Since this is a whitespace issue I'm going to merge this and fix in the next PR.

**Comment by lucasponce** [comment]
@mtho11 @jshaughn 

Mike,

Developers are responsible to ensure consistency across Kiali, it's not responsability of UX.

With this work in the logs tab, I see it deviates more and more (different location of controls compared with other pages, different approaches for similar features).

This has to change.

UX is not responsible of that, we (the developers team) need to identify this situations and reporte them (as we did in the UX meeting) and work on them.

I don't see that happening, just progressing without taking into consideration the consistency comments we did.

So, that's creating a problem and I have the feeling that we don't understand the same way to work on this.

**Comment by jshaughn** [comment]
@lucasponce I agree that devs are responsible for consistency across Kiali.  UX can help us improve even further by offering expertise in layout, cleanliness and usability of the work we have already put in place.  And we can apply UX suggestions iteratively, whether it's before or after work is merged.

As for this logs tab I don't see the deviation you're talking about and as such I think you'll need to be more specific.  If you are talking about the Full Screen/compress icons as opposed to the expand icons used in metrics, those icons are not doing the same thing.  As for your suggestion to apply Full Screen across text area/editors, it can be done but doesn't need to be done as part of this PR.   As for any other controls, please be specific.  As for breaks in process, again, please be specific.

**Pull request merged**
