### PR TITLE
Dissociate grafana info fetching from login sequence

### PR DESCRIPTION
**Pull request by jotak**
So that login isn't slowed down when grafana doesn't answer quickly.
Removing all redux-based grafana state, replaced with a simple static promise.

Closes https://github.com/kiali/kiali/issues/1562

### CODE REVIEW

**Comment by jotak** [comment]
Opening as draft, I still need to test several error paths

**Comment by jotak** [comment]
@israel-hdez @mtho11 @josejulio are you ok with this removal of redux here?
I'm doing this because the redux state looks like an overkill to me here, logic was dispatched in 10 different files whereas the GrafanaState is being used only in one place.

**Comment by israel-hdez** [comment]
@jotak Coming here just to say that I'm :+1: about reducing Redux usage only when neccessary :)
Clever move to using a static field in the IstioMetrics component.

**Comment by mtho11** [comment]
@jotak yep. agreed.

**Pull request merged**
