### PR TITLE
KIALI-2990 Show empty page messaging when overview has no namespaces

### PR DESCRIPTION
**Pull request by jshaughn**
kiali-2990

### CODE REVIEW

**Comment by mtho11** [comment]
Can we get a before/after?
This is a nit, but the PR doesn't follow the template just one animated gif.

**Comment by josejulio** [comment]
Before: before

**Comment by jshaughn** [comment]
gracias for the screen shot @josejulio !

**Comment by abonas** [comment]
@jstickle can you please review this new sentence? I'm having doubts about "user account has no accessible namespaces", perhaps this should be changed to something like "user has no permissions to access namespaces?" 
It's not that the namespaces are accessible (or not), nor do they belong to user accounts, but the user accounts have no access/permissions to the namespaces.

**Comment by JStickler** [comment]
@abonas I think you revision ( "user has no permissions to access namespaces") is an improvement.

**Comment by jshaughn** [comment]
@abonas @JStickler Please see and approve https://github.com/kiali/kiali-ui/pull/1253

**Pull request merged**
