### PR TITLE
Show message if Kiali is configured with LDAP or login strategy for authentication

### PR DESCRIPTION
**Pull request by israel-hdez**
Results on the following when LDAP is configured:

image

Results on the following when "login" is configured:

image

Part of kiali/kiali#2863, kiali/kiali#2862.

### CODE REVIEW

**Comment by israel-hdez** [comment]
Trivial, so skipping QA. I'll merge after dev-approvals.

**Comment by jmazzitelli** [comment]
@israel-hdez can we add a link to these messages that the user can click to get more information? I don't know what to link to :) Maybe the github issue? Maybe the getting-started page with the Login Options? Something to give them some place to go to for more details.

**Comment by israel-hdez** [comment]
@jmazzitelli I think I can link to the currently non-existent v1.19 section of the release notes page (https://kiali.io/news/release-notes/) and add some notes there about the deprecation.

**Comment by israel-hdez** [comment]
@jmazzitelli OK, I added a link to https://kiali.io/news/release-notes/#_1_19_0, which does not exist yet, but hoping it will exists at some point ;)

Images are updated.

**Pull request merged**
