### PR TITLE
Fix lighted when label is equal a value

### PR DESCRIPTION
**Pull request by aljesusg**
After replace of '"' by ':' I forgot change it in the light feature

## Before
Screenshot from 2020-04-14 12-54-42

## After
Screenshot from 2020-04-14 13-00-51

### CODE REVIEW

**Comment by aljesusg** [comment]
Fix https://github.com/kiali/kiali/issues/2650

**Comment by hhovsepy** [comment]
Thanks @aljesusg it is fixed now:
Screenshot from 2020-04-14 14-32-28

**Comment by aljesusg** [comment]
great @hhovsepy plz approve the PR to be merge it

**Comment by hhovsepy** [comment]
@aljesusg just a small point, when filtering by "version:v2" it highlights only exact "v2" labels, but shows all labels containing "v2", is this the expected scenario?
Screenshot from 2020-04-14 15-10-32

**Comment by aljesusg** [comment]
> @aljesusg just a small point, when filtering by "version:v2" it highlights only exact "v2" labels, but shows all labels containing "v2", is this the expected scenario?
> Screenshot from 2020-04-14 15-10-32

yes because you are looking for version:v2 not v2-X ...or Should we show values startwith too?  @lucasponce ??

**Comment by aljesusg** [comment]
mm If we filter we shoudl light them too, let me change it

**Comment by aljesusg** [comment]
Done @hhovsepy  Thanks !!!

**Comment by prachiyadav** [comment]
Screenshot from 2020-04-14 21-10-25
Screenshot from 2020-04-14 21-09-40

**Pull request merged**
