### PR TITLE
KIALI-2789 Fix x-axis ticks on small screens

### PR DESCRIPTION
**Pull request by jotak**
JIRA: https://issues.jboss.org/browse/KIALI-2789

### CODE REVIEW

**Comment by jotak** [comment]
Do not merge: I'll improve a little bit to fix this [ https://issues.jboss.org/browse/KIALI-2523 ] at the same time

**Comment by jotak** [comment]
Now x-ticks are also relative to spans, so small charts will have less ticks and smaller time format:

sshot

See in red, ticks for large chart, in green ticks for small charts

**Comment by hhovsepy** [comment]
Verified the small resolution fix, as marked in green ticks.

**Comment by jotak** [comment]
thanks for review/test @jshaughn @hhovsepy

**Comment by jotak** [comment]
cc @kiali/ux-reviewers

**Pull request merged**
