### PR TITLE
Add typeRoot for resolving types from IDE

### PR DESCRIPTION
**Pull request by lucasponce**
I don't know if there is a better way, but it seems the current tsconfig.json doesn't help IDE to resolve dependencies.

Adding this one helps but not sure if it may have some non desired side effect.

Please, review.

### CODE REVIEW

**Comment by cfcosta** [comment]
What happens when you try getting types for dependencies that do not provide `@types`? I think `moment` is a good one to test that.

**Comment by mtho11** [comment]
@cfcosta I think that is a corner case that you mentioned and shouldn't stop this from going in.

**Comment by mtho11** [comment]
Just adding this for reference: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Comment by cfcosta** [comment]
Tested here on vim with languageclient, seems to be working ok.

**Pull request merged**
