### PR TITLE
Support Iter8-v1.0.0

### PR DESCRIPTION
**Pull request by jadeyliu939**
** Describe the change **
Support Iter8 v1.0.0 (Documentation - https://iter8.tools/)
Require PR [#3179] (https://github.com/kiali/kiali/pull/3179)
** Issue reference **
issue #2007

** Backwards compatible? **
Only support  Iter8 v1.0.0

[ ] Is your pull-request introducing changes in behaviour?

_Describe the changes if appropriate. E.g. a new link, a change on what a click does, etc_
Major changes
1. Add A/B/n support ( new badge for Experiment Type: Canary and A/B/n
2. Experiment Create Page, with additional CRD requirement
3. Experiment Detail page, with new tab "Assessment"
4. Allow creation of Experiment using YAML file ( with YAML editor or file upload)

** Screen Shot ***

Screen Shot 2020-09-06 at 4 44 14 PM

Screen Shot 2020-09-06 at 4 44 35 PM

Screen Shot 2020-09-06 at 4 45 02 PM

### CODE REVIEW

**Comment by jadeyliu939** [comment]
@lucasponce  Please review the changes.

**Comment by lucasponce** [comment]
Style issue: let's try to keep a similar header aspect in the new YAML page.
For example, this header:
image
And this one should be similar:
image

Just add a "Create a New Iter8 Experiment" to the new page, probably there is a missing edge in the UI routes where the titles are set.

**Comment by lucasponce** [comment]
Minor, probably not for this PR but I'll leave a note for myself too.

The Iter8 details page needs to adjust the header, perhaps some CSS is adding a couple of more height.
image

No action on this PR for this, but for myself to try to align these components.

**Comment by lucasponce** [comment]
Also in the new page there are some CSS issues with the bottom:
image
Compared with the editor in the Istio Config Details:
image

**Comment by lucasponce** [comment]
Where could I select the new A/B/C experiment type in the new page ?
This is what I see locally:
image

**Comment by jadeyliu939** [comment]
Fix the Title and spacing issues, also reduce the height of the editor
Screen Shot 2020-09-09 at 4 56 09 PM

**Comment by jadeyliu939** [comment]
The A/B/n or Canary experiment depends on the number of candidates selected. Currently, there is no need to let use choose the type. In the future feature enhancements, Iter8 team might add additional experiment type, we can then add a selection for experiment type.

**Comment by lucasponce** [comment]
Thanks @jadeyliu939.
I've made a couple of more testing, but I get a failed load of the yaml using:

```
https://raw.githubusercontent.com/iter8-tools/iter8/v1.0.0-rc1/doc/tutorials/istio/bookinfo/canary_reviews-v2_to_reviews-v3-simple.yaml
```

image

Also, in the screenshot it seems when the editor is empty the height looks large and I'd say no need to scroll in those cases too, only the editor should scroll on large files.

**Comment by lucasponce** [comment]
I'm still seeing this unnecessary scroll:
image

I suggest to try to align like the Istio Config editor:
image

When the yaml is larger, it's the editor which scrolls but not the page.

I think it's the only aspect I see to merge this work, other refinements can go in followup PRs.

**Comment by jadeyliu939** [comment]
Remove the unnecessary scrollbar, only the Editor get the scrollerbar when a big Yaml is entered
Screen Shot 2020-09-14 at 4 01 44 PM

**Review by lucasponce — APPROVED** [review]
Good progress @jadeyliu939, thanks for the PR.

**Pull request merged**
