### PR TITLE
Update patternfly charts to 4.7.9 in order to have ChartBullet 

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **
There is the need to use CharBullet component from PF4. This component is available in 4.7.9 of Patternfly Charts dependency.

This PR adds that Component up.

Need in https://github.com/kiali/kiali/issues/1593

### CODE REVIEW

**Comment by xeviknal** [comment]
The only charts used directly in kiali (not k-charts) are in the overview page. Here's a screenshot:
Screenshot of Kiali Console (17)

**Comment by xeviknal** [comment]
Do not merged added due to: https://github.com/patternfly/patternfly-react/issues/2815
It is shown in travis also.

**Comment by aljesusg** [comment]
We need @patternfly/react-tokens to 2.6.21 here, the version installed by react-charts is a old release that not include **chart_bullet_axis_tick_count**


Add 

```json
"@patternfly/react-tokens": "2.6.21",
```

**Comment by xeviknal** [comment]
@hhovsepy do you mind checking again? The regression should be fixed :)

**Pull request merged**
