### PR TITLE
[PF4] MIgrate Actions and ACEeditor buttons from Istio Page

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **
Screen recording (4)

Includes https://github.com/kiali/kiali-ui/pull/1397, otherwise cancel button doesn't work. Merge https://github.com/kiali/kiali-ui/pull/1397 first.

Closes https://github.com/kiali/kiali/issues/1593

### CODE REVIEW

**Comment by lucasponce** [comment]
@xeviknal I think in PR #1396 
https://github.com/kiali/kiali-ui/pull/1396/files#diff-83a1e884d16d17f86b191fa3af0d73f5R398

I've migrated the "confirm delete" modal to PF4 as well, I'm also touching this files so I can do it in that pass, but just in case you want to add it on this PR or we can sync to be added on my WIP.

Just let me know :)

**Comment by lucasponce** [comment]
#1397 is already merged, perhaps this one can be rebased.

**Comment by lucasponce** [comment]
I don't know if this only happens to me:
image

It seems the editor height should be adjusted, now buttons are always at the bottom using the overflow space and it needs to scroll down.

I tried to resize the window, but it continues to be in the bottom part of the window.

**Comment by xeviknal** [comment]
@lucasponce and @hhovsepy changes approached. Scroll removed, Modal migrated.

**Pull request merged**
