### PR TITLE
Labels filtering: click on labels to filter

### PR DESCRIPTION
**Pull request by aljesusg**
Fixes https://github.com/kiali/kiali/issues/2735

## Demo
ezgif-4-4aee51cba4a5

I need to do it for OverviewPage too but I want to sent the PR for start reviewing it.
What do you think @jotak ? I didn't see another way to do it than use refs.

### CODE REVIEW

**Comment by jotak** [comment]
That's really nice!
Do you think it would be easy to implement the reverse mechanism also? ie. when you click a label that is active, it's removed from filters?

**Comment by aljesusg** [comment]
> That's really nice!
> Do you think it would be easy to implement the reverse mechanism also? ie. when you click a label that is active, it's removed from filters?
> If it's not trivial no problem - we could perhaps open a new task for enhancements.

Yes we can do it... I was thinking about to add a tooltip withj soemthing like "Remove filter" or "Add filter"

**Comment by aljesusg** [comment]
> > That's really nice!
> > Do you think it would be easy to implement the reverse mechanism also? ie. when you click a label that is active, it's removed from filters?
> > If it's not trivial no problem - we could perhaps open a new task for enhancements.
> 
> Yes we can do it... I was thinking about to add a tooltip withj soemthing like "Remove filter" or "Add filter"

The problem here @jotak is that when user set label app:details this is going to match all labels "contain" details so if we have the label app:details-v1 activated and the user click I think that the behaviour should be something like...if there is a label app:details-v1 applied so the user can remove it, cursor change and there is a tooltip....otherwise no cursor, no tooltip.

What do you think?

**Comment by aljesusg** [comment]
## behaviour
# Add Filter
Tooltip: Add label to Filters
Cursor: Pointer
add
# Remove Filter
Case: (The filter key:value is in filters)
Tooltip: Remove label from Filters
Cursor: Pointer
Remove
9379-ce8130c5ee2d.png)

What do you think @jotak ?

**Comment by aljesusg** [comment]
🔍  Finding changed files since git revision f0ba580e.
🎯  Found 6 changed files.
🔍  Examining package.json.
🔍  Examining src/components/Filters/StatefulFilters.tsx.
🔍  Examining src/components/VirtualList/Config.ts.
🔍  Examining src/components/VirtualList/Renderers.tsx.
🔍  Examining src/components/VirtualList/VirtualItem.tsx.
🔍  Examining src/components/VirtualList/VirtualList.tsx.
✅  Everything is awesome!
Done in 0.91s.


:'(

**Comment by aljesusg** [comment]
ok update dep...can we add some test for this ?

**Comment by lucasponce** [comment]
Please, @aljesusg this requires rebase, thanks

**Comment by aljesusg** [comment]
Rebased

**Comment by jotak** [comment]
@aljesusg hmm I didn't realize that it wasn't exact matching. It's fine to do as you suggest.

**Pull request merged**
