### PR TITLE
testpr

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: hayk-kiali-core-pr-e2e-test [#26](https://paste.fedoraproject.org/paste/yvC4~dHz60U1gtaHwuuWwQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: hayk-kiali-core-pr-e2e-test [#27](https://paste.fedoraproject.org/paste/KfFsOWcbbjkQagROg82NXg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: hayk-kiali-core-pr-e2e-test [#28](https://paste.fedoraproject.org/paste/gKMyI1hUC8PKN9Zb~0gLtg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: hayk-kiali-core-pr-e2e-test [#29](https://paste.fedoraproject.org/paste/zbWSJu2rJDzkyy59Z6wF9g)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: hayk-kiali-core-pr-e2e-test [#30](https://paste.fedoraproject.org/paste/XTR~iphkt7Z0sTbqMTfy6Q)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1955]](https://paste.fedoraproject.org/paste/LDsIIbE-PC8VyUkNOqy8DA)
  * :red_circle: run-kiali-e2e-tests [#[706]](https://paste.fedoraproject.org/paste/hkT720Wm~0szs3CVKOpSBQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-core-pr-e2e-test [#31](https://paste.fedoraproject.org/paste/S~Wixx0UrLsrxBlVo8KAEQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1956]](https://paste.fedoraproject.org/paste/l5zmNFLvXNzJeQtQRFGh6w)
  * :red_circle: run-kiali-e2e-tests [#[707]](https://paste.fedoraproject.org/paste/nY9KKS9pmLgOHqyLRP0sCQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-core-pr-e2e-test [#32](https://paste.fedoraproject.org/paste/npbnrP4KEEX1pFxynVzWYQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1957]](https://paste.fedoraproject.org/paste/oIhbF01T7D1x9rwiYgZFGw)
  * :red_circle: run-kiali-e2e-tests [#[708]](https://paste.fedoraproject.org/paste/GS4~WFvC201bbZMFs~TQSg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-core-pr-e2e-test [#33](https://paste.fedoraproject.org/paste/D~5rMa2M7Gz0bkTl3JCFWA)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-core-pr-e2e-test [#34](https://paste.fedoraproject.org/paste/nVbYa3UlCPIEtSBmzVsK9w)
  * :red_circle: run-kiali-e2e-tests [#[710]](https://paste.fedoraproject.org/paste/GyXfFdh8f8rYHgZAG662EQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: hayk-kiali-core-pr-e2e-test [#35](https://paste.fedoraproject.org/paste/ea2ZUkkDjLY8ncE1R8CAeg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: kiali-ui-pr-e2e-test [#305](https://paste.fedoraproject.org/paste/PegvXjzLJZVUF3115iEC1A)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-ui-pr-e2e-test [#309](https://paste.fedoraproject.org/paste/nMlQtohdikyTEqbd3qKMOQ)
 :red_circle: PRT Failed, Please Contact QE

**Pull request closed without merging**
