### PR TITLE
KIALI-2410 Replace bars with status column (traffic tab)

### PR DESCRIPTION
**Pull request by israel-hdez**
https://issues.jboss.org/browse/KIALI-2410

* Remove the green/red bars that appear at the end of each row in the detailed traffic tab.
* Add a "status" column showing colored icons, depending on the thresholds.

This is per UXD recommendation: https://github.com/kiali/kiali-design/issues/70#issuecomment-462904571

image

### CODE REVIEW

**Comment by israel-hdez** [comment]
@jotak Not sure if I added any bias to the UXD thread (https://github.com/kiali/kiali-design/issues/70#issuecomment-462904571). I think you are in a more neutral position, it's up to you whether to merge.

Instead of labeling the first column as "Health" it's labeled as "Status". I think this may solve the terminology issue.

For me, this look is much cleaner and more understandable than the bars. But you have the last word.

**Comment by jotak** [comment]
Looks good from the screenshot, I'm going to test locally.
BTW is the "unknown" icon already used somewhere else? It could replace our "N/A" text in health, or vice-versa.

**Comment by abonas** [comment]
I probably missed some discussion on this. But why is there a "tab/space" in destination column for some rows? For example reviews vs reviews-v1. is this supposed to indicate hierarchy?

**Comment by jotak** [comment]
@abonas more than a hierarchy I think it shows the sequence of outgoing requests: first "caught" by a service, then a workload. "Caught" by service is symbolic as services don't run any code, but this is the abstract representation shown, as in the graph.

**Comment by abonas** [comment]
> @abonas more than a hierarchy I think it shows the sequence of outgoing requests: first "caught" by a service, then a workload. "Caught" by service is symbolic as services don't run any code, but this is the abstract representation shown, as in the graph.

@jotak typically a grid/tabular view like this does not visualize the dependency/relation/hierarchy between the rows. Each row is on its own. So the way it looks now, it's looks like a formatting bug, although it's not :)
If there is a need to emphasize the relation between the rows, we'll probably need a different or an additional indication. I'll ask on the design issue.

**Comment by israel-hdez** [comment]
> @abonas But why is there a "tab/space" in destination column for some rows?

What @jotak said is the right explanation :)

> @jotak BTW is the "unknown" icon already used somewhere else?

I don't remember other places using it.

**Comment by abonas** [comment]
it seems that compared to the design, there is a "down" arrow missing from the "parent" rows, and that arrow is what indicates hierarchy.

**Comment by israel-hdez** [comment]
@abonas I deliberately omitted the down arrows because I didn't like how it looks when placed next to the service icons. And, although not too important, also because the TableGrid control doesn't seem to support the expand/collapse feature, and the down arrow may give this idea. If there is no problem with this, I will add the down arrows.

The expand/collapse feature can be added without the TableGrid support, it's not hard, but it's more code. So, I could implement it in another PR.

**Comment by abonas** [comment]
> @abonas I deliberately omitted the down arrows because I didn't like how it looks when placed next to the service icons. And, although not too important, also because the TableGrid control doesn't seem to support the expand/collapse feature, and the down arrow may give this idea. If there is no problem with this, I will add the down arrows.
> 
> The expand/collapse feature can be added without the TableGrid support, it's not hard, but it's more code. So, I could implement it in another PR.

I don't have a strong opinion about this and whether more work needs to be invested into something more sophisticated.
The only thing I would like to see improved is how it currently looks like there's a formatting issue, while it's not

**Comment by israel-hdez** [comment]
I'll merge this PR since this is supposed to address the design about the icons vs the bars.
@abonas can we discuss the row indentation in the weekly UXD call? (although I no longer see the entry of the call in the calendar)

**Pull request merged**
