### PR TITLE
KIALI-1598 Support service detail graphs

### PR DESCRIPTION
**Pull request by jshaughn**
This is the ui-side support.  It depends on merge of server-side PR https://github.com/kiali/kiali/pull/517.  Setting DNM until that is merged.

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#107](https://paste.fedoraproject.org/paste/C8WmMnOhIE3hUyRV-N-jaQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1384]](https://paste.fedoraproject.org/paste/XMygAsL227cn4AyFOnlM3Q)
  * :heavy_check_mark: Istio-Upstream [#[260]](https://paste.fedoraproject.org/paste/OC5m2hpmH8LPDecbOe7yBQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1318, 1319]](https://paste.fedoraproject.org/paste/DAI29P7ZlGq14NFHt4AmvA)
  * :heavy_check_mark: install-bookinfo [#[744]](https://paste.fedoraproject.org/paste/ITnGyQVXemYZl8Dw8gSLQQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[754]](https://paste.fedoraproject.org/paste/ZBGlT3KcMSfCNHdvshV5dQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[201]](https://paste.fedoraproject.org/paste/qbiMgItYtlcPs62yAa~ofA)


KIALI_NAME=kialiuipr703-istio-system

**Comment by jmazzitelli** [comment]
I select the Details service triangle here:

image

 and I get this:

image

That doesn't seem right, does it? Should I see just the red edge and the nodes connecting it? Or should I see what I see?

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#115](https://paste.fedoraproject.org/paste/ZSKJ5PFPanj8WibrQiO9ww)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1394]](https://paste.fedoraproject.org/paste/53Ln6mQGhNSy85hs2HNMbQ)
  * :heavy_check_mark: Istio-Upstream [#[269]](https://paste.fedoraproject.org/paste/i-5Caiv1NMnVWHb3YKVYdA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1339, 1340]](https://paste.fedoraproject.org/paste/saE1EFTNICjV3QDZuAPaDQ)
  * :heavy_check_mark: install-bookinfo [#[756]](https://paste.fedoraproject.org/paste/KZwLjoF2oDKV0IHp1OBAJw)
  * :heavy_check_mark: Kiali-on-Openshift [#[764]](https://paste.fedoraproject.org/paste/8JWCcz2hQDt57h2S5HA-nA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[210]](https://paste.fedoraproject.org/paste/LfnUHtGW-mBr9fShIfW8Tw)


KIALI_NAME=kialiuipr703-istio-system

**Comment by jmazzitelli** [comment]
I dbl-click the mongo service triangle:

image

and I get an empty graph:

image

**Comment by jshaughn** [comment]
@jmazzitelli The mongo service is fixed, I had to change to source-side reporting as destination-side reporting was not setting the destination_service_name.

**Comment by jshaughn** [comment]
The travis build passed but git didn't get updated.

**Pull request merged**
