### PR TITLE
KIALI-1376 Update Workload list and Workload details with WorkloadHealth

### PR DESCRIPTION
**Pull request by aljesusg**
** Describe the change **

health_workload

** Issue reference **
[KIALI-1376](
https://issues.jboss.org/browse/KIALI-1376
)

### CODE REVIEW

**Comment by lucasponce** [comment]
Added DNM to fetch this PR locally and check.

**Comment by lucasponce** [comment]
UI comment:
image
Deployment, Label Validation, Health and Error Rate should have a uniform padding between elements.
Similar a Services has:
image

**Comment by aljesusg** [comment]
Ok @lucasponce I was thinking about keep all related with health in the right I'll change it. thanks

**Comment by lucasponce** [comment]
Another comment:
image
Workload list page should have a sorting feature per error rate and to define the rate of the metrics pulled.
Just as similar as Service page has.

**Comment by aljesusg** [comment]
workload
Comment addressed @lucasponce . Thanks

**Comment by lucasponce** [comment]
Thanks @aljesusg, sorry for my delay to review last changes.
I see a couple of things (I hope are just the last ones :)).
In the Workloads, the sorting by Error Rate seems to not work correctly:
Sorted Z->A:
image
Sorted A->Z:
image
It seems that field is not properly managed or something additional is happening. The expected is that the item with error rate could be sorted.

Another thing that I see today is a minor change of the fields in the Workload list.
For example:
image

On items with no Label Validation, the style is broken. Without enter in style, I would follow the Services setup, putting Health and Rate first and Label Validation at last position:
image

Then, fields will look similar in both pages.

Good change to move the type on the first column.

Thanks !

**Comment by aljesusg** [comment]
Fixed I forgot update the component after order. Thanks @lucasponce 
work

**Comment by aljesusg** [comment]
Thanks for the review @lucasponce

**Pull request merged**
