### PR TITLE
Expanded overview sparkline consolidation.

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Work with UX on increasing the density of information on expanded overview cards.

** Issue reference **
https://github.com/kiali/kiali/issues/2137
https://github.com/kiali/kiali-design/issues/167

** Screenshot **

Just a start:
Kiali_Console_-_Firefox_Developer_Edition

### CODE REVIEW

**Comment by jshaughn** [comment]
@mtho11 Is this PR still a thing?

**Comment by mtho11** [comment]
@jshaughn yep, still a thing :)

**Comment by mtho11** [comment]
@jshaughn I need to run this by UxD again, it kinda got forgotten.
CC: @beaumorley @lwrigh

**Comment by jshaughn** [comment]
@lucasponce @mtho11 @lwrigh We have so many small issues re: the Overview page/cards that I'm considering just  creating one new issue for a full UX pass of the page/cards and linking/closing the current issues.  We/UX could then prioritize the work when it makes sense.  None of them are currently on the sprint backlog and so we don't really need to do work here at the moment.

**Comment by lucasponce** [comment]
Note that also these pages are being modified and probably this work is outdated as there is a new table view in the overview page.

Overview cards are going to have actions and we are going to follow the standard patternfly recommendations on it (http://patternfly-react.surge.sh/documentation/react/components/card)

So, I suggest that when we have all these features consolidated perhaps we can review more minor/details UX aspects but as a whole task.

Also this review is something we could relaunch when we finish the main block of features planned for OSSM 1.2/2.0.

**Comment by mtho11** [comment]
I can close this one then since it has not been approved for any sprints.

**Pull request closed without merging**
