### PR TITLE
Implement spans list expanded mode

### PR DESCRIPTION
**Pull request by jotak**
- Adding a new Expandable component (avoiding patternfly's table expand which has some
  performance penalties)
- Implement a compact view for several cells of spans list
- Heatmap compact view

Fixes https://github.com/kiali/kiali/issues/3420

Screenshot:
Capture d’écran de 2020-11-17 16-59-48

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM

**Comment by hhovsepy** [comment]
Can the column widths stay the same after expanding? Because now the columns have different width before and after expand, It causes some visual discomfort in expanding.
Screenshot from 2020-11-18 10-38-19
Screenshot from 2020-11-18 10-38-33

**Comment by jotak** [comment]
@hhovsepy sure, can you retry? I've set percent-based cells width.

**Review by hhovsepy — APPROVED** [review]
Verified

**Comment by lucasponce** [comment]
It looks ok, I have a minor suggestion:

- The left alignment of "Duration" text is good.
- I wonder if you could make an easy try to see if putting the heatmap (both, mini and expanded) in the center of the cell would help into the visualization.

image

image

But otherwise it looks ok.

**Comment by jotak** [comment]
Problem with a mix of centered and left-aligned elements, is that it won't play well on wide screens, like this:

Capture d’écran de 2020-11-18 13-53-37

IIRC we had that kind of problems in the past and moved everything to being left-aligned. Also I think it's more a less a patternfly guideline, no? (not sure)

**Review by lucasponce — APPROVED** [review]

**Pull request merged**
