### PR TITLE
Enhance Health tooltip info

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/3197

There is not tooltip for HEALTHY status.

## Y-server Tooltip with configuration
tooltip_y_server
## Overview Y-server with configuration
Overview_y_server

##  Y-server Tooltip 
tooltip_y_server_no_conf
## Overview Y-server
no_config_y_server

### CODE REVIEW

**Comment by prachiyadav** [comment]
Screenshot from 2020-09-15 15-19-23

**Comment by prachiyadav** [comment]
Screenshot from 2020-09-15 15-19-07

**Review by prachiyadav — APPROVED** [review]

**Comment by aljesusg** [comment]
Wait @prachiyadav let me add something. In this screenshot

Screenshot from 2020-09-15 15-19-23

we shouldn't bee the traffic title if there is not traffic.

Can you try it again with the last commit ?

**Review by hhovsepy — APPROVED** [review]
Verified:
Screenshot from 2020-09-15 14-26-52

**Comment by lucasponce** [comment]
cc-ing @lwrigh as she suggested the change from UX meetings

**Review by lucasponce — APPROVED** [review]

**Comment by lwrigh** [comment]
It looks good to me! The only thing I notice is the blue icon has low contrast so you might want to change it to be lighter so there is higher contrast.

**Pull request merged**
