### PR TITLE
Better CSS fix for the ACE editor

### PR DESCRIPTION
**Pull request by lucasponce**
Fixes https://github.com/kiali/kiali-ui/pull/2154

Moved the fontSize from the ace builtint properties to the scss file.

### CODE REVIEW

**Comment by hhovsepy** [comment]
still facing the same issue, it disappears only when removing '!' before the important

**Comment by lucasponce** [comment]
I've seen that I have in my env some *.css that are ignored but may affect when building the global CSS.
I guess that can explain the mistery to not be able to reproduce from my side.

I'll investigate.

**Comment by lucasponce** [comment]
image

@hhovsepy would you be able to debug the styles that are being loaded in your test ?
Just to check which one is being applied.

**Comment by hhovsepy** [comment]
By first load I see 16px in style which is applied and is big:
Screenshot from 2021-05-17 19-29-34
But when size is not !important the 'element''s 12px is applied:
Screenshot from 2021-05-17 19-30-43

**Comment by lucasponce** [comment]
But the "host" links in the side panel should have also this style:
image

Are you having a different one in your test ?

**Comment by hhovsepy** [comment]
> Are you having a different one in your test ?
For the 'host' link there is not style applied:
Screenshot from 2021-05-18 09-14-09

**Comment by hhovsepy** [comment]
Screenshot from 2021-05-18 09-25-03

**Review by hhovsepy — APPROVED** [review]
Verified now.

**Review by prachiyadav — APPROVED** [review]

**Pull request merged**
