### PR TITLE
Patternfly minor bump

### PR DESCRIPTION
**Pull request by jotak**
Using the latest of 3.x branches

Fixes https://github.com/kiali/kiali/issues/3199

As usual with PF upgrades, special care must be taken for styles over the whole application.
I didn't notice any obvious change.

The bug it fixes is a bit annoying so I think we shouldn't skip this bump.

(PS: adding @mattmahoneyrh as reviewer for both teams are impacted)

### CODE REVIEW

**Review by lucasponce — APPROVED** [review]
LGTM
Tested locally in a global features tour: from overview to the Istio Config details pages.
No obvious regression to me.

But I won't merge until QE tests it as well.

**Review by aljesusg — APPROVED** [review]
lfgm

**Review by hhovsepy — APPROVED** [review]
Regression tested.

**Review by cfcosta — APPROVED** [review]

**Comment by lucasponce** [comment]
Thanks for all the reviews/tests, I think we can merge now.

**Pull request merged**
