### PR TITLE
KIALI-2535 Move TLS/LoadBalancer under Show Advanced Options

### PR DESCRIPTION
**Pull request by lucasponce**
** Describe the change **

https://issues.jboss.org/browse/KIALI-2535

image

image

### CODE REVIEW

**Comment by abonas** [comment]
while at it, maybe add the lock icon next to TLS? ;)

**Comment by abonas** [comment]
also, did you remove the "NONE" option from the TLS dropdown? it was part of the issues that led to this change

**Comment by lucasponce** [comment]
> while at it, maybe add the lock icon next to TLS? ;)

What pattern here,
TLS <icon> or <icon> TLS, or TLS <dropdown> <icon> ?

**Comment by lucasponce** [comment]
> also, did you remove the "NONE" option from the TLS dropdown? it was part of the issues that led to this change

Ok, that means that we will populate always these values, but I guess that's not bad. I'll use the default values for both cases (TLS and LB).

**Comment by abonas** [comment]
> What pattern here,
> TLS or TLS, or TLS ?

sorry, don't understand the above

**Comment by abonas** [comment]
> Ok, that means that we will populate always these values, but I guess that's not bad. I'll use the default values for both cases (TLS and LB).

only if user selected something in the dropdown, no?

**Comment by hhovsepy** [comment]
Verified.

**Comment by lucasponce** [comment]
I'm going to address in a next commit a couple of comments discussed in the PR.

**Comment by lucasponce** [comment]
image

NONE value removed from Dropdowns.
Lock icon added to TLS label.
TLS value is pre-selected depending if mTLS is defined global wide, otherwise is selected DISABLED.

image

Only tls and loadbalancer are added into final DR object when user modifies or Istio_Mutual is enabled.

**Comment by abonas** [comment]
this is a huge improvement. I have one last suggestion, not sure if it's even possible - to increase the font of the words of "Advanced options" - they look small on their own, and even smaller because right below them there are some words in capital letters

**Comment by lucasponce** [comment]
image

**Comment by abonas** [comment]
EXCELLENT!

**Comment by lucasponce** [comment]
@aljesusg @hhovsepy I've sent a couple of commits after your review; if you'd like to give a final look, to check everything is fine, we can - then - merge this one.
Thx

**Comment by hhovsepy** [comment]
Verified it in a pair with https://github.com/kiali/kiali/pull/909
Screenshot from 2019-03-12 14-27-55

**Pull request merged**
