### PR TITLE
KIALI-1587 Jaeger link tries to open popup

### PR DESCRIPTION
**Pull request by aljesusg**
** Describe the change **

Now we can see the url services in the status after the merge of https://github.com/kiali/kiali/pull/573 . /api/status provide us of the urls and versions now. So we only need to check one time to get all the urls
status

When the jaeger url is empty we have not menu item in the navigation
without jaeger url

behaviour in Firefox with https popup, now we have not warning message.
firefox_behaviour_jaeger_popup

** Issue reference **
[KIALI-1587](
https://issues.jboss.org/browse/KIALI-1587)

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#229](https://paste.fedoraproject.org/paste/rQBhLlx6iwlQ4QotcBd5JQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1662]](https://paste.fedoraproject.org/paste/OqDokOCntnLEaDE5CnLpFw)
  * :heavy_check_mark: Istio-Upstream [#[507]](https://paste.fedoraproject.org/paste/Vi~53LUZlZDqtYcP2tFO~g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1896, 1895]](https://paste.fedoraproject.org/paste/VVS51V-s42Od~oZCstsiiw)
  * :heavy_check_mark: install-bookinfo [#[1037]](https://paste.fedoraproject.org/paste/qruCpt6T7HvK3Rrw0e72vw)
  * :heavy_check_mark: Kiali-on-Openshift [#[1056]](https://paste.fedoraproject.org/paste/WPLx7cX7iXKKexQdnLt~cA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[462]](https://paste.fedoraproject.org/paste/8lCybBcMjfs07Z7YWRTu3w)


KIALI_NAME=kialiuipr760-istio-system

**Comment by aljesusg** [comment]
Moved Fetch Grafana Info to redux, now we only make one request instead of fetch the grafanainfo each time we go to service/metrics and click to the link when the information not change.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#230](https://paste.fedoraproject.org/paste/EaPJ3DF3WeNl9YhQc6bwaw)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1663]](https://paste.fedoraproject.org/paste/my9TY6SPVRoYmoVIY5CDew)
  * :heavy_check_mark: Istio-Upstream [#[508]](https://paste.fedoraproject.org/paste/PgCF08ymYzIF96Sm~qOOoA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1897, 1898]](https://paste.fedoraproject.org/paste/Tov168JPyUG7qJztwdXt3w)
  * :heavy_check_mark: install-bookinfo [#[1038]](https://paste.fedoraproject.org/paste/KeQEP9D-uxCQVkJN6NiTJw)
  * :heavy_check_mark: Kiali-on-Openshift [#[1057]](https://paste.fedoraproject.org/paste/qfKstLOY~akTabBCVasNWQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[463]](https://paste.fedoraproject.org/paste/Z6nAwFiF1LU49dcMkXGjSA)


KIALI_NAME=kialiuipr760-istio-system

**Comment by jotak** [comment]
Good change, I just wonder if there is really an interest to use all the redux machinery since it's something going to be static / defined once for all? (I mean, compared to a simple global / static access)

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#231](https://paste.fedoraproject.org/paste/WAvYcwK~ORYcVkTgjuSeYw)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1664]](https://paste.fedoraproject.org/paste/l3MYNzDMDWp0RiJAZHvFNw)
  * :heavy_check_mark: Istio-Upstream [#[509]](https://paste.fedoraproject.org/paste/yY9yI1TFbHbqPHSIdxA33w)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1899, 1900]](https://paste.fedoraproject.org/paste/CR13rxZPHERx9ilZqnPmHQ)
  * :heavy_check_mark: install-bookinfo [#[1039]](https://paste.fedoraproject.org/paste/b8bYalluvA3x8FcKBFScog)
  * :heavy_check_mark: Kiali-on-Openshift [#[1058]](https://paste.fedoraproject.org/paste/lkIYQlfH9-npVtou3ap2Tw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[464]](https://paste.fedoraproject.org/paste/GBiGGvpbw7s-bWMl7NGrGw)


KIALI_NAME=kialiuipr760-istio-system

**Comment by aljesusg** [comment]
I think that with this we avoid fetch the sameinfo each time we go to services (componentdidmount). This fetch is only called when user login in the app.

**Comment by jotak** [comment]
@aljesusg yes I understand the goal of this task, but I mean, the same result could be achieved without redux: just triggering this grafana info query on login, stored in a globally accessible variable.
No worries, LGTM anyway

**Pull request merged**
