### PR TITLE
KIALI-1878 Overview: allow to switch to workloads health

### PR DESCRIPTION
**Pull request by jotak**
- Add switch between app-based health and workload-based health
- In toolbar, some perf enhancements as refresh is not needed in every component change, and prevents unnecessary change checks & state updates (less renders)
- Remove unused function setActiveNamespace

JIRA: https://issues.jboss.org/browse/KIALI-1878

Screenshoft:
overview

### CODE REVIEW

**Comment by jotak** [comment]
PS: tell me if you think there's a better label name than "Health Type" to show

**Comment by jotak** [comment]
> > PS: tell me if you think there's a better label name than "Health Type" to show
> 
> "Show health for" would be perhaps more clear.
> Maybe also consider aligning this with the switcher on the graph that also switch between different entity types? only if it will make sense :)

If you're thinking about the "Graph Type" switch, this is what I based on this change already (and it's why I named it "Health Type" as an equivalent of "Graph Type" , but I agree "Show health for" is more meaningful). But it doesn't make sense to show "versionned app" here, it's only Apps or Workloads.

> For future PRs I recommend to split enhancements/removal of unused code to either separate PRs or at least separate commits.

I can only partly agree ... I could have split the PR for the small perf enhancements, I agree. But very little changes (such as removing unused variables in the file that we're editing in) doesn't need extra PR IMO, as it would be a lot of noise (new JIRA, notifications flood etc.) for very little thing - slowing down processes / triage / etc. Which in the end would encourage NOT to fix little things I fear.

**Comment by abonas** [comment]
> > > PS: tell me if you think there's a better label name than "Health Type" to show
> > 
> > 
> > "Show health for" would be perhaps more clear.
> > Maybe also consider aligning this with the switcher on the graph that also switch between different entity types? only if it will make sense :)
> 
> If you're thinking about the "Graph Type" switch, this is what I based on this change already (and it's why I named it "Health Type" as an equivalent of "Graph Type" , but I agree "Show health for" is more meaningful). But it doesn't make sense to show "versionned app" here, it's only Apps or Workloads.

Yes, I'm not suggesting to add versionned apps here, but rather only look at a similar control at the graph page "for inspiration". But if "Show health for" sounds good, go for it :)
> 
> > For future PRs I recommend to split enhancements/removal of unused code to either separate PRs or at least separate commits.
> 
> I can only partly agree ... I could have split the PR for the small perf enhancements, I agree. But very little changes (such as removing unused variables in the file that we're editing in) doesn't need extra PR IMO, as it would be a lot of noise (new JIRA, notifications flood etc.) for very little thing - slowing down processes / triage / etc. Which in the end would encourage NOT to fix little things I fear.

The idea is absolutely *not* to increase the noise and extra work with extra JIRAs. some PRs can hold minor changes without JIRA. But I also mentioned an option of separate commits where those commits are stacked one on another and are part of the same PR. After PR is merged, it has no meaning and no visibility in git history. So when someone looking at the code and using git history, they will gain more clarity per every commit if every commit has a single purpose rather than "why the commit that adds functionality X also does Y? was that change necessary for the feature or just a cleanup?"

**Comment by lucasponce** [comment]
> The idea is absolutely not to increase the noise and extra work with extra JIRAs. some PRs can hold minor changes without JIRA. But I also mentioned an option of separate commits where those commits are stacked one on another and are part of the same PR. After PR is merged, it has no meaning and no visibility in git history. So when someone looking at the code and using git history, they will gain more clarity per every commit if every commit has a single purpose rather than "why the commit that adds functionality X also does Y? was that change necessary for the feature or just a cleanup?"

A comment in the commit message should be enough.
I.e. we force to re-arrange a PR when adding a new library dependencies.

For the problem commented here, just adding a comment is how the project is being doing.

**Comment by hhovsepy** [comment]
The link to Workloads filter by Health is referenced to Applications.
screenshot from 2018-11-12 11-35-40

**Comment by jotak** [comment]
@hhovsepy ah you're right, I've only changed one link, I forgot this one... good catch, thanks!

**Comment by jotak** [comment]
@abonas @hhovsepy fixed:

updated

**Comment by hhovsepy** [comment]
Verified 
kiali-ui 0.11.0 (3ae65df1eccca44cb0ff8ecee8626a212fa5dce3)
kiali v0.11.0-SNAPSHOT (12af09a47f5335f0f06c1a8bbf1f5f99ade962e9)

**Comment by xeviknal** [comment]
Code reviewed and tested in my local env :)

**Pull request merged**
