### PR TITLE
Adjust size of subsets column in DR table

### PR DESCRIPTION
**Pull request by lucasponce**
image

Fixes kiali/kiali#1905

### CODE REVIEW

**Comment by hhovsepy** [comment]
It works fine on Chrome, but fails on FF:
Screenshot from 2019-11-15 09-27-55

**Comment by lucasponce** [comment]
Interesting.
Will check.

**Comment by lucasponce** [comment]
Well, the issue was there, it looks like there is something weird in FF for this scenario.
It's unrelated to this PR, but I'm going to see if there could be an easy workaround.

**Comment by lucasponce** [comment]
@hhovsepy changed

**Pull request merged**
