### PR TITLE
KIALI-491: Display rate interval for the service page

### PR DESCRIPTION
**Pull request by israel-hdez**
image

### CODE REVIEW

**Comment by abonas** [comment]
Something confuses me here (it might be completely my own misunderstanding and also unrelated to this particular PR)
1. Displaying rate interval means to me read only.
The above screenshot suggests that users *control* the rate interval.

2. the rate interval term itself - does this mean "refresh frequency of the UI vs server"? "refresh interval in which data is fetched by Kiali from Istio"? another third option? perhaps the term is not 100% accurate here

**Comment by israel-hdez** [comment]
@abonas "Rate interval" is for the error rate percentage. If you choose "Last 10 minutes" the error rate for the last 10 minutes will be calculated and shown in the list. 

So, for example, if a service receives lots of requests but there were a high number of errors in the last few minutes, selecting "Last 30 minutes" may show a lower error rate compared to the error rate of the "Last 5 minutes".

Perhaps instead of "Rate interval" I could change the label to "Error rate for".... Or perhaps I'm misusing the _rate_ word.

**Comment by cfcosta** [comment]
I think "Rate Interval" is ok enough, maybe "Error rate interval"?

**Comment by jotak** [comment]
Technically, the "rate interval" is what is passed to prometheus `rate()` / `irate()` function, like the `5m`  described here: https://prometheus.io/docs/prometheus/latest/querying/functions/#rate(), which if I'm correct stands for "rolling rate computed over interval [N-5 minutes, N]". Since in this case I guess we fetch only the latest datapoint, it's really the last 5 minutes from now - but in the metrics screen it has to be distinguished with the observed duration which is in general bigger than the rate interval.

**Pull request merged**
