### PR TITLE
KIALI-2872 Adjust focus animation

### PR DESCRIPTION
**Pull request by josejulio**
** Describe the change **

Adjust focus animation.

It takes 2 seconds and the first circle in takes 1s, the out half a second and the second "in" the other half second.

I could do something different, please comment what you have in mind.

** Screenshot **

Before:
focus-animation-17

After:

a)
focus-animation-16

b)
focus-animation-15

c) same as (a) but with color PfColors.Blue300

focus-animation-18

### CODE REVIEW

**Comment by mtho11** [comment]
Can you also add the before screenshot so we can compare?

**Comment by josejulio** [comment]
> Can you also add the before screenshot so we can compare?

I added some, but the quality of my recording is not really good.

**Comment by jmazzitelli** [comment]
I like (a) better. The red obviously won't help color blind people - red is also the color of "ERROR! Something is wrong here!!".

**Comment by josejulio** [comment]
Current code uses option (a).

**Comment by mtho11** [comment]
Personally, I kinda like option b.

**Comment by jshaughn** [comment]
@josejulio option a or b are both fine to me, although in both cases I think I'd prefer the same color as is used for a selected node.  The problem there is that the color differs depending on health.  If we had to settle on one color I'd go with the non-degraded select color (PfColors.Blue300), or just black.

**Comment by josejulio** [comment]
Health is fetched dynamically, so i don't think we can use the health color for this.

**Comment by josejulio** [comment]
> PfColors.Blue300

With that color it looks like this:
focus-animation-18

**Comment by abonas** [comment]
not with red please.
cc @serenamarie125 fyi

**Comment by josejulio** [comment]
Current code has the PfColors.Blue300
I think we can iterate further if UXD proposes something else

**Pull request merged**
