### PR TITLE
[KIALI-170]Iframe with Jaeger

### PR DESCRIPTION
**Pull request by aljesusg**
This is a PR with a Embed Jaeger while  we continue the research.

Task : [KIALI-170](https://issues.jboss.org/browse/KIALI-170)
jaeger_embed

### CODE REVIEW

**Comment by objectiser** [comment]
@aljesusg Looks good :+1:

**Comment by theute** [comment]
I'm fine with that approach now (not much technical debt), but I would put "Distributed Tracing" or just "Tracing" if too long in the menu rather than "Jaeger".

**Comment by abonas** [comment]
I think this looks excellent! (considering technical issues and an understandable gap in look and feel)

**Comment by aljesusg** [comment]
Thanks @abonas @theute next is how we wanna the menu.
The icon I set a paw because jaeger Logo it seems is looking paws ^^
jaeger logo

With **Distributed Tracing**

Unselected
unselected_jaeger

Selected
selected_jaeger

With **Tracing**
tracing

**Comment by theute** [comment]
Let's go with "Distributed Tracing" then, thanks 1

**Comment by aljesusg** [comment]
You're welcome. Changed

**Pull request merged**
