### PR TITLE
Ignore .css.map files from git

### PR DESCRIPTION
**Pull request by xeviknal**
do you think this is a good idea?
Perhaps I am not using project properly, but I found myself committing one .css.map file.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
I'm not sure of a best practice, but mostly I've seen the map files get ignored.

**Comment by lucasponce** [comment]
I don't see an explicit ignore line on https://github.com/openshift/console but in the code there is not any .map file.

**Comment by xeviknal** [comment]
It doesn't sound natural to me the fact of debugging into production environment.

**Comment by xeviknal** [comment]
@mtho11 glad that we had this conversation! thx!

**Pull request merged**
