### PR TITLE
TrafficControl Frame, min/max RatioStatistics, use TrafficShifting

### PR DESCRIPTION
**Pull request by jadeyliu939**
Improve on the Changes request from [PR#2015](https://github.com/kiali/kiali-ui/pull/2015) 

a)  Add Traffic Control Frame in Experiment Detail page 
> 1.  **_Using Kiali pattern for showing match rules_**
> 2. **_Fix the tab issue for TrafficControl Frame_**

b)  Add Min/Max credible interval in Experiment Assessment tab when the values are available. also add Legend for the assessment chart

c)  Using TrafficShifting Components in Terminate Experiment request

Note: has dependency on PR https://github.com/kiali/kiali/pull/3475

**Screenshot**

a) Traffic Control 
Screen Shot 2020-12-03 at 1 32 35 PM

b) Min/Max Credible Internal 
Screen Shot 2020-12-03 at 1 33 41 PM

c) TrafficShifting 
Screen Shot 2020-12-03 at 1 37 17 PM

### CODE REVIEW

**Comment by lucasponce** [comment]
I'm having some problems testing this.

When I tried to create a simple traffic control rule like this:
image

I get this error:
image

**Comment by lucasponce** [comment]
Note, I'm testing with iter8 installed in this way:

```
ITER8_VERSION="v1.0.0-rc3"

echo "===== Installing Iter8 ${ITER8_VERSION} ======"

echo "===== Installing iter8-analytics ====="
kubectl apply -f https://raw.githubusercontent.com/iter8-tools/iter8-analytics/${ITER8_VERSION}/install/kubernetes/iter8-analytics.yaml

echo "===== Installing iter8-control - Telemetry v2 ====="
kubectl apply -f https://raw.githubusercontent.com/iter8-tools/iter8-controller/${ITER8_VERSION}/install/iter8-controller-telemetry-v2-17.yaml
```

**Comment by jadeyliu939** [comment]
This appears to be incompatible issues with earlier release of Iter8, I will look into the backward incompatible problem.

**Comment by lucasponce** [comment]
> This appears to be incompatible issues with earlier release of Iter8, I will look into the backward incompatible problem.

I'm fine if we document that kiali 1.28.x needs iter8 v1.0.0 instead of rc3.

For scenarios like this I don't have problem to ask for a new version of the extension, but you decide here.

**Review by lucasponce — APPROVED** [review]

**Comment by lucasponce** [comment]
Now that Iter8 extension is consolidating in master I'm going to update the Epics to review some of the UI patterns used.

There are some areas that are diverging of the other Kiali forms and worth to refactor them to align.

So, this is a followup task for me, for next Sprint, to review it and prepare the subtasks for this.

**Pull request merged**
