### PR TITLE
Add links from Graph side panel validation status to istio config list

### PR DESCRIPTION
**Pull request by xeviknal**
fixes https://github.com/kiali/kiali/issues/2218

### CODE REVIEW

**Review by hhovsepy — COMMENTED** [review]
Tested the cases:
1. One WARN only.
2. One Error Only.
3. Many WARN and Errors.
4. One Error and many Warnings.
In all cases are OK.

Only difference with the initial issue is that Filters are not applied:
Screenshot from 2021-02-25 17-44-09

**Comment by xeviknal** [comment]
@hhovsepy I've have added the filters into the links pointing to the istio config list.
1) When there are only errors, it filters by errors.
2) when there  are only warning, it filters by warnings.
3) when there are both, it filters by both warnings and errors.

WRT to linking to one specific istio config, I understood to not implementing it by comment in the issue. This would add more work in the endpoints side. So far, we don't know how many objects have errors/warnings. We know how many validations (one object may have multiple ones). I am okay to modify the backend though topping this extra info.

On the other hand, I've standarized the links. This behavior should not only be in the graph validation link but in overview too.

Finally, there was a bug in the validations icon in the istio config list and service details page:

Screenshot of Kiali (5)

Screenshot of Kiali (6)

Thank you!

**Review by jshaughn — APPROVED** [review]
@xeviknal You should yell at me if I don't respond to a review request after 24 hours!  I am sorry, I missed this.  Graph-related changes look fine to me, tested and working.

**Comment by hhovsepy** [comment]
It seems the link from graph is not constantly putting the correct filters.

**Comment by hhovsepy** [comment]
When clicking to namespace icon in graph and then going back to graph page several time with selecting different namespaces, the link from icon does not set filters anymore.

**Comment by jshaughn** [comment]
> When clicking to namespace icon in graph and then going back to graph page several time with selecting different namespaces, the link from icon does not set filters anymore.

I tested this and for me it seemed to work, but I defer to @hhovsepy.  Do you have a reproducible pattern?

**Comment by xeviknal** [comment]
I am working with this. I found a couple of inconsistencies. I'll update this PR soon :) Thanks jay!

**Comment by xeviknal** [comment]
I can see what happens now. The filters in the istio config list don't prioritize the ones in the URL. It always takes the ones set in the state.

To reproduce:
1. Click a link the graph
2. Remove the filter (or add one more)
3. Go back to the graph and click the same link
4. The filters don't appear anymore (or both appears even if only one is intended)

It looks like this is a bug in the StatefulFilters. I'll give it a quick look now.

**Comment by xeviknal** [comment]
@jshaughn @hhovsepy I've found what was the problem. I am resetting filters before sending people to the istio config list. This way, the param filters will have priority.

Let me know!

**Review by hhovsepy — APPROVED** [review]
Verified now.

**Pull request merged**
