### PR TITLE
Add new tslint rule: 'no-literal-string' to clean up type-safe issues…

### PR DESCRIPTION
**Pull request by mtho11**
…. Disallows obj["property"] (which has no type safety) in favor of obj.property. We are totally bypassing Typescript's type-safety here.

WDYT? This open to the team to comment.

### CODE REVIEW

**Comment by jotak** [comment]
Sounds good to me, and improves type safety.

**Comment by israel-hdez** [comment]
+1 :+1: 
I've seen those literal strings and wanting to get rid of them.

**Comment by lucasponce** [comment]
+1
Worth to fetch locally and check regressions once the PR is ready, but it sounds good.

**Comment by lucasponce** [comment]
I think we need a different strategy for these kind of PRs where we are applying some lint or similar recommendation.

We need to define a "time window" where author and reviewers can be focus on it more synchronous to review/discuss/merge-reject at same time.

If not, I'm afraid that other changes may outdate this work pretty fast, even as it happens here, it seems a good idea.

**Comment by jotak** [comment]
yes ... BTW @mtho11 why did you add the DNM label?
If you rebase & fix, I can review in priority

**Comment by mtho11** [comment]
@jotak there is actually a fair bit more refactoring I was not counting on ;)

```
index.js:2178 /Users/mithomps/projects/kiali-ui/src/components/SummaryPanel/ResponseTable.tsx
(50,28): Property 'key' does not exist on type 'Object'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
handleErrors @ webpackHotDevClient.js:178
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2178 /Users/mithomps/projects/kiali-ui/src/components/SummaryPanel/ResponseTable.tsx
(51,26): Property 'code' does not exist on type 'Object'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
handleErrors @ webpackHotDevClient.js:178
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2178 /Users/mithomps/projects/kiali-ui/src/components/SummaryPanel/ResponseTable.tsx
(52,46): Property 'flags' does not exist on type 'Object'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
handleErrors @ webpackHotDevClient.js:178
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2178 /Users/mithomps/projects/kiali-ui/src/components/SummaryPanel/ResponseTable.tsx
(52,59): Property 'flags' does not exist on type 'Object'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
handleErrors @ webpackHotDevClient.js:178
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2178 /Users/mithomps/projects/kiali-ui/src/components/SummaryPanel/ResponseTable.tsx
(53,26): Property 'val' does not exist on type 'Object'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
handleErrors @ webpackHotDevClient.js:178
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2178 /Users/mithomps/projects/kiali-ui/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
(87,34): Property 'editor' does not exist on type 'AceEditor'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
handleErrors @ webpackHotDevClient.js:178
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2178 /Users/mithomps/projects/kiali-ui/src/services/Api.ts
(115,12): Property 'validate' does not exist on type '{ objects: string; } | { objects?: undefined; }'.
  Property 'validate' does not exist on type '{ objects: string; }'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
handleErrors @ webpackHotDevClient.js:178
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/react-dev-utils/node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
index.js:2178 /Users/mithomps/projects/kiali-ui/src/services/Api.ts
(381,12): Property 'validate' does not exist on type '{}'.
```

**Comment by mtho11** [comment]
@jshaughn do you mind looking at the `ResponseTable` stuff here; much of that is due to `export type Responses = Object;`

**Comment by jshaughn** [comment]
@mtho11 Same mistake I had in the other code.  I'll create a PR against this branch that changes from Object to object.

**Comment by mtho11** [comment]
@jshaughn also you can use typescript `ReadOnly` in place of `Object.freeze`:
```
type Foo = {
  bar: number;
  bas: number;
}

type FooReadonly = Readonly<Foo>; 
```
https://basarat.gitbooks.io/typescript/docs/types/readonly.html

**Comment by lucasponce** [comment]
@hhovsepy I added you as reviewer on this PR.
It's pure code refactoring, if you could perform a quick regression check we can merge it and consolidate to avoid @mtho11 is blocked on it as it touches several different files.
Thanks

**Pull request merged**
