### PR TITLE
Metrics page: don't show labels with a single value in legend

### PR DESCRIPTION
**Pull request by jotak**
Add tests on TimeSeriesUtil

Fixes https://github.com/kiali/kiali/issues/3659

### CODE REVIEW

**Review by hhovsepy — APPROVED** [review]
Verified, no regression:
Screenshot from 2021-02-01 18-55-20
Screenshot from 2021-02-01 18-57-48

**Comment by hhovsepy** [comment]
One version case is fixed:
Screenshot from 2021-02-01 19-03-34

**Review by jshaughn — APPROVED** [review]
LGTM, and if for some reason a user does want to see it, they still can.

**Comment by jotak** [comment]
Thanks!

**Pull request merged**
