### PR TITLE
Add Auto-Refresh on Overview/Traffic tabs

### PR DESCRIPTION
**Pull request by lucasponce**
Fixes https://github.com/kiali/kiali/issues/3163

Now all tabs with health/traffic info that may change during time are aligned and they enable auto-refresh.

cc @jshaughn I touched a minor detail in TrafficDetails.tsx which are being modified in your PR, but I hope it's minor and you could rebase without problem.

### CODE REVIEW

**Comment by lucasponce** [comment]
It's not a bug but I guess v1.24 branch would benefit of this one.

**Review by skondkar — APPROVED** [review]
Verified on Kiali UI : 1.25.0 (0a9388f224eea87b7916f402256c990c48e5ee76)
Verified auto-refresh on overview and traffic tabs of applications/workloads/service details pages.
LGTM.

**Comment by jshaughn** [comment]
> It's not a bug but I guess v1.24 branch would benefit of this one.

I think we should respect the code freeze and backport only bug fixes.

**Comment by lucasponce** [comment]
> I think we should respect the code freeze and backport only bug fixes.

Some minor enhancements may go specially in the context we are, but I'm fine with no backporting this.

**Pull request merged**
