### PR TITLE
KIALI-3145 Migrate the graph filter toolbar to PF4.

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Migrate the graph filter toolbar to PF4.

- [x] Migrate from PF3 to PF4
- [ ] Make ToolbarDropdown PF4 compliant
- [ ] Fix styling for PF4 to match PF3 Kiali

### CODE REVIEW

**Comment by abonas** [comment]
@aljesusg making sure you're synced on this effort

**Comment by mtho11** [comment]
@abonas yes, @aljesusg and I discussed last week.

**Comment by aljesusg** [comment]
yes @abonas we talked :)

**Comment by jshaughn** [comment]
When applying the UX changes ensure that the toolbar does not wrap on lower res (I think it was 1280x1024 that we targeted but verify with @jmazzitelli).

**Comment by mtho11** [comment]
@jshaughn, yep remember I did all the small screen testing jiras.

**Comment by aljesusg** [comment]
Hi @mtho11 I am working in https://issues.jboss.org/browse/KIALI-2735, there are some components in the overviewpage toolbar like refresh or toolbar that are used in graph view, lits, details... I am working in them I'll ping you with the first draft

**Comment by mtho11** [comment]
Closed via https://github.com/kiali/kiali-ui/pull/1389

**Pull request closed without merging**
