### PR TITLE
KIALI-936 Enhance metrics page

### PR DESCRIPTION
**Pull request by jotak**
JIRA: https://issues.jboss.org/browse/KIALI-936
Needs backend PR https://github.com/kiali/kiali/pull/514 in order to work.

- Consume new REST api for quantiles
- Add new url params for metrics options (and centralize declaration of URL parameters)
- Use enums for metrics object types and in/out direction
- Use the new Refresh component in Metrics, delegating management of polling job
- C3 Charts: need to tell explicitely which series to unload
- Add quantile 0.999 (hence rename percentile => quantile)

Screenshot:
screenshot

### CODE REVIEW

**Comment by jotak** [comment]
Adding DNM to coordinate with backend PR...

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#103](https://paste.fedoraproject.org/paste/aE09I7a8sIHtLFQEoW0kWw)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1372]](https://paste.fedoraproject.org/paste/~iD0B2Nv4iM4p314hfqAnA)
  * :heavy_check_mark: Istio-Upstream [#[248]](https://paste.fedoraproject.org/paste/0UbEuu46zWqkCyGSBDG8gg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1289, 1290]](https://paste.fedoraproject.org/paste/~u5J1fLVR-m08GPjGthYZw)
  * :heavy_check_mark: install-bookinfo [#[731]](https://paste.fedoraproject.org/paste/FptOY-cTzvBU~TzQLUWxpA)
  * :heavy_check_mark: Kiali-on-Openshift [#[742]](https://paste.fedoraproject.org/paste/~Gu~FFCwKUREie5d40F4HQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[189]](https://paste.fedoraproject.org/paste/8s4fWKnHRhNxUZ5n48EydA)


KIALI_NAME=kialiuipr701-istio-system

**Comment by israel-hdez** [comment]
Is the backend code ready?
UI code looks ok, but I would like to try it.

**Comment by jotak** [comment]
@israel-hdez that's right, it's an issue. I think I'll change the default server-side to 'empty', that will avoid to do some tricks with additional parameters or special values to handle the no-value case.

**Comment by israel-hdez** [comment]
@jotak I just had a lightbulb moment:
Looks like it's possible to disable all checkboxes of the "Histograms". So, this allows them to be blank.
This is not a blocker. It's only a comment that I thought was worth to point.

**Comment by jotak** [comment]
@israel-hdez , not sure to understand your last comment, what do you mean by "disable all checkboxes" ? Uncheck them?
I addressed your initial remark on the backend side, now default quantiles == empty, so that's consistent.

**Comment by jotak** [comment]
@israel-hdez I'm merging but let me know if something can still be improved

**Comment by israel-hdez** [comment]
@jotak Yes, I meant unchecking all them, leading to the histograms being blank. 
It's only a comment. Behavior is ok. It's just that it may be a little misleading, since UI doesn't tell which ones are histograms, it's a little weird to see some charts with data and some other without data.
I don't have a problem to keep the UI as it is. Perhaps the "in-app" documentation could mention that.

**Pull request merged**
