### PR TITLE
Implement UXD changes for the graph

### PR DESCRIPTION
**Pull request by josejulio**
** Describe the change **
Implements the UXD changes suggested in https://marvelapp.com/41jgfd4/screen/59366802

This still depends on unpublished changes on cytoscape and my fork: https://github.com/josejulio/cytoscape-node-html-label (which is still unpublished)

** Issue reference **
https://github.com/kiali/kiali/issues/1418

** Screenshot **

Peek 2019-08-27 17-17

### CODE REVIEW

**Comment by josejulio** [comment]
@serenamarie125 could you take a look at the GIF and comment?
I haven't tried to modify the group boxes, but most likely they can't be changed.

**Comment by josejulio** [comment]
Pushed a docker image to `josejuliomartinez/kiali:PR-1385` in case someone wants to test.
// cc @mwringe

**Comment by abonas** [comment]
@josejulio @mwringe if this needs UX feedback, was it added to UX meeting agenda?

**Comment by josejulio** [comment]
> @josejulio @mwringe if this needs UX feedback, was it added to UX meeting agenda?

I don't think that this was added, I'll check that, thanks.

**Comment by jshaughn** [comment]
@josejulio In the UX mock the background is a shade of gray and app box backgrounds are white, but in your video (and our current impl) it is reversed.  You may need to make that change.

**Comment by abonas** [comment]
@josejulio was it eventually discussed in UX meeting? if not, please see if it's possible this week

**Comment by josejulio** [comment]
> @josejulio was it eventually discussed in UX meeting? if not, please see if it's possible this week

There haven't been an UX meeting since i added this to the agenda, I hope to be able to work it out this week.

**Comment by serenamarie125** [comment]
Agreed - the page background should be grey to remain consistent with PF4 topology.  This is looking great, nice work!

**Comment by serenamarie125** [comment]
FWIW if the dashboard page background is all grey ( rather than just a strip ), it will also provide some consistency when switching between graphical views!

**Comment by josejulio** [comment]
Grey background is being done here: https://github.com/kiali/kiali-ui/pull/1431
I'll update the background of the nodes to white.

**Comment by josejulio** [comment]
Squashed and rebased, this is ready for a review.

**Comment by jshaughn** [comment]
When trying to run this with yarn start and render the graph, I immediately get:

TypeError: Invalid attempt to spread non-iterable instance

at CytoscapeGraph.tsx:394:   let newBE = [...oldBE];

Is there something I need to do, or check?  I did run 'yarn' after pulling the PR.  Perhaps rebase with master and update the PR and I can try again.

**Comment by josejulio** [comment]
> at CytoscapeGraph.tsx:394: let newBE = [...oldBE];

Not really sure why you are hitting this issue, oldBE should be an array, it looks like it is not in your case. I added a small patch that should fix your issue. If not, please share the browser/OS that you are using.

**Comment by jshaughn** [comment]
@josejulio There seems to be something more fundamental going on, I crashed out again.  Perhaps I have an environmental issue.  I'll contact you directly.

**Comment by josejulio** [comment]
> * The legend needs to be updated to match the edge styling

Ok, going to update the legend

> * The labels no longer respond to hover (maybe this is expected, but it is different)

This is expected. I tried some code to make them work, but didn't work well and made things less stable.

> * The background images are still clipped in the service triangles, perhaps they can be repositioned?

I'll check

> * Sometimes there is noticeable lag for the hover "emphasis" effect to enable/disable

Probably related to https://github.com/kiali/kiali/issues/1725 and running in dev mode (yarn start)

> * The background is white, not grey (I think this is being done in another PR)

Correct

> * The nodes do not have rounded edges (I think this is a known technical limitation)

Waiting for [cytoscape 3.11.0](https://github.com/cytoscape/cytoscape.js/milestone/180?closed=1). In that version we have rounded versions of the shapes we use.

**Comment by jshaughn** [comment]
@josejulio OK, if you can update the legend and fix the background images for service nodes, that would cover my questions/change-requests.

**Comment by josejulio** [comment]
Adding do not merge tag, as we are expecting a patch release with a fix we need.

**Comment by jshaughn** [comment]
@josejulio The legend looks correct and the background images are fitting the triangles.  For me it's good to merge, even with the slow-ness due to the console logging issue.  But if you want to wait for the cy release that is OK, as long as it happens fairly soon.  We do need the grey background, i'm not sure why that's in a separate PR, but without it the default node edges are too light, they look like dead nodes.  Also, I really don't like the unused node edges, they are hard to distinguish from a normal node.  But we can wait for the correct background and then evaluate.  Good Job!

**Comment by jshaughn** [comment]
One thing I noticed today, I wonder whether UX wants us to update some of our colors given the PF4 color scheme: https://www.patternfly.org/v4/design-guidelines/styles/colors.  @serenamarie125 , any idea whether the graph edges, node borders, need to be tweaked?

**Comment by mtho11** [comment]
@mattmahoneyrh your question might be better addressed in kiali-design repo where our UxD people can properly address.

**Comment by mattmahoneyrh** [comment]
@mto11 per your suggestion: https://github.com/kiali/kiali-design/issues/147

**Pull request merged**
