### PR TITLE
KIALI-1784 add mTLS edge badge to legend

### PR DESCRIPTION
**Pull request by jshaughn**
image

### CODE REVIEW

**Comment by jshaughn** [comment]
@jmazzitelli This should be an easy one to review but if you want to wait for @pilhuhn to return that's fine too.

**Comment by abonas** [comment]
LGTM (the look, did not review the code)
btw with which tool do you edit SVG?

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#303](https://paste.fedoraproject.org/paste/H0MDotMChhNzC712WPHllw)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1886]](https://paste.fedoraproject.org/paste/Yus-X4CZTls45TFzI5rSiA)
  * :heavy_check_mark: Istio-Upstream [#[732]](https://paste.fedoraproject.org/paste/kXi34vaCmdY0De08u1KQGw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2308, 2309]](https://paste.fedoraproject.org/paste/kfH~GwtwN-kmlyNaaX~pTQ)
  * :heavy_check_mark: install-bookinfo [#[1273]](https://paste.fedoraproject.org/paste/RhzxBRaIeyETMzrWPO7xnA)
  * :heavy_check_mark: Kiali-on-Openshift [#[1248]](https://paste.fedoraproject.org/paste/wsQQQoVMkvSVq1MflEpacw)
  * :red_circle: run-kiali-e2e-tests [#[641]](https://paste.fedoraproject.org/paste/Bgro0ZbYtn4x1RQLMnqtlA)


KIALI_NAME=kialiuipr786-istio-system

**Comment by jshaughn** [comment]
@abonas I was able to dnf install inkscape onto my f28 and it seems like a pretty powerful open source SVG editor.  I was able to import the icon svg which was nicely downloadable from fontawesome's web site.  The only change was the svg so I think we can merge.

**Pull request merged**
