### PR TITLE
KIALI-959 Support node detail graphs and drill-down

### PR DESCRIPTION
**Pull request by jshaughn**

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#16](https://paste.fedoraproject.org/paste/KtBLSXuXBtD63kkBgjj8KQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1179]](https://paste.fedoraproject.org/paste/sCVcpQGHzN1WeC8s1X1Mpw)
  * :heavy_check_mark: Kiali-on-Openshift [#[529]](https://paste.fedoraproject.org/paste/-YDNLWbGO~iAxMO-nlMDOA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[945]](https://paste.fedoraproject.org/paste/01aYfnFFezwNGRHEK85cDg)
  * :red_circle: run-kiali-e2e-tests [#[30]](https://paste.fedoraproject.org/paste/UMOVtJvdEo89hycAy~DMyg)

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#21](https://paste.fedoraproject.org/paste/KnOneRZ5ey5ikqnmUrA~8A)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1201]](https://paste.fedoraproject.org/paste/hXlgpSJVLQ39yPofemoKvg)
  * :heavy_check_mark: Kiali-on-Openshift [#[547]](https://paste.fedoraproject.org/paste/tZI3m5gL2-J6kysTiBlZjA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[983]](https://paste.fedoraproject.org/paste/hq5c9PmhvriEWW7ofjD83A)
  * :heavy_check_mark: run-kiali-e2e-tests [#[43]](https://paste.fedoraproject.org/paste/QfN4tdqZo-i4h~~FJbjdQQ)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#22](https://paste.fedoraproject.org/paste/drE5My2d47-BQzEBQ4Yl4g)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1202]](https://paste.fedoraproject.org/paste/9Lm4wq4WRCIrVcR3KCL-Bg)
  * :heavy_check_mark: Kiali-on-Openshift [#[548]](https://paste.fedoraproject.org/paste/GtWBA1JU0GURgG75qG5Iww)
  * :heavy_check_mark: Kiali-Istio-Checker [#[984]](https://paste.fedoraproject.org/paste/Jjc9rk65QWtI4HHLOBXRsw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[44]](https://paste.fedoraproject.org/paste/RE9oBdYsmIX-gIiaXrhbjQ)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#24](https://paste.fedoraproject.org/paste/vnQ~KhGVRSlyV~gIxooSMA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1205]](https://paste.fedoraproject.org/paste/wuVehIDYoPVeBbRBQjZQTQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[551]](https://paste.fedoraproject.org/paste/C7RTpUMH73~JpnkTrgqZTQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[989]](https://paste.fedoraproject.org/paste/5RdqWGkDbxLlrybbTJScPw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[46]](https://paste.fedoraproject.org/paste/0ZWIENBl-rPnxtcvPPoPZg)


KIALI_NAME=kialiuipr663-istio-system

**Comment by jmazzitelli** [comment]
FWIW: I'm running with this stuff, and it works pretty good. Only problem is when you drill-down (double click) on a drill-down graph, the graph doesn't reload until a "refresh" happens.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#25](https://paste.fedoraproject.org/paste/d-Mbjp1oF-~EKLpKG2BsKg)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1209]](https://paste.fedoraproject.org/paste/fBKOzUJJ3RQEnI2m0ivTNg)
  * :heavy_check_mark: Kiali-on-Openshift [#[556]](https://paste.fedoraproject.org/paste/i3yZU-coGCcVCqa6NlM~Ng)
  * :heavy_check_mark: Kiali-Istio-Checker [#[996]](https://paste.fedoraproject.org/paste/03EoQmYiYURcruS595vEIQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[50]](https://paste.fedoraproject.org/paste/l1kPycMUN2UD~2MEppwOYA)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#26](https://paste.fedoraproject.org/paste/E09rWSsemkMjkWoTEkyA2w)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1210]](https://paste.fedoraproject.org/paste/czDXcs~noEgiQ3yQC5rAsg)
  * :heavy_check_mark: Kiali-on-Openshift [#[557]](https://paste.fedoraproject.org/paste/LMMS6mBtJb9nKnnDT3LLEA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[997]](https://paste.fedoraproject.org/paste/rAZ6a83dJ4d9MTrqo2yp-Q)
  * :heavy_check_mark: run-kiali-e2e-tests [#[51]](https://paste.fedoraproject.org/paste/pwQ8O27oYYuEozAhG8wNZA)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#28](https://paste.fedoraproject.org/paste/cCd1XeaI1Iv6J44OJdXQ-A)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1212]](https://paste.fedoraproject.org/paste/5PTREj3uBXL8ZT0FE8ipew)
  * :red_circle: Kiali-on-Openshift [#[559]](https://paste.fedoraproject.org/paste/XYtRqDP4ucAuEbR88EQfmQ)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#29](https://paste.fedoraproject.org/paste/~aTyHciaq~4XjCpemWb-Qg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1214]](https://paste.fedoraproject.org/paste/LEzgpbjkxtgBpfSJ6jvFmg)
  * :red_circle: Kiali-on-Openshift [#[561]](https://paste.fedoraproject.org/paste/9oTKjU08832ymgcm3WtduQ)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#30](https://paste.fedoraproject.org/paste/W50Ea10RttH0tc2mTbI39Q)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1215]](https://paste.fedoraproject.org/paste/x88MvnZpWlcPUmGpDAXtzA)
  * :red_circle: Kiali-on-Openshift [#[562]](https://paste.fedoraproject.org/paste/SbUw03typJZ7YD24T9yYBw)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#32](https://paste.fedoraproject.org/paste/Jh8ATuxUwG3rm~no9mb3NQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1220]](https://paste.fedoraproject.org/paste/dB4b8MlmMPB~ZeaVu1v7iw)
  * :heavy_check_mark: Kiali-on-Openshift [#[568]](https://paste.fedoraproject.org/paste/vxg4kNuUfxAIx0rrLX-BOA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1003]](https://paste.fedoraproject.org/paste/XZ4Kzu-eHJ~pGuuqr6TWhg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[53]](https://paste.fedoraproject.org/paste/YOfmdNz2HwH7i5cgwt9y6Q)


KIALI_NAME=kialiuipr663-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#33](https://paste.fedoraproject.org/paste/G4reNGdgoKrLRxeqtNQUnA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1222]](https://paste.fedoraproject.org/paste/ldSkimT5enY7nyIFG5WZBw)
  * :heavy_check_mark: Kiali-on-Openshift [#[570]](https://paste.fedoraproject.org/paste/sEhFZWlcCCmtSTI6YKP2QQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1004]](https://paste.fedoraproject.org/paste/vH9hHEX7T27GfR89xk3dGg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[54]](https://paste.fedoraproject.org/paste/prCXts7oxeGAIfTYOs~20A)


KIALI_NAME=kialiuipr663-istio-system

**Pull request merged**
