### PR TITLE
 KIALI-2809 Upgrade PF4 to release 3.58.1 

### PR DESCRIPTION
**Pull request by aljesusg**
Stable version 3.58.1 https://www.npmjs.com/package/@patternfly/react-core

### CODE REVIEW

**Comment by aljesusg** [comment]
@lucasponce What do you think about merge this ?

**Comment by lucasponce** [comment]
@aljesusg I'm already fetching locally, give me some minutes and I'll test

**Comment by lucasponce** [comment]
I've found a problem on "show on graph"
image

So, please, don't merge, going to check if that is something present in master or if it's due my env only.

**Comment by aljesusg** [comment]
Hahahha

**Pull request merged**
