### PR TITLE
Link graph from trace details, with trace overlay

### PR DESCRIPTION
**Pull request by jotak**
Fixes https://github.com/kiali/kiali/issues/2842 (and part of https://github.com/kiali/kiali/issues/3095)

Capture d’écran de 2020-09-15 12-07-42

Note: as part of https://github.com/kiali/kiali/issues/3095 it is possible that the design / placement of this link will soon change.
Comments are welcome for readjustments of the whole table.

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM maybe we can set the link in the header

**Comment by jotak** [comment]
@aljesusg yes, I really don't know, either option is fine to me. I'll give a try with link in the header

**Comment by jotak** [comment]
Here's a couple of other options:

1. 
Capture d’écran de 2020-09-15 13-15-57

2.
 Capture d’écran de 2020-09-15 13-17-05

3.
 Capture d’écran de 2020-09-15 13-17-42


I think I prefer 1. or 3.

**Comment by aljesusg** [comment]
I prefer 1 :)

**Comment by jotak** [comment]
> I prefer 1 :)

Done, I've changed to that one

**Review by skondkar — APPROVED** [review]
Verified on Kiali UI: 1.24.0 (28f2d9a41faadaa66c537e8ab3dacc65c5b929a7)
Verified the link 'View On Graph' on traces which navigates to graph page displaying path.

Screenshot_ViewOnGraph-Link


Screenshot from 2020-09-15 19-37-02

**Comment by jotak** [comment]
thanks @aljesusg @skondkar

**Pull request merged**
