### PR TITLE
[PF4] KIALI-1635 Migrate validations to PF4 from Istio Page

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **

Migrating all Validation icons, tooltips and so on.

** Issue reference **

https://github.com/kiali/kiali/issues/1635

** Backwards compatible? **
yes

** Screenshot **

### TooltipValidation component:
Shows the list of all the validations for a group of checkers.
Screenshot of Kiali Console (25)

Screenshot of Kiali Console (26)

### GlobalValidation:
Only shows the status of the whole object.

Screenshot of Kiali Console (27)

Screenshot of Kiali Console (28)

### CODE REVIEW

**Comment by hhovsepy** [comment]
Subset validation does not show for DR:
Screenshot from 2019-09-18 09-02-48
Screenshot from 2019-09-18 09-03-04

**Comment by lucasponce** [comment]
I'm not sure if it's in the scope of this PR, but I have this one:
image
Which it looks like the tooltip in the list are still in PF3, right ?

**Comment by lucasponce** [comment]
Also, I can confirm this issue too https://github.com/kiali/kiali/issues/1686

**Comment by lucasponce** [comment]
Also I see this:
image

in a local yarn start using commit:

```
commit 4f1fae54b927e261bcb75192d8a21415f39d9d61 (HEAD -> pr1394)
Author: Xavier Canal i Masjuan <xeviknal@gmail.com>
Date:   Wed Sep 18 11:23:20 2019 +0200

    Service link from DR Page fixed: not shown when object is invalid
```

Not sure if I'm building correctly the PR or those are out this one.

**Comment by lucasponce** [comment]
Also, I see another regression in the DestinationRule Overview:
image

The host can be a link with the service within same namespace.

**Comment by lucasponce** [comment]
Ok, I can understand that probably the tooltips under ServiceDetails will be migrated when we touch that page (oh, it's in my backlog :-), so I will reuse this, too).

**Comment by lucasponce** [comment]
Code LGTM, and if scope it's just the IstioDetailPage, it's Ok.
But I'd fix the regression with the host link in the DestinationRule Overview case.
Probably that one was missed before.

**Comment by hhovsepy** [comment]
@lucasponce is the DR with missing host link valid? Because if the subset is invalid, it should not display a link to host.

**Comment by xeviknal** [comment]
@lucasponce all the popovers in white are migrated in here: https://github.com/kiali/kiali-ui/pull/1423
Yes, I can confirm the regression. Approaching this now. Thanks very much for the review.

**Pull request merged**
