### PR TITLE
Add Jaeger configuration for namespaceSelector

### PR DESCRIPTION
**Pull request by aljesusg**
Fix: https://github.com/kiali/kiali/issues/1785

Require: https://github.com/kiali/kiali/pull/1801

### CODE REVIEW

**Comment by hhovsepy** [comment]
@aljesusg now those services which required service.namespace (for instance details.bookinfo) does not show traces in Kiali.

**Comment by aljesusg** [comment]
@hhovsepy I did the changes that we talked, can you check them? Thanks

**Comment by hhovsepy** [comment]
In Traces tab of service, it shows traces for bookinfo/details, but does not show for istio-system/istio-ingressgateway it does not. And for Distributed Tracing menu it behaves in the opposite way:
Screenshot from 2019-10-24 15-44-17
Screenshot from 2019-10-24 15-44-38
Screenshot from 2019-10-24 15-45-01
Screenshot from 2019-10-24 15-45-27

**Comment by aljesusg** [comment]
@hhovsepy you should see a checkbox before the lookback drop-down with the namespace-selector option, it seems that the build is not for this PR

**Comment by hhovsepy** [comment]
When Namespace Selector checkbox is selected/deselected the checked Service is reset and "Search Traces" button is disabled. Can the this functionality be removed? So Service selection is not reset.
This is not right from UX perspective.
Also in Service's Traces tab when checking or unchecking Namespace Selector, it disables the "Search Traces" button and keeps disabled forever.
Screenshot from 2019-10-24 18-09-58

**Comment by xeviknal** [comment]
yep, I can agree with @hhovsepy . I think that toggling the checkbox shouldn't reset the dropdown. It is pretty odd to re-select the option. Specially for those who don't know about the feature.
Thinking out lout, but shouldn't this be on the advanced options? I don't think it is something you change many times. wdyt?

**Comment by aljesusg** [comment]
cc @xeviknal @hhovsepy

**Comment by hhovsepy** [comment]
@aljesusg so the namespace_selector config is always true by default?

**Comment by hhovsepy** [comment]
Checking "Namespace Selector" checkbox causes the Traces data to reload, is this the intended behavior?.
But still it uses the checkbox's old (preclick) value in the refresh request. Only after click to "Search Traces" button sends correct request.
Also with smaller windows the view is broken.
Screenshot from 2019-11-13 13-14-59

**Comment by hhovsepy** [comment]
Also in Distributed Tracing section, when first entering without having any namespace selected, then after selecting namespace, the service selection dropdown is still disabled:
Screenshot from 2019-11-13 13-21-59

**Comment by aljesusg** [comment]
> @aljesusg so the namespace_selector config is always true by default?

Yes, the user must set in kiali configmap to false or kiali will set this to true

> Checking "Namespace Selector" checkbox causes the Traces data to reload, is this the intended behavior?.
> But still it uses the checkbox's old (preclick) value in the refresh request. Only after click to "Search Traces" button sends correct request.
> Also with smaller windows the view is broken.
> Screenshot from 2019-11-13 13-14-59

I did a trigger to relaod the iframe with the data onClick namespace Selector...maybe we can remove it and have the same behaviour than lookback


> Also in Distributed Tracing section, when first entering without having any namespace selected, then after selecting namespace, the service selection dropdown is still disabled:
> Screenshot from 2019-11-13 13-21-59

MMM let me check this I tested and it was working that.

**Comment by aljesusg** [comment]
@hhovsepy I fixec the reload of the services, I removed the update testing :(. Can you check it ?

**Pull request merged**
