### PR TITLE
Cypress:user logout

### PR DESCRIPTION
**Pull request by pbajjuri20**
Kiali User logout test case

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@pbajjuri20 We aren't using this kiali-ui repo anymore - UI is in kiali/kiali under `frontend` directory.

**Comment by pbajjuri20** [comment]
@jmazzitelli: I will create this PR under kiali/kiali.

Thank you, Mazz

**Comment by pbajjuri20** [comment]
Creating this PR against kiali/kiali under frontend directory.

**Comment by pbajjuri20** [comment]
Creating this PR against kiali/kiali under the frontend directory.

**Pull request closed without merging**
