### PR TITLE
KIALI-2731 Support Advanced LoadBalancing in Wizards

### PR DESCRIPTION
**Pull request by lucasponce**
** Describe the change **

Add following options in the "Advanced Options" section on wizards:
- VirtualService Hosts
- Add LoadBalancer, supporting simple or consistent hashing.
- Add Gateway.

Implemeting a progressive disclosure [1] strategy on LoadBalancer / Gateway options.
Fix some problems with multiple sections validations.

image

image

image

[1] https://www.patternfly.org/pattern-library/forms-and-controls/progressive-disclosure/

### CODE REVIEW

**Comment by hhovsepy** [comment]
1. With HTTP Cookie type, it does not say value format:
Screenshot from 2019-06-06 14-09-43

2. With HTTP Header type, when creating first time, it keeps 2 types in a DR, Header and Source IP:
Screenshot from 2019-06-06 14-09-43
Screenshot from 2019-06-06 14-15-35

3. Enter key in wizard is not handled, it relogins.

**Comment by lucasponce** [comment]
> Enter key in wizard is not handled, it relogins.

On this case, what would be the expected behaviour ? to invoke "Create" right ?

**Comment by hhovsepy** [comment]
> > Enter key in wizard is not handled, it relogins.
> 
> On this case, what would be the expected behaviour ? to invoke "Create" right ?

yes

**Comment by hhovsepy** [comment]
> 2.  With HTTP Header type, when creating first time, it keeps 2 types in a DR, Header and Source IP:
But when editing the route, it fixes the Load Balancer value and SourceIP is removed.

**Comment by lucasponce** [comment]
> With HTTP Header type, when creating first time, it keeps 2 types in a DR, Header and Source IP:
> But when editing the route, it fixes the Load Balancer value and SourceIP is removed.

Yes, it seems some null values are rendered and creating some confusion in the table.

**Comment by lucasponce** [comment]
@hhovsepy I think all comments and RFE are addressed on my last commit.
Please let me know how it looks like there.
Thanks !

**Comment by hhovsepy** [comment]
Type any value in any Consistent Hash tape of LoadBalancer, wait a second, Create button is enabled, continue typing.
It will auto submit the Wizard.

**Comment by hhovsepy** [comment]
tested on FF and Chrome, private browsing.

**Comment by lucasponce** [comment]
> Type any value in any Consistent Hash tape of LoadBalancer, wait a second, Create button is enabled, continue typing.
It will auto submit the Wizard.

Oh, good catch, it seems it happens on the weighted wizard. I missed this one, I tested only the matching one.

**Comment by lucasponce** [comment]
@hhovsepy I think now the Enter key is captured correctly.

**Comment by lucasponce** [comment]
@aljesusg could you take a look into the PR to check if I missed something related code ?
In terms of features this one is tested.

**Pull request merged**
