### PR TITLE
Happy halloween!

### PR DESCRIPTION
**Pull request by josejulio**
happy-halloween

They are supposed to look like pumpkins :)

### CODE REVIEW

**Comment by mtho11** [comment]
Nice! Happy Halloween!

**Comment by JStickler** [comment]
LOL, OMG I love it.  =D

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#301](https://paste.fedoraproject.org/paste/SjxviOTTq020RZR6JLiMug)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1879]](https://paste.fedoraproject.org/paste/KsGx1mWET08Nnb4KK5l6Ow)
  * :heavy_check_mark: Istio-Upstream [#[727]](https://paste.fedoraproject.org/paste/OKBE6oKOdFt5yWg39CSLuA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2297, 2298]](https://paste.fedoraproject.org/paste/tDUF4gbIjURHtHYkyTvKXQ)
  * :heavy_check_mark: install-bookinfo [#[1265]](https://paste.fedoraproject.org/paste/iFVZEj2oWNDKxKZe7rViFw)
  * :heavy_check_mark: Kiali-on-Openshift [#[1242]](https://paste.fedoraproject.org/paste/sXcxlFb67k-i2OKwz-Ei3g)
  * :red_circle: run-kiali-e2e-tests [#[635]](https://paste.fedoraproject.org/paste/54EUoapaPfoGQBSbG09YZQ)


KIALI_NAME=kialiuipr784-istio-system

**Comment by jmazzitelli** [comment]
I'm expecting to see the animation to be bats instead of dots :)

**Comment by theute** [comment]
Oh this is awesome, was there a tweet ??

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by jmazzitelli** [comment]
I'm closing this before someone accidentally merges it :)

**Comment by josejulio** [comment]
> I'm expecting to see the animation to be bats instead of dots :)

bats


//cc: @jmazzitelli

**Comment by josejulio** [comment]
Thanks! It looks funny :)

**Pull request closed without merging**
