### PR TITLE
KIALI-2399 'No traces' for existing service due to missing namespace

### PR DESCRIPTION
**Pull request by aljesusg**

### CODE REVIEW

**Comment by hhovsepy** [comment]
Failing for me:
screenshot from 2019-02-18 14-08-23

**Comment by aljesusg** [comment]
@hhovsepy Can you verify this now with the last kiali master ?

**Comment by hhovsepy** [comment]
Still failing, missing "/jaeger/" in a URL, it is "<jaegerIP>/search?service=details.bookinfo" but should be "<jaegerIP>/jaeger/search?service=details.bookinfo"

**Comment by aljesusg** [comment]
mmm so in Maistra isdeploying in /jaeger but I don't know in upstream

**Comment by hhovsepy** [comment]
ok, rechecking it on Maistra

**Pull request closed without merging**
