### PR TITLE
KIALI-1063 Turn off loading spinner on response error

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by aljesusg** [comment]
I think that spinner is running when an axios request is running so in response error the axios request is finished and spinner should stop, see sec/app/App.tsx from L12, so I think that we don't need this

https://github.com/kiali/kiali-ui/blob/6202fbf4ba5d114f9e409c23898a80cc8857ca57/src/app/App.tsx#L12

**Comment by josejulio** [comment]
> Is it really working in case of several concurrent requests? I would say a counter that increments for each requests and decrements for each response should be the way to go (and it's loading when counter > 0)

That's other bug that i was going to file :)

**Comment by jotak** [comment]
@aljesusg yeah, but wrote *concurrent* requests.
Start REQ1 => spinner spins
Start REQ2 => spinner spins
End REQ1 => spinner stops ... wait, what?
we need to count :) But that's another bug, yes.

**Comment by josejulio** [comment]
> I think that spinner is running when an axios request is running so in response error the axios request is finished and spinner should stop, see sec/app/App.tsx from L12, so I think that we don't need this

Is not doing that on timeout, there is no response when a request times out, so it goes to `error` L36

**Comment by aljesusg** [comment]
Oh I see ... And check if there is any axios pending in the response section and avoid counters?

**Comment by josejulio** [comment]
> Oh I see ... And check if there is any axios pending in the response section and avoid counters?

We will need counters to know all requests finished, but going to do that in a separate PR

**Comment by josejulio** [comment]
> Oh I see ... And check if there is any axios pending in the response section and avoid counters?

Unless we can check if there is any pending requests, can we do that?

**Comment by mtho11** [comment]
You guys are all correct. Nice insights.
I believe the real solution to this is via _Observables_ (Rx.js). This allows us to combine multiple requests (streams) into whatever strategies we want.
Promises have their limitations.
Sorry for hijacking, obviously another sprint ;)

**Comment by mtho11** [comment]
@jotak @aljesusg go to bed. It's Friday night 🛏

**Comment by josejulio** [comment]
https://issues.jboss.org/browse/KIALI-1080

**Comment by josejulio** [comment]
> @jotak @aljesusg go to bed. It's Friday night

Actually i think that is at least Saturday morning for them :)

**Comment by jotak** [comment]
@josejulio now it is, but not on my first post. (and I'm in bed... counting the requests helps to sleep)

**Comment by aljesusg** [comment]
Me too ^^

**Comment by josejulio** [comment]
@jotak The related bug (count the requests) is tracked in [KIALI-1080](https://issues.jboss.org/browse/KIALI-1080), can you review this one and merge if is OK?

Thanks!

**Pull request merged**
