### PR TITLE
[KIALI-474] Add button to toggle Circuit Breakers on Graph

### PR DESCRIPTION
**Pull request by cfcosta**
The button is shown on the right side of the filter bar, like this:

It can also be defined on the URL, for repeatable graph generation.

### CODE REVIEW

**Comment by pilhuhn** [comment]
On 18 Apr 2018, at 1:19, Josejulio Martínez wrote:

> I think it should be "Hide Circuit Breakers" / "Show Circuit Breakers" 
> or something like that to show what is actually going to do 
> (Show/Hide).

+3 Especially as "Toggle" could also mean to (de)activate the the CBs in 
the real istio-RRs.

**Comment by jshaughn** [comment]
My 2 cents, this seems like a checkbox thing to me, just a checkbox labeled with 'circuit breakers'.

**Comment by mtho11** [comment]
Looks like it should be a toggle button. I think we are going to have a whole row of these _visibility layer toggles._
toggle

**Comment by cfcosta** [comment]
Fixed failing tests, and added the filter on a new row:

**Comment by mtho11** [comment]
Remember to squash the commits

**Pull request merged**
