### PR TITLE
Merge "api doc" and "additional details" features

### PR DESCRIPTION
**Pull request by jotak**
- API doc feature is removes / replaced with more generic "additional details" one
- Add optional icon display with additional details (to keep API doc icons)
- Kiali won't embed documentation anymore, this is replaced with external links
- Removing "rapidoc" dependency also lowers attack surface / deps size (-315 lines in yarn.lock)

Fixes https://github.com/kiali/kiali/issues/1567 (part-of)

Required backend PR: https://github.com/kiali/kiali/pull/2262

### CODE REVIEW

**Comment by jotak** [comment]
Capture d’écran de 2020-02-18 16-35-21

**Comment by jotak** [comment]
yes @hhovsepy it's done, now it shows the item title (in this example: API documentation)

**Comment by hhovsepy** [comment]
A question: should the documentation icon be sorted in Details column ?

**Comment by jotak** [comment]
@hhovsepy good remark, I've just updated to enable sort based on the icon

**Pull request merged**
