### PR TITLE
KIALI-3067 PF4 migration: charts / k-charted

### PR DESCRIPTION
**Pull request by jotak**
JIRA: https://issues.jboss.org/browse/KIALI-3067

Ongoing work in k-charted repo: https://github.com/kiali/k-charted/issues?q=is%3Aissue+label%3APF4+

- [x] https://github.com/kiali/k-charted/pull/22
- [x] https://github.com/kiali/k-charted/issues/17
- [x] https://github.com/kiali/k-charted/issues/18
- [x] https://github.com/kiali/k-charted/issues/20
- [x] https://github.com/kiali/k-charted/issues/24
- [x] https://github.com/kiali/k-charted/issues/25
- [x] https://github.com/kiali/k-charted/issues/35
- [x] https://github.com/kiali/k-charted/issues/37
- [x] Crashing in some conditions: https://github.com/FormidableLabs/victory/issues/1355
- [x] Do some perf comparison: https://github.com/kiali/k-charted/issues/45

### CODE REVIEW

**Comment by jotak** [comment]
@aljesusg it seems that there's an issue with the Grids used in Kiali. For some reason, all GridItems are taking the whole width, regardless the `span` value that I'm providing.

This seems to be specific to Kiali, because in K-charted storybook the items are correctly displayed, I can put several charts on the same row, which for some reason doesn't work in Kiali.
I wonder if you have any idea about what can be the problem.

I've seen that you did several CSS overrides about the grids here : https://github.com/kiali/kiali-ui/blob/master/src/styles/_overrides.scss
I wonder if it could play some role here. Any idea?

**Comment by aljesusg** [comment]
Yes @jotak , this will be fixed upgrading PF4 , I am working on it, I don't know if you can wait . If not please feel free to remove the css that is blocking you.

**Comment by jotak** [comment]
@aljesusg that's fine, i've upgraded locally and indeed it works better. No hurry for that, as far as we know what we have to do.

**Comment by jotak** [comment]
So, all dependant tasks are merged, however we still need to sort out the grid issue before it can be merged.
It seems that a PF4 upgrade is necessary for that, but I'm having quite a lot of troubles when I try to do it (many errors ... btw I can't understand how I could have seen it working correctly 3 days ago ???)

**Comment by jotak** [comment]
Testing with @aljesusg PR ( https://github.com/kiali/kiali-ui/pull/1302 ) => the grid issue is gone.
However I've found a new issue, probably in k-charted : https://github.com/kiali/k-charted/issues/35

**Comment by jotak** [comment]
Hey, I've added a script to fetch automatically PRs from k-charted and put them in node_modules.
For instance, to test this https://github.com/kiali/k-charted/pull/44 now we just have to run, from kiali-ui:

```
./fetch-k-charted-pf4.sh https://github.com/kiali/k-charted/pull/44
# then
yarn start
# or
yarn build
```

**Comment by josejulio** [comment]
> Hey, I've added a script to fetch automatically PRs from k-charted and put them in node_modules.
> For instance, to test this [kiali/k-charted#44](https://github.com/kiali/k-charted/pull/44) now we just have to run, from kiali-ui:

What would it take to restore k-charted?
Could you set up a script or put instructions to do it?
If is only "yarn install", i would suggest to put a warning that doing so will reset this change.

**Comment by jotak** [comment]
@josejulio I've updated the script to add more info. `yarn install` may or may not restore the original version, afaict it will depends on yarn.lock being up-to-date or not.
So the best way to restore files would be `yarn upgrade @kiali/k-charted-pf4`, I think. It's now mentioned in the script.

**Comment by hhovsepy** [comment]
Empty page is loaded, it seems rebase is needed.

**Comment by jotak** [comment]
There's still a blank page. Similar problem as we've seen before, probably due to some lazy loading, but the error message really doesn't help.

@israel-hdez , how did you fix that issue last time? You removed the lazy loading for AppDetails, but what made you think it was that page that had an issue? Because the error is ununderstandable i've no idea what is causing the issue (or i can try all the pages one by one, is that what you did?)

I've also tried to update all our dependencies (removing yarn.lock + reinstalling), it doesn't solve the issue.

**Comment by israel-hdez** [comment]
@jotak Yes, I did that one by one.
But I tried quickly and nothing helped in this case.

I traced the issue and the MessageCenter was the problem. See PR https://github.com/kiali/kiali-ui/pull/1339. It fixes master and also this PR. But I'm unsure. See my comment in that PR

**Comment by jotak** [comment]
@hhovsepy now that #1343 has been merged, you should now be able to test.

As a reminder, you can use the new script:
```
./fetch-k-charted-pf4.sh 44
yarn build
```

Note that by fetching this PR you'll get not only the fix but also all changes that were made in k-charted since v0.2.0, as this PR is based on master : https://github.com/kiali/k-charted/compare/v0.2.0...master

So you will notice several changes, that will anyway get in once we upgrade the lib version in kiali-ui.

**Comment by hhovsepy** [comment]
Getting this error while building k-charted:
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1564568650700-0.1615605488093772/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8f9d10 node::Abort() [/usr/bin/node]
 2: 0x8f9d5c  [/usr/bin/node]
 3: 0xaffd0e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xafff44 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xef4152  [/usr/bin/node]
 6: 0xef4258 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/bin/node]
 7: 0xf00332 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0xf00c64 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0xf038d1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0xeccd54 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/bin/node]
11: 0x116cede v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
12: 0x62f6dedbe1d

**Comment by jotak** [comment]
@hhovsepy :-( This PR is cursed
Can you try shutting down some running stuff on your machine?

I'm also seeing more and more out-of-memory issues during builds. Not especially with this PR, but any other. I'm surprised the builds require so much memory. Maybe we should try with different versions of yarn/node/typescript/what else? cc @mtho11 @josejulio @israel-hdez do you see that as well?

**Comment by jotak** [comment]
@hhovsepy not sure if you saw my post on kiali-dev : when you get OOM you can try setting max memory parameter on node : 
`export NODE_OPTIONS=--max_old_space_size=4096`

**Comment by israel-hdez** [comment]
@jotak I haven't seen that issue locally. I just tried and it works OK :-/

**Comment by hhovsepy** [comment]
Thanks @jotak ,
Now I verified https://github.com/kiali/k-charted/pull/44
But in charts loading I see some slowness, it takes from few seconds to some 10 seconds to load/reload charts.

**Comment by jotak** [comment]
thanks @hhovsepy 
I'll do more perf analysis now

**Comment by hhovsepy** [comment]
Minor thing: the values of X and Y axis are too close on the 0 point.
Otherwise looks good, will retest after rebase.
Screenshot from 2019-08-07 12-02-46

**Comment by hhovsepy** [comment]
Verified.
Screenshot from 2019-08-08 20-06-24

**Comment by jotak** [comment]
Thanks @hhovsepy I've seen your comment about labels too close, I'll try to fix that

**Comment by jotak** [comment]
Thanks @aljesusg 

@hhovsepy : i've created a ticket : https://github.com/kiali/k-charted/issues/49

**Pull request merged**
