### PR TITLE
Add support for Node.js 12.x (new LTS)

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Now that Node.js 12.x is LTS we need to support that as well as the existing LTS which is 10.x.

- [ ] Make tests work with both Node.js 12.x and 10.x 

The issue here is that our tests fail when using the new version and fixing that makes the tests fail in the old version.

fixes: https://github.com/kiali/kiali/issues/1946

### CODE REVIEW

**Comment by mtho11** [comment]
The real issue here is if we want to support both Node.js 10.x and 12.x for UI builds or just the latest 12.x version? It is further reaching because of transitive dependencies.

**Comment by mtho11** [comment]
After fiddling with this stuff the question is: "Do we want to support both Node.js 10.x and 12.x, or should we just move on to 12.x"? 
Both are LTS versions with overlapping time periods.
Obviously, there is a cost to supporting both versus just the latest.

**Comment by jotak** [comment]
As long as the 12.x support works just fine and doesn't cause any trouble to the developers, I don't see any reason to continue to support 10.x, no?

**Comment by jshaughn** [comment]
@mtho11 Why did you close this?  If it makes sense and seems stable I think it should be fine for beginning of the next sprint.

**Comment by mtho11** [comment]
There is a lot of work to be done to make this work with both 10 and 12.

**Comment by jshaughn** [comment]
What about just 12?  Why support both?

**Comment by israel-hdez** [comment]
I would vote to support node12 only if it is already available in downstream for building.
Note that *nodejs support* is only to support dev environments (and the build). The final package does not depend on nodejs.

**Comment by mtho11** [comment]
Just supporting 12 would be much easier. That would be my vote.

**Pull request closed without merging**
