### PR TITLE
kiali-440: Bump all versions in package.json (and package-lock.json).

### PR DESCRIPTION
**Pull request by mtho11**
Bump all the versions to latest.

### CODE REVIEW

**Comment by pilhuhn** [comment]
At least no obvious fallout in the UI

**Comment by mtho11** [comment]
@aljesusg I don't want to change your snapshot test failures. So I guess this one is in your hands now.

**Comment by aljesusg** [comment]
All snapshoots fail in local with this changes,**MetricsOptionsBar**  too(src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap). After update snapshoots tests pass in this tests but now fail in ServiceInfo when check if there is ServiceInfoDescription element 

```js
expect(wrapper.find('ServiceInfoDescription').length === 1).toBeTruthy();
```

**Comment by jotak** [comment]
@mtho11 can you run `npm test -- -u` , locally, run all tests and commit the modified snapshots please?

**Comment by mtho11** [comment]
@jotak Wow.  I didn't realize I had to replace the Jest snapshots after npm package upgrades. Nice find!
Closing this now in favor or #195

**Pull request closed without merging**
