### PR TITLE
KIALI-2732 [PF4] Upgrade patternfly/react-core to 3.2.6

### PR DESCRIPTION
**Pull request by aljesusg**
Upgrade to the stable release 3.2.6 for production

### CODE REVIEW

**Comment by cfcosta** [comment]
Sorry, marked it as ready to review by accident.

Anyway, I did some testing for using @patternfly/react-core 3.4.1 as a part of KIALI-2529, and the update went ok. Didn't go too far on testing, since upgrading to create-react-app is going to break a lot more stuff than this, but everything seems ok.

**Comment by aljesusg** [comment]
No @cfcosta there are issues with styles after upgrade, I am working with PF4 team, this is why it was like a draft.

**Comment by aljesusg** [comment]
@hhovsepy  @lucasponce this is the upgrade to PF stable release for production. Can you check that all is ok like before?

**Comment by aljesusg** [comment]
thanks @hhovsepy

**Pull request merged**
