### PR TITLE
KIALI-1625 Add tour component

### PR DESCRIPTION
**Pull request by josejulio**
** Describe the change **

Adds a tour component to improve the graph help

Todo:
[x] Finish the tour component.
[x] Implement the Tour in the graph page.

** Screenshot **

~~This is a demo of what it does so far, to start gathering feedback.
Is not complete, the final layout of the Tour is not done.~~

demo-tour-3

old demo:
demo-tour

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#196](https://paste.fedoraproject.org/paste/7nW-8wDS3aspQ81P2WW1WA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1565]](https://paste.fedoraproject.org/paste/F4m6hiZTmmcnbiDT-61tfg)
  * :heavy_check_mark: Istio-Upstream [#[420]](https://paste.fedoraproject.org/paste/M0g7xz8W6DbytX2cdpHieQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1685, 1686]](https://paste.fedoraproject.org/paste/cDkdP26t4QvYHhMl4SQvIA)
  * :heavy_check_mark: install-bookinfo [#[936]](https://paste.fedoraproject.org/paste/nwgSZ~nzUW987MlxWIZq6A)
  * :heavy_check_mark: Kiali-on-Openshift [#[943]](https://paste.fedoraproject.org/paste/IWyZzRtYM60oNQ1BdZ1Djw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[362]](https://paste.fedoraproject.org/paste/2GF4aVR8IwKkvDSFSrIK3Q)


KIALI_NAME=kialiuipr740-istio-system

**Comment by pilhuhn** [comment]
That demo animation looks like a game of whack-a-mole :-)

Good job !

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#208](https://paste.fedoraproject.org/paste/7ioBlaPKyLnWi8PG20tEWg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1594]](https://paste.fedoraproject.org/paste/6mNFX8kcdnGkHQJV9hsi8A)
  * :heavy_check_mark: Istio-Upstream [#[447]](https://paste.fedoraproject.org/paste/45XNBW-Hn6TGAIxd~TKZVA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1753, 1754]](https://paste.fedoraproject.org/paste/DN61OcN1vRN0xtX05W1FmA)
  * :heavy_check_mark: install-bookinfo [#[968]](https://paste.fedoraproject.org/paste/vPctg9MTi8aitalizgELtA)
  * :heavy_check_mark: Kiali-on-Openshift [#[983]](https://paste.fedoraproject.org/paste/jGqTgQ3HMDfPc5a3neZw5A)
  * :red_circle: run-kiali-e2e-tests [#[392]](https://paste.fedoraproject.org/paste/Qyp6iUupLHY2GsekwcZheQ)


KIALI_NAME=kialiuipr740-istio-system

**Comment by josejulio** [comment]
> @josejulio this needs rebased

Rebased

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#210](https://paste.fedoraproject.org/paste/0rv3dRbRfHq4hegPSVEUhw)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1598]](https://paste.fedoraproject.org/paste/lgUxvZ9Q4HzVL1SWvjNaUQ)
  * :heavy_check_mark: Istio-Upstream [#[451]](https://paste.fedoraproject.org/paste/mR4KVk2nz78F0-uNOGdvXA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1761, 1762]](https://paste.fedoraproject.org/paste/wEjMAP6tS9AFNqztARxbGQ)
  * :heavy_check_mark: install-bookinfo [#[972]](https://paste.fedoraproject.org/paste/RrS5coD7c-3sIMr2n71P9Q)
  * :heavy_check_mark: Kiali-on-Openshift [#[987]](https://paste.fedoraproject.org/paste/rBlmCUDKKPmD-T7G5QBtug)
  * :heavy_check_mark: run-kiali-e2e-tests [#[396]](https://paste.fedoraproject.org/paste/ZproIMQGG6q4saEv5qdwDQ)


KIALI_NAME=kialiuipr740-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-ui-pr-e2e-test [#211](https://paste.fedoraproject.org/paste/FfjDvUo9L5ZXegrr0u5L1w)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1599]](https://paste.fedoraproject.org/paste/Q5FQEb9PLtgv3B~sHDlUDw)
  * :heavy_check_mark: Istio-Upstream [#[452]](https://paste.fedoraproject.org/paste/A2aoexPhRlodI7cVGOCf8g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1763, 1764]](https://paste.fedoraproject.org/paste/NY2qBrk5OX-Lc2jUEnCw2w)
  * :heavy_check_mark: install-bookinfo [#[973]](https://paste.fedoraproject.org/paste/FZXds6JKIOdFz~aUaQec6A)
  * :heavy_check_mark: Kiali-on-Openshift [#[988]](https://paste.fedoraproject.org/paste/K2WkCK2FuntEHEZITe~FzQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[397]](https://paste.fedoraproject.org/paste/z98mvHXNUi~QEcLP6dettQ)


KIALI_NAME=kialiuipr740-istio-system

**Pull request merged**
