### PR TITLE
Fix warnings and uncaught errors in tests

### PR DESCRIPTION
**Pull request by jotak**
- Add a unique 'id' in Tooltips
- Mock API.getNamespaceMetrics
- Had to rewrite a part of HealthDetails.tsx due to a prettier versus tslint conflict

### CODE REVIEW

**Comment by jotak** [comment]
Note, the mentioned prettier versus tslint conflict is due to prettier formatting blocs of code with new lines after `{` whereas tslint asks (probably just in JSX) that there are no space after `{`.

It's not the first time prettier is bugging me. Ok to use formatting tools as long as they're not broken :-/

**Comment by josejulio** [comment]
> It's not the first time prettier is bugging me. Ok to use formatting tools as long as they're not broken :-/

I don't think they are broken, but not compatible on all their rules. Can you configure either one to match the other (for this case) ?

https://prettier.io/docs/en/configuration.html
https://palantir.github.io/tslint/usage/configuration/

**Comment by jotak** [comment]
@josejulio haven't gone through that painful process yet. Maybe next time.

**Comment by josejulio** [comment]
> @josejulio haven't gone through that painful process yet. Maybe next time.
> Note that prettier config is quite basic and generally it's turning on or off a feature, not fine-tuning how it works.

Seems someone already did that: https://www.npmjs.com/package/tslint-config-prettier

**Pull request merged**
