### PR TITLE
Revise namespace selector (add select all)

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes https://github.com/kiali/kiali/issues/3173

This PR revises the namespace selector in a few ways:

- adds select/deselect all
  - this is the primary RFE addition for 3173
  - note that select/deselect all applies only to the filtered set of namespaces.  Without a name filter it is a "true" all.  This allows the user to easily modify the state of a subset of namespaces, without affecting prior selections.
- batches changes
  - an important behavioral change.  prior to this PR each individual namespace select/deselect generated a state change.  this was distracting and inefficient as even changing from one namespace to another would generate 2 changes and cause pages to update while the user was still working with the dropdown.  now all changes are applied when the dropdown is closed (by clicking the button or outside the dropdown, or via the Escape key (I still wonder whether escape should act as cancel...)).
- changes button label
  - apply badging pattern to indicate multiple namespace selection

See the issue for screenshots/videos.

### CODE REVIEW

**Review by lucasponce — APPROVED** [review]
Thanks.
Tested locally, it works ok.

**Comment by jshaughn** [comment]
@lucasponce thanks for the review.  Although, going forward it would be better not to merge, just approve.  On Saturn we often wait to add QE until after dev approval.  This PR has not yet seen QE approval.  Also, when squash merging I often fix the commit message to avoid a bunch of appended messages for the various commits. Still, glad you liked the PR enough to merge :)

**Comment by lucasponce** [comment]
Ok, but I was the only reviewer, I didn't see QE on the PR this morning and there was changes located into a single file.
Just to sync both teams, add them in the PR otherwise we'll repeat similar scenarios.

**Comment by pbajjuri20** [comment]
LGTM!

I have validated from here https://quay.io/repository/kiali/kiali?tab=tags because it is already merged to Master.

**Pull request merged**
