### PR TITLE
KIALI-1847 fix Kiali favicon

### PR DESCRIPTION
**Pull request by abonas**
** Describe the change **

Fix the favicon (the icon in the browser tab) to be of Kiali and not the default React one.

** Backwards compatible? **

yes

[ ] Is your pull-request introducing changes in behaviour?

_Describe the changes if appropriate. E.g. a new link, a change on what a click does, etc_

** Screenshot **

screenshot at 2018-11-28 18-14-19

### CODE REVIEW

**Comment by abonas** [comment]
btw does anyone know why the img folder is full with various twitter/skype/facebook logos?

**Comment by josejulio** [comment]
The favicon background looks "white", is that on purpose? Does it looks bad with transparent background?

**Comment by jmazzitelli** [comment]
blech... can we get one with transparent background?

**Comment by jotak** [comment]
@abonas @jmazzitelli about the unused icons, I created this some time ago: https://issues.jboss.org/browse/KIALI-1866
Worst part is about the fonts, 15MB, I'm pretty sure we don't use all of that?

**Pull request merged**
