### PR TITLE
ServiceDetails page, Istio Config section: added support of listing Gateways linked in VirtualServices.

### PR DESCRIPTION
**Pull request by hhovsepy**
RFE https://github.com/kiali/kiali/issues/4326

When VirtualService have linked Gateways, then these Gateways are listed in Istio Config section of ServiceDetails page.

Gateways can be linked for instance while creating Routing via Wizard.

Screenshot from 2021-09-29 09-01-21
Screenshot from 2021-09-29 09-01-50

### CODE REVIEW

**Review by lucasponce — APPROVED** [review]
LGTM

Not for this PR, but probably in a next iteration we may want to sync in the list page as well:
image

But I'd prefer to address that once that https://github.com/kiali/kiali/pull/4389 is consolidated as I know that's a backend change.

So no action item for this PR, just leaving a note for the record.

**Comment by hhovsepy** [comment]
Thank you @lucasponce , I am preparing a PR for ServiceList page as well. But they can be verified separately.

> LGTM
> 
> Not for this PR, but probably in a next iteration we may want to sync in the list page as well: image
> 
> But I'd prefer to address that once that [kiali/kiali#4389](https://github.com/kiali/kiali/pull/4389) is consolidated as I know that's a backend change.
> 
> So no action item for this PR, just leaving a note for the record.

**Review by skondkar — APPROVED** [review]
Verified LGTM.
Gateways in VirtualServices are listed on Service Details page.

Screenshot-vs-linked-gateways

Screenshot from 2021-10-01 13-51-40

**Comment by skondkar** [comment]
Polarion Testcase >> SWSQE-1991

**Pull request merged**
