### PR TITLE
Add Container selection back into Workload logs.

### PR DESCRIPTION
**Pull request by mtho11**
** Describe the change **
Add the ability to select a container in the pod.

** Issue reference **
fixes: https://github.com/kiali/kiali/issues/2765

** Screenshot **
Kiali_Console

two-containers

### CODE REVIEW

**Comment by mtho11** [comment]
I used this example of two containers in a pod: https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

And then log into the Nginx container and hit the `curl localhost` to get some log output. The switchback between the containers to see that it works.

**Comment by mtho11** [comment]
@jshaughn this is the minimal fix for getting containers back in the logs

**Comment by mtho11** [comment]
@jshaughn this fix should work until we get the new multi-window design from UxD

**Comment by mtho11** [comment]
Ok here is what the changes look like now for empty logs:

Kiali_Console_and_Simple_Bookstore_App

**Comment by mtho11** [comment]
A video might be more revealing:

empty-logs

**Comment by mtho11** [comment]
@jshaughn your comments have been addressed from the Ux meeting. And updating prettier (devDependency) did resolve the issue with the `?.` operator.

**Comment by mtho11** [comment]
I just added the version (if it has one) to the container dropdown to make it more concise.

**Comment by mtho11** [comment]
Fixed side by side view:
Kiali_Console

**Comment by mtho11** [comment]
Ok Jay found an issue:
1. Refresh new stacked view 50/50 split
2. Make it 25/75 split
3. Goto side by side view
4. Make it 50/50 split
5. go back to stacked view
Observe the strangeness

@pbajjuri20 this is a scenario for you to test once it comes your way

**Comment by pbajjuri20** [comment]
Tested and Passed on Kiali UI 1.19.0 (7ecdbe00b731bdfe8452bc15d1b8cf8e5fddc348)

**Pull request merged**
