### PR TITLE
Don't use message center alerts for regex errors

### PR DESCRIPTION
**Pull request by jshaughn**
use PF4 guideline and make it like graph find/hide.

Fixes https://github.com/kiali/kiali/issues/2973

image

### CODE REVIEW

**Comment by jshaughn** [comment]
> This doesn't work on the OS/X browsers. The catch block never gets executed

I can't explain it, I've scoured the interwebs and there is no mention of the regexp constructor not throwing errors on webkit/safari.  To the contrary there are a lot of example of errors being thrown on safari, sometimes when they should not have been.  Safari supports both the regexp constructor and try/catch.  Something is wonky here.

Do me a favor, try something else bogus in a try catch on safari, like a div by 0 or something, anything.  what happens?  Or try a regexp compile(pattern).   It's deprecated in favor of the construtor but it too should throw an error.

There is, as far as I can see, no regexp validate function, so if this doesn't work on Safari I'm not sure we have an alternative other than to report a bug to safari - but I'd be shocked that we'd be the first to see it, something else must be going on here.

**Comment by jshaughn** [comment]
@mtho11 I made one small change, maybe it somehow makes a difference. on Safari, I got rid of the extraneous "new" in "new RegExp".  Please try again.

**Comment by mtho11** [comment]
Minor spacing issues when errors occur:

Kiali_Console

Kiali_Console

**Comment by pbajjuri20** [comment]
Tested and Passed on Kiali UI 1.23.0 (3f048f913ef22f26bd014783d9371cb1aca44657)

**Pull request merged**
