### PR TITLE
List views alignment issue

### PR DESCRIPTION
**Pull request by jshaughn**
This is a tricky issue (at least for me).  The problem occurs because of the width taken by the scroll bar when the virtual list requires scrolling.  Initially I thought it was due to problems with the cell rendering itself, but eventually I discovered the root cause.  A fix is difficult, or possibly just difficult for me given a lack of experience with visual orientation issues.  But because the Virtual table body is rendered independently of the table header, when the body width is reduced the cells compress slightly, but the header positions do not change.

On Chrome (webkit) the problem is solvable with a proprietary setting (overflowY: 'overlay'), but this does not exist on FF or Edge.  This PR contains the Chrome solution but this would still be a known issue for non-chrome browsers.  Perhaps someone else has a good idea, I'll set this to Draft and ask for review/suggestions from the UI heavy hitters...

note, there is also a small change/fix to the "Details' rendering, which may have contributed an additional issue, although I'm not positive it was a problem.

Finally, this updates the package for virtualized extension, because I was hoping it would resolve the issue. This ends up basically updating react.  The update is not required and I'll roll it back if and when this PR goes live.

Partial fix for https://github.com/kiali/kiali/issues/1710.

p.s. There is an unrelated fix to remove an unused and misleading 'style' property from MissingSidecar.
p.s. There is an unrelated fix to the version in package.json.

### CODE REVIEW

**Comment by mtho11** [comment]
Maybe https://modernizr.com/docs/#what-is-modernizr is a better way to detect this feature?

I looked for other css overflow polyfills buf didn't find any.

**Comment by aljesusg** [comment]
We should report this to pf team, I'll open an issue about this

**Comment by aljesusg** [comment]
Yes @mtho11, we can proceed with a workaround, my point is that we have a lot of lines in the css override file because components have different behaviour in Chrome than FF, PF4 team asked us why we import the css in this way (like openshift because we use PF3 & PF4) so maybe this things will be fixed . I think that the problem is in the PF3 css with the PF4 css so we prefer to finish the migration before change the css.

**Comment by jshaughn** [comment]
> We should report this to pf team, I'll open an issue about this

@aljesusg , thanks.  Sorry, I was trying to reduce the PF4 work for you and still it ends up being work for you ;-(

Do you think we should proceed with the Chrome-only workaround until maybe we get a PF fix?  @mtho11 I'm a little nervous about introducing a new dep like modernizr (although it's neat).  With respect to the 'overlay' chrome feature, it' proprietary and it is not going to show up in FF.  The alignment problem is annoying but not critical.

**Comment by aljesusg** [comment]
> > We should report this to pf team, I'll open an issue about this
> 
> @aljesusg , thanks. Sorry, I was trying to reduce the PF4 work for you and still it ends up being work for you ;-(
> 
> Do you think we should proceed with the Chrome-only workaround until maybe we get a PF fix? @mtho11 I'm a little nervous about introducing a new dep like modernizr (although it's neat). With respect to the 'overlay' chrome feature, it' proprietary and it is not going to show up in FF. The alignment problem is annoying but not critical.

No @jshaughn we should merge this if there is a problem about css in FF. My point is about to clean all these patchs after the migration with the PF4 team tips, so go ahead !!!.

**Comment by mtho11** [comment]
@jshaughn can we get some before/after screenshots? It will help people just quickly scanning the issue to easily see the changes.

**Comment by mtho11** [comment]
I still like the **Modernizer** approach to targeting browser _capabilities_ and not a specific browser hack. Browsers are constantly updating and their _capabilities_ constantly changing and some users change slower or faster (think ESR versions and even mobile/tablet versions). IMO browser capabilities are a better way to address cross-browser compatibility than browser types or versions.

**Comment by jshaughn** [comment]
> can we get some before/after screenshots? 

Before (and currently on FF):
image

After (on WebKit browsers: chrome, safari. opera):
image

**Pull request merged**
