### PR TITLE
KIALI-1114 Allow IstioConfig list show warning messages

### PR DESCRIPTION
**Pull request by aljesusg**
Jira: [KIALI-1114](https://issues.jboss.org/browse/KIALI-1114)

peek 2018-07-10 22-16

### CODE REVIEW

**Comment by lucasponce** [comment]
Is the filter updated ?

**Comment by aljesusg** [comment]
No @lucasponce I sent the Pull Request because I wanna make a question ^^ What do you think about show  instead number of issues , the number of warnings and number of errors?

**Comment by lucasponce** [comment]
> No @lucasponce I sent the Pull Request because I wanna make a question ^^ What do you think about show instead number of issues , the number of warnings and number of errors?

+1 sounds good.

**Comment by abonas** [comment]
@aljesusg IMO number of errors and number of warnings sounds much better than general number of issues.
cc @kiali/ux-reviewers what do you think?

**Comment by aljesusg** [comment]
Great @abonas  so I'll remove number of total issues in that case, @lucasponce if there is only warnings issues the config is valid or not valid??

**Comment by serenamarie125** [comment]
👍🏼 To including the actual number @aljesusg

**Comment by lucasponce** [comment]
> Great @abonas so I'll remove number of total issues in that case, @lucasponce if there is only warnings issues the config is valid or not valid??

Filter should be updated to manage four states then, error, warning, valid and not validated. To let user work with all combination of results.
(Today it manages three, but we should split the not valid in the error and warning ones).

**Comment by aljesusg** [comment]
That's my point @lucasponce now there are Istio objects with warning issues and no errors and the config is not valid.

**Comment by aljesusg** [comment]
@serenamarie125 the total issues number in addition to number of errors issues and number of warning issues?

**Comment by cshinn** [comment]
@aljesusg are there other types of issues besides warnings and errors? If not, I don't think having a total would be more helpful than listing them separately

**Comment by aljesusg** [comment]
Updated
peek 2018-07-09 21-11

**Comment by aljesusg** [comment]
Last update removing lines @cshinn 

peek 2018-07-09 23-45

**Comment by aljesusg** [comment]
mmm maybe let me check it. Thanks @lucasponce

**Comment by aljesusg** [comment]
Updated 

peek 2018-07-10 22-16

**Comment by cshinn** [comment]
@aljesusg looks great!

**Comment by lucasponce** [comment]
@aljesusg I'm testing locally master but I have this

image

I guess the expected behaviour would be to show the warning icon.

**Pull request merged**
