### PR TITLE
Fix empty trace tabs with no trace

### PR DESCRIPTION
**Pull request by jotak**
Fixes https://github.com/kiali/kiali/issues/3299

Also: when the trace ID doesn't exist, remove it from URL

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM

**Review by hhovsepy — COMMENTED** [review]
Verified the original issue, just I see some other issue with Grafana traces.
Screenshot from 2020-10-08 09-55-55
Screenshot from 2020-10-08 10-03-53

**Review by hhovsepy — APPROVED** [review]
Verified as the grafana issue is not related to this PR.

**Comment by jotak** [comment]
Thanks.
I'm going to look at the issue with grafana

**Pull request merged**
